import type { AmalBob } from "./types";

export const AMALIY: AmalBob[] = [
  {id:1,harflar:["ت","ب","أ"],nomlar:["Ta","Ba","Hamza"],mavzu:"Jahr va Hams",
   maxraj:[{h:"ت",mx:"Tarafi Lison (til uchi—tish)",iz:"Til uchining yuqori tish orqasiga teginishi."},{h:"ب",mx:"Shafatayn (lab-lab)",iz:"Ikki lab bir-biriga yopiladi, portlatib chiqariladi."},{h:"أ",mx:"Adnal Halq",iz:"Tomoqning eng yuqori qismi. Havo to'liq to'xtatiladi — glottal stop."}],
   sifatlar:[{h:"ت",sf:["Shadid","Hams","Istifol","Infitoh","Izloq"]},{h:"ب",sf:["Shadid","Jahr","Istifol","Infitoh","Izloq"]},{h:"أ",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ت",m:"ت",b:"تـ",o:"ـتـ",x:"ـت",iz:"Ikki nuqta ustida"},{h:"ب",m:"ب",b:"بـ",o:"ـبـ",x:"ـب",iz:"Ba to'rt holatda bog'lanadi"},{h:"أ",m:"أ",b:"أ",o:"ـأ",x:"ـأ",iz:"Alif faqat oldingi harfga ulanadi"}],
   harakatlar:[{h:"ت",f:"تَ",k:"تِ",d:"تُ",s:"تْ",of:"ta",ok:"ti",od:"tu",os:"t"},{h:"ب",f:"بَ",k:"بِ",d:"بُ",s:"بْ",of:"ba",ok:"bi",od:"bu",os:"b"},{h:"أ",f:"أَ",k:"أِ",d:"أُ",s:"أْ",of:"a",ok:"i",od:"u",os:"hamza"}],
   sozlar:[{ar:"أَب",oq:"Ab",tr:"Ota",h:"أ+ب"},{ar:"بَاب",oq:"Baab",tr:"Eshik",h:"ب+ا+ب"},{ar:"بَيْت",oq:"Bayt",tr:"Uy",h:"ب+ي+ت"},{ar:"تَمْر",oq:"Tamr",tr:"Xurmo",h:"ت+م+ر"},{ar:"تَاجِر",oq:"Taajir",tr:"Savdogar",h:"ت+ا+ج+ر"},{ar:"أَكْبَر",oq:"Akbar",tr:"Kattaroq",h:"أ+ك+ب+ر"}],
   oqish:[{ar:"تَ تِ تُ تْ",iz:"Ta ning 4 harakati"},{ar:"بَ بِ بُ بْ",iz:"Ba ning 4 harakati"},{ar:"أَبٌ",iz:"Ab-un — ota"},{ar:"بَابٌ",iz:"Baab — eshik"},{ar:"أَبٌ كَبِيرٌ",iz:"Katta ota"}],
   yozish:[{t:"Ta, Ba va Alif harflarining shakllarini yozing",m:"تـ ـتـ ـت ت / بـ ـبـ ـب ب / أ"},{t:"'Bayt' so'zini harakat bilan yozing",m:"بَيْتٌ"},{t:"Alif+Ba birikmasini yozing",m:"أَب"}],
   uyvazifa:["أ, ب, ت harflarini 5 martadan yozing","Jahr (أ, ب) va Hams (ت) sifatlarini tushuntiring","'Bayt','Ab','Tamr' ni 10 marta o'qing"],
   test:[
     {s:"ت harfining maxraji qaysi?",v:["Lab (shafatayn)","Tomoq (halq)","Til uchi — tish","Burun"],t:2},
     {s:"ب harfining maxraji qaysi?",v:["Halq (tomoq)","Lison (til)","Shafatayn (lab-lab)","Jawf (bo'shliq)"],t:2},
     {s:"أ harfining maxraji qaysi?",v:["Vasat Halq","Adnal Halq","Aqsal Halq","Shafatayn"],t:1},
     {s:"Bu darsda Jahr sifati qaysi harflarda bor?",v:["Faqat ت da","أ va ب da","Faqat أ da","Hech qaysisida"],t:1},
     {s:"Bu darsda Hams sifati qaysi harfda bor?",v:["أ","ب","ت","Hammasida"],t:2},
     {s:"بَ qanday o'qiladi?",v:["bi","bu","ba","b"],t:2},
     {s:"تَ qanday o'qiladi?",v:["ti","tu","ta","t"],t:2},
     {s:"بَيْتٌ so'zining ma'nosi?",v:["Kitob","Eshik","Uy","Bola"],t:2},
     {s:"أَب so'zining ma'nosi?",v:["Aka","Eshik","Ota","Bola"],t:2},
     {s:"تَمْر so'zining ma'nosi?",v:["Kiyim","Uy","Xurmo","Uch"],t:2}
   ]},

  {id:2,harflar:["ج","ث"],nomlar:["Jim","Sa"],mavzu:"Shadid va Raxv",
   maxraj:[{h:"ج",mx:"Vasat Lison",iz:"Tilning o'rta qismi tanglay tomon ko'tariladi."},{h:"ث",mx:"Tarafi Lison (tish oraliq)",iz:"Til uchi ikki tish orasiga chiqariladi — 'think' dagi 'th'."}],
   sifatlar:[{h:"ج",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"ث",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ج",m:"ج",b:"جـ",o:"ـجـ",x:"ـج",iz:"Bir nuqta pastida"},{h:"ث",m:"ث",b:"ثـ",o:"ـثـ",x:"ـث",iz:"Uch nuqta ustida"}],
   harakatlar:[{h:"ج",f:"جَ",k:"جِ",d:"جُ",s:"جْ",of:"ja",ok:"ji",od:"ju",os:"j"},{h:"ث",f:"ثَ",k:"ثِ",d:"ثُ",s:"ثْ",of:"θa",ok:"θi",od:"θu",os:"θ"}],
   sozlar:[{ar:"جَمَل",oq:"Jamal",tr:"Tuya",h:"ج+م+ل"},{ar:"جَاءَ",oq:"Jaa'a",tr:"Keldi",h:"ج+ا+ء"},{ar:"أَجَل",oq:"Ajal",tr:"Ha",h:"أ+ج+ل"},{ar:"ثَوْب",oq:"θawb",tr:"Kiyim",h:"ث+و+ب"},{ar:"ثَلَاثَة",oq:"θalaθa",tr:"Uch",h:"ث+ل+ا+ث"}],
   oqish:[{ar:"جَ جِ جُ جْ",iz:"Jim 4 harakati"},{ar:"ثَ ثِ ثُ ثْ",iz:"Sa (tilni chiqarib)"},{ar:"جَمَلٌ كَبِيرٌ",iz:"Katta tuya"},{ar:"ثَلَاثَةٌ",iz:"Uch"},{ar:"جَاءَ الرَّجُلُ",iz:"Erkak keldi"}],
   yozish:[{t:"ج va ث farqini yozing",m:"ج(1 nuqta pastida)—ث(3 nuqta ustida)"},{t:"'Jamal' yozing",m:"جَمَلٌ"},{t:"'θalaθa' yozing",m:"ثَلَاثَةٌ"}],
   uyvazifa:["ج va ث ni 5 martadan yozing","Shadid (ج) va Raxv (ث) sifatlarini tushuntiring","'Jamal','θawb','θalaθa' yod oling"],
   test:[
     {s:"ج harfining maxraji qaysi?",v:["Vasat Halq","Vasat Lison","Adnal Halq","Shafatayn"],t:1},
     {s:"ث qanday talaffuz qilinadi?",v:["Oddiy 's' kabi","Tilni tishlar orasiga chiqarib jarangsiz","Qalin 's' kabi","Tomoqdan"],t:1},
     {s:"ج ning kuchli/zaif sifati?",v:["Raxv","Tavassut","Shadid","Lin"],t:2},
     {s:"ث ning kuchli/zaif sifati?",v:["Shadid","Tavassut","Raxv","Qalqala"],t:2},
     {s:"Shadid sifati nimani anglatadi?",v:["Havo to'liq to'xtaydi, portlash bilan chiqadi","Havo erkin oqib chiqadi","Til titraydi","Havo burundan chiqadi"],t:0},
     {s:"Raxv sifati nimani anglatadi?",v:["Havo erkin/davomli oqib chiqadi","Havo to'liq to'xtaydi","Til tishlar orasida qisiladi","Havo burun orqali chiqadi"],t:0},
     {s:"جَمَل so'zining ma'nosi?",v:["Tosh","Tuya","Sevgi","Keldi"],t:1},
     {s:"ثَوْب so'zining ma'nosi?",v:["Xurmo","Kiyim","Uy","Savdogar"],t:1},
     {s:"ثَلَاثَة nechani anglatadi?",v:["Ikki","Uch","To'rt","Besh"],t:1},
     {s:"ج va ث yozuvdagi farqi?",v:["Maxraj farqi","ج bir nuqta pastida, ث uch nuqta ustida","Sifat soni","Shakl tamoman boshqa"],t:1}
   ]},

  {id:3,harflar:["ح","خ"],nomlar:["Ha","Xo"],mavzu:"Iste'lo va Istefol",
   maxraj:[{h:"ح",mx:"Vasat Halq",iz:"Tomoqning o'rta qismidan chuqur nafas — jarangsiz."},{h:"خ",mx:"Aqsal Halq",iz:"Tomoqning pastki qismidan jarangsiz — o'zbek 'x' chuqurroq."}],
   sifatlar:[{h:"ح",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]},{h:"خ",sf:["Raxv","Hams","Isti'lo","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ح",m:"ح",b:"حـ",o:"ـحـ",x:"ـح",iz:"Nuqtasiz"},{h:"خ",m:"خ",b:"خـ",o:"ـخـ",x:"ـخ",iz:"Bir nuqta (ح ga o'xshash shakl)"}],
   harakatlar:[{h:"ح",f:"حَ",k:"حِ",d:"حُ",s:"حْ",of:"ħa",ok:"ħi",od:"ħu",os:"ħ"},{h:"خ",f:"خَ",k:"خِ",d:"خُ",s:"خْ",of:"xa",ok:"xi",od:"xu",os:"x"}],
   sozlar:[{ar:"حَجَر",oq:"Ħajar",tr:"Tosh",h:"ح+ج+ر"},{ar:"حُبٌّ",oq:"Ħubb",tr:"Sevgi",h:"ح+ب"},{ar:"خُبْز",oq:"Xubz",tr:"Non",h:"خ+ب+ز"},{ar:"خَيْر",oq:"Xayr",tr:"Yaxshilik",h:"خ+ي+ر"},{ar:"أَخٌ",oq:"Ax",tr:"Aka",h:"أ+خ"}],
   oqish:[{ar:"حَ حِ حُ حْ",iz:"Ha (tomoqdan chuqur nafas)"},{ar:"خَ خِ خُ خْ",iz:"Xo 4 harakati"},{ar:"حُبُّ الأَبِ",iz:"Ota sevgisi"},{ar:"حَجَرٌ كَبِيرٌ",iz:"Katta tosh"},{ar:"خَيْرٌ كَثِيرٌ",iz:"Ko'p yaxshilik"}],
   yozish:[{t:"ح va خ farqini yozing",m:"ح(nuqtasiz)—خ(bir nuqta)"},{t:"'Xubz' yozing",m:"خُبْزٌ"},{t:"'Ħubb' yozing",m:"حُبٌّ"}],
   uyvazifa:["ح va خ ni 5 martadan yozing","Isti'lo (خ) va Istifol (ح) sifatlarini tushuntiring","'Xayr','Ħajar','Xubz' yod oling"],
   test:[
     {s:"ح harfining maxraji qaysi?",v:["Adnal Halq","Aqsal Halq","Vasat Halq","Jawf"],t:2},
     {s:"خ harfining maxraji qaysi?",v:["Adnal Halq","Vasat Halq","Aqsal Halq","Jawf"],t:2},
     {s:"خ ning ko'tarilgan/pastlangan sifati?",v:["Istifol","Isti'lo","Infitoh","Itboq"],t:1},
     {s:"ح ning ko'tarilgan/pastlangan sifati?",v:["Istifol","Isti'lo","Infitoh","Itboq"],t:0},
     {s:"Isti'lo sifati nimani anglatadi?",v:["Til orqasi tanglayga ko'tariladi (qalinlashadi)","Til pastda qoladi (ingichka)","Havo burundan chiqadi","Til titraydi"],t:0},
     {s:"حَجَر so'zining ma'nosi?",v:["Tuya","Ha","Tosh","Sevgi"],t:2},
     {s:"حُبٌّ so'zining ma'nosi?",v:["Tosh","Tuya","Sevgi","Eshik"],t:2},
     {s:"خُبْز so'zining ma'nosi?",v:["Dars","Non","Aka","Uy"],t:1},
     {s:"أَخٌ so'zining ma'nosi?",v:["Ota","Aka","Uy","Dars"],t:1},
     {s:"خ va ح farqi nima?",v:["Maxraj farqi","خ bir nuqtali, ح nuqtasiz","Sifat soni","Shakl tamoman boshqa"],t:1}
   ]},

  {id:4,harflar:["ذ","د"],nomlar:["Zal","Dal"],mavzu:"Itbaq va Infitah",
   maxraj:[{h:"ذ",mx:"Tarafi Lison (tish oraliq, jarangli)",iz:"Til uchi tishlar orasiga — 'this' dagi 'dh'."},{h:"د",mx:"Tarafi Lison (til uchi—tish)",iz:"Portlovchi jarangli tovush."}],
   sifatlar:[{h:"ذ",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"د",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ذ",m:"ذ",b:"ذ",o:"ـذ",x:"ـذ",iz:"Faqat o'ngga — bir nuqta"},{h:"د",m:"د",b:"د",o:"ـد",x:"ـد",iz:"Faqat o'ng tomonga — nuqtasiz"}],
   harakatlar:[{h:"ذ",f:"ذَ",k:"ذِ",d:"ذُ",s:"ذْ",of:"ða",ok:"ði",od:"ðu",os:"ð"},{h:"د",f:"دَ",k:"دِ",d:"دُ",s:"دْ",of:"da",ok:"di",od:"du",os:"d"}],
   sozlar:[{ar:"ذَهَبَ",oq:"Zahaba",tr:"Ketdi",h:"ذ+ه+ب"},{ar:"هَذَا",oq:"Haazaa",tr:"Bu",h:"ه+ذ+ا"},{ar:"ذَكَاء",oq:"Zakaau",tr:"Aql/Ziyraklik",h:"ذ+ك+ا+ء"},{ar:"دَرْس",oq:"Dars",tr:"Dars",h:"د+ر+س"},{ar:"دَار",oq:"Daar",tr:"Uy",h:"د+ا+ر"}],
   oqish:[{ar:"ذَ ذِ ذُ ذْ",iz:"Zal (tilni chiqarib jarangli)"},{ar:"دَ دِ دُ دْ",iz:"Dal 4 harakati"},{ar:"هَذَا كِتَابٌ",iz:"Bu kitob"},{ar:"ذَهَبَ الرَّجُلُ",iz:"Erkak ketdi"},{ar:"دَرَسَ الْوَلَدُ",iz:"Bola o'qidi"}],
   yozish:[{t:"ذ va د farqini yozing",m:"ذ(nuqtali)—د(nuqtasiz)"},{t:"'Zaahaba' yozing",m:"ذَهَبَ"},{t:"'Dars' yozing",m:"دَرْسٌ"}],
   uyvazifa:["ذ va د ni 5 martadan yozing","ذ va د farqini tovush va yozuvda ko'rsating","'Haazaa','Zakaau','Dars' yod oling"],
   test:[
     {s:"ذ qanday talaffuz qilinadi?",v:["Tilni tishlar orasiga chiqarib jarangsiz","Tilni tishlar orasiga chiqarib jarangli","Oddiy z kabi","Tomoqdan"],t:1},
     {s:"د harfining maxraji qaysi?",v:["Shafatayn","Vasat Lison","Tarafi Lison (til uchi—tish)","Halq"],t:2},
     {s:"ذ ning jarangli/jarangsiz sifati?",v:["Jahr","Hams","Safir","G'unna"],t:0},
     {s:"د ning jarangli/jarangsiz sifati?",v:["Hams","Jahr","Tafashi","Safir"],t:1},
     {s:"د faqat qaysi tomonga bog'lanadi?",v:["Ikki tomonga","Chap tomonga","O'ng tomonga (faqat)","Ulanmaydi"],t:2},
     {s:"ذَهَبَ so'zining ma'nosi?",v:["Keldi","Ketdi","O'tirdi","Yozdi"],t:1},
     {s:"هَذَا so'zining ma'nosi?",v:["U","Men","Bu","Siz"],t:2},
     {s:"دَرْس so'zining ma'nosi?",v:["Uy","Non","Dars","Yaxshilik"],t:2},
     {s:"ذَكَاء so'zining ma'nosi?",v:["Ketdi","Erkak","Bu","Aql/Ziyraklik"],t:3},
     {s:"ذ va د ning maxraji qaysi guruhga kiradi?",v:["Shafatayn","Halq","Tarafi Lison (til uchi)","Jawf"],t:2}
   ]},

  {id:5,harflar:["ز","ر"],nomlar:["Zayn","Ra"],mavzu:"Izlaq va Ismat",
   maxraj:[{h:"ز",mx:"Tarafi Lison (tish izi, jarangli)",iz:"Jarangli z, Safir sifati."},{h:"ر",mx:"Tarafi Lison (til uchi—milk)",iz:"Til uchi yuqori milkka tegib, titrab chiqadi — Takrir."}],
   sifatlar:[{h:"ز",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Safir"]},{h:"ر",sf:["Tavassut","Jahr","Istifol/Isti'lo","Infitoh","Takrir","Inhiraf","Izloq"]}],
   shakllar:[{h:"ز",m:"ز",b:"ز",o:"ـز",x:"ـز",iz:"Faqat o'ngga — bir nuqta"},{h:"ر",m:"ر",b:"ر",o:"ـر",x:"ـر",iz:"Faqat o'ngga — nuqtasiz"}],
   harakatlar:[{h:"ز",f:"زَ",k:"زِ",d:"زُ",s:"زْ",of:"za",ok:"zi",od:"zu",os:"z"},{h:"ر",f:"رَ",k:"رِ",d:"رُ",s:"رْ",of:"ra",ok:"ri",od:"ru",os:"r"}],
   sozlar:[{ar:"زَيْد",oq:"Zayd",tr:"(Ism)",h:"ز+ي+د"},{ar:"زَرَعَ",oq:"Zaraa",tr:"Ekdi",h:"ز+ر+ع"},{ar:"بَازَار",oq:"Baazaar",tr:"Bozor",h:"ب+ا+ز+ا+ر"},{ar:"رَجُل",oq:"Rajul",tr:"Erkak",h:"ر+ج+ل"},{ar:"دَرَسَ",oq:"Darasa",tr:"O'qidi",h:"د+ر+س"}],
   oqish:[{ar:"زَ زِ زُ زْ",iz:"Zayn 4 harakati"},{ar:"رَ رِ رُ رْ",iz:"Ra (til titrab chiqadi)"},{ar:"زَرَعَ الأَبُ",iz:"Ota ekdi"},{ar:"دَرَسَ الرَّجُلُ",iz:"Erkak o'qidi"},{ar:"رَجُلٌ وَزَيْدٌ",iz:"Erkak va Zayd"}],
   yozish:[{t:"ز va ر farqini yozing",m:"ز(nuqtali)—ر(nuqtasiz)"},{t:"Ra — Takrir sifatini tushuntir",m:"ر titraydi"},{t:"'Zaraa' yozing",m:"زَرَعَ"}],
   uyvazifa:["ز va ر ni 5 martadan yozing","Izloq (ر) sifatini tushuntiring — nima uchun ر Izloq harfi?","'Zayd','Rajul','Zaraa' yod oling"],
   test:[
     {s:"ز harfining maxraji qaysi guruhga kiradi?",v:["Shafatayn","Halq","Tarafi Lison (til—tish)","Jawf"],t:2},
     {s:"ر ning maxsus sifati (titrab chiqishi)?",v:["Safir","Tafashi","Takrir","G'unna"],t:2},
     {s:"ر nima uchun 'Izloq' harfi hisoblanadi?",v:["Til uchi yengil, ravon chiqadi","Havo burundan chiqadi","Til qattiq tishga tegadi","Ovoz umuman chiqmaydi"],t:0},
     {s:"ز ning jarangli/jarangsiz sifati?",v:["Jahr","Hams","Safir","Qalqala"],t:0},
     {s:"Safir sifatiga ega harflar?",v:["ل ر ن","ز س ص","ن م","و ي"],t:1},
     {s:"زَيْد so'zi nimani anglatadi?",v:["Bozor","Ism","Erkak","Ekish"],t:1},
     {s:"رَجُل so'zining ma'nosi?",v:["Bola","Erkak","Ayol","Ota"],t:1},
     {s:"زَرَعَ so'zining ma'nosi?",v:["Ketdi","O'qidi","Ekdi","Keldi"],t:2},
     {s:"ذ va ر — ز va ر ikkalasi ham qaysi tomonga bog'lanadi?",v:["Ikki tomonga","Chap tomonga","Faqat o'ng tomonga","Ulanmaydi"],t:2},
     {s:"دَرَسَ so'zining ma'nosi?",v:["Ketdi","Keldi","O'qidi","Yedi"],t:2}
   ]},

  {id:6,harflar:["ش","س"],nomlar:["Shin","Sin"],mavzu:"Sin va Shin",
   maxraj:[{h:"ش",mx:"Vasat Lison",iz:"Havo keng yoyiladi — Tafashi sifati."},{h:"س",mx:"Tarafi Lison (tish izi, jarangsiz)",iz:"Jarangsiz s, Safir sifati."}],
   sifatlar:[{h:"ش",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq","Tafashi"]},{h:"س",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq","Safir"]}],
   shakllar:[{h:"ش",m:"ش",b:"شـ",o:"ـشـ",x:"ـش",iz:"Uch nuqta (س ga o'xshash shakl)"},{h:"س",m:"س",b:"سـ",o:"ـسـ",x:"ـس",iz:"To'rt tomonga — nuqtasiz"}],
   harakatlar:[{h:"ش",f:"شَ",k:"شِ",d:"شُ",s:"شْ",of:"sha",ok:"shi",od:"shu",os:"sh"},{h:"س",f:"سَ",k:"سِ",d:"سُ",s:"سْ",of:"sa",ok:"si",od:"su",os:"s"}],
   sozlar:[{ar:"شَمْس",oq:"Shams",tr:"Quyosh",h:"ش+م+س"},{ar:"شَجَر",oq:"Shajar",tr:"Daraxt",h:"ش+ج+ر"},{ar:"أَشْجَار",oq:"Ashjaar",tr:"Daraxtlar",h:"أ+ش+ج+ا+ر"},{ar:"سَمَاء",oq:"Samaau",tr:"Osmon",h:"س+م+ا+ء"},{ar:"بَازَار",oq:"Baazaar",tr:"Bozor",h:"ب+ا+ز+ا+ر"}],
   oqish:[{ar:"شَ شِ شُ شْ",iz:"Shin 4 harakati"},{ar:"سَ سِ سُ سْ",iz:"Sin 4 harakati"},{ar:"شَمْسٌ مُشْرِقَةٌ",iz:"Yorqin quyosh"},{ar:"سَمَاءٌ صَافِيَةٌ",iz:"Tiniq osmon"},{ar:"شَجَرٌ وَسَمَاءٌ",iz:"Daraxt va osmon"}],
   yozish:[{t:"ش va س farqini yozing",m:"ش(3 nuqta)—س(nuqtasiz)"},{t:"'Shams' yozing",m:"شَمْسٌ"},{t:"'Samaau' yozing",m:"سَمَاءٌ"}],
   uyvazifa:["ش va س ni 5 martadan yozing","Tafashi (ش) va Safir (س) sifatlarini tushuntiring","'Shams','Shajar','Samaau' yod oling"],
   test:[
     {s:"Tafashi sifati qaysi harfda bor?",v:["س","ز","ش","ص"],t:2},
     {s:"Tafashi sifati nimani anglatadi?",v:["Til titraydi","Havo og'iz bo'ylab keng yoyiladi","Havo burundan chiqadi","Til yon tomoni uzayadi"],t:1},
     {s:"Safir sifati nima?",v:["Havo burundan chiqadi","Hushtak (shovqin) ovozi hosil bo'ladi","Til titraydi","Havo keng yoyiladi"],t:1},
     {s:"ش va س yozuvdagi farqi?",v:["Maxraj farqi","ش uch nuqta ustida, س nuqtasiz","Sifat soni","Shakl tamoman boshqa"],t:1},
     {s:"س harfi yozuvda necha tomonga bog'lanadi?",v:["Faqat o'ngga","Ikki tomonga (to'rt holatda)","Faqat chapga","Ulanmaydi"],t:1},
     {s:"شَمْس so'zining ma'nosi?",v:["Oy","Quyosh","Yulduz","Osmon"],t:1},
     {s:"شَجَر so'zining ma'nosi?",v:["Quyosh","Sabr","Daraxt","Do'st"],t:2},
     {s:"سَمَاء so'zining ma'nosi?",v:["Osmon","Bozor","Ism","Ekdi"],t:0},
     {s:"س ning jarangli/jarangsiz sifati?",v:["Jahr","Hams","Safir","G'unna"],t:1},
     {s:"ش ning jarangli/jarangsiz sifati?",v:["Jahr","Hams","Tafashi","Safir"],t:1}
   ]},

  {id:7,harflar:["ص","ض"],nomlar:["Sod","Dod"],mavzu:"Sod va Zod",
   maxraj:[{h:"ص",mx:"Tarafi Lison (qalin)",iz:"Sin kabi joyda, lekin til orqasi ko'tarilgan — qalin s."},{h:"ض",mx:"Hafat Lison (til yon tomoni)",iz:"Tilning yon tomoni milkka — Istitoyla sifati."}],
   sifatlar:[{h:"ص",sf:["Raxv","Hams","Isti'lo","Itboq","Ishmoq","Safir"]},{h:"ض",sf:["Raxv","Jahr","Isti'lo","Itboq","Ishmoq","Istitoyla"]}],
   shakllar:[{h:"ص",m:"ص",b:"صـ",o:"ـصـ",x:"ـص",iz:"Nuqtasiz, yumaloq"},{h:"ض",m:"ض",b:"ضـ",o:"ـضـ",x:"ـض",iz:"Nuqtali (ص ga o'xshash)"}],
   harakatlar:[{h:"ص",f:"صَ",k:"صِ",d:"صُ",s:"صْ",of:"ṣa",ok:"ṣi",od:"ṣu",os:"ṣ"},{h:"ض",f:"ضَ",k:"ضِ",d:"ضُ",s:"ضْ",of:"ḍa",ok:"ḍi",od:"ḍu",os:"ḍ"}],
   sozlar:[{ar:"صَارَ",oq:"Ṣaara",tr:"Bo'ldi",h:"ص+ا+ر"},{ar:"صَدِيق",oq:"Ṣadiiq",tr:"Do'st",h:"ص+د+ي+ق"},{ar:"ضَرَبَ",oq:"Ḍaraba",tr:"Urdi",h:"ض+ر+ب"},{ar:"أَرْض",oq:"Arḍ",tr:"Yer",h:"أ+ر+ض"},{ar:"رِيَاضَة",oq:"Riyaada",tr:"Sport",h:"ر+ي+ا+ض+ة"}],
   oqish:[{ar:"صَ صِ صُ صْ",iz:"Sod, qalin s!"},{ar:"ضَ ضِ ضُ ضْ",iz:"Dod 4 harakati"},{ar:"صَوْتٌ جَمِيلٌ",iz:"Go'zal ovoz"},{ar:"أَرْضٌ وَسَمَاءٌ",iz:"Yer va osmon"},{ar:"صَدِيقٌ وَفِيٌّ",iz:"Sodiq do'st"}],
   yozish:[{t:"ص va ض farqini yozing",m:"ص(nuqtasiz)—ض(nuqtali)"},{t:"'Ṣadiiq' yozing",m:"صَدِيقٌ"},{t:"Istitoyla sifatini tushuntir",m:"Til yon tomoni uzayib chiqadi"}],
   uyvazifa:["ص va ض ni 5 martadan yozing","Isti'lo va Itboq sifatlarini tushuntiring","'Ṣaara','Ḍaraba','Arḍ' yod oling"],
   test:[
     {s:"ص harfining maxraji qaysi guruhga kiradi?",v:["Shafatayn","Halq","Tarafi Lison (til-tish, qalin)","Jawf"],t:2},
     {s:"ض harfining maxraji qaysi?",v:["Shafatayn","Hafat Lison (til yon tomoni)","Tarafi Lison","Halq"],t:1},
     {s:"Istitoyla sifati qaysi harfda bor?",v:["ط","ص","ض","ظ"],t:2},
     {s:"Istitoyla sifati nimani anglatadi?",v:["Havo keng yoyiladi","Tilning yon tomoni uzayib milkka tegadi","Havo burundan chiqadi","Til titraydi"],t:1},
     {s:"ص ning ko'tarilish sifati?",v:["Istifol","Isti'lo","Infitoh","Inhiraf"],t:1},
     {s:"ض ning kuchli/zaif sifati?",v:["Shadid","Raxv","Tavassut","Qalqala"],t:1},
     {s:"صَارَ so'zining ma'nosi?",v:["Ketdi","Bo'ldi","Keldi","Ekdi"],t:1},
     {s:"أَرْض so'zining ma'nosi?",v:["Osmon","Yo'l","Yer","Doktor"],t:2},
     {s:"ضَرَبَ so'zining ma'nosi?",v:["Ketdi","Keldi","O'qidi","Urdi"],t:3},
     {s:"ص va ض yozuvdagi farqi?",v:["Maxraj farqi","ص nuqtasiz, ض nuqtali","Sifat soni","Shakl tamoman boshqa"],t:1}
   ]},

  {id:8,harflar:["ط","ظ"],nomlar:["To","Zo"],mavzu:"To va Zo",
   maxraj:[{h:"ط",mx:"Tarafi Lison (til uchi—tish, qalin)",iz:"Qalin t — til orqasi ko'tarilgan."},{h:"ظ",mx:"Tarafi Lison (tish oraliq, qalin, jarangli)",iz:"Tilni chiqarib, til orqasi ko'tarilgan — qalin jarangli."}],
   sifatlar:[{h:"ط",sf:["Shadid","Jahr","Isti'lo","Itboq","Ishmoq"]},{h:"ظ",sf:["Raxv","Jahr","Isti'lo","Itboq","Ishmoq"]}],
   shakllar:[{h:"ط",m:"ط",b:"طـ",o:"ـطـ",x:"ـط",iz:"Nuqtasiz, halqali"},{h:"ظ",m:"ظ",b:"ظـ",o:"ـظـ",x:"ـظ",iz:"Nuqta ustida (ط ga o'xshash)"}],
   harakatlar:[{h:"ط",f:"طَ",k:"طِ",d:"طُ",s:"طْ",of:"ṭa",ok:"ṭi",od:"ṭu",os:"ṭ"},{h:"ظ",f:"ظَ",k:"ظِ",d:"ظُ",s:"ظْ",of:"ẓa",ok:"ẓi",od:"ẓu",os:"ẓ"}],
   sozlar:[{ar:"طَرِيق",oq:"Ṭariiq",tr:"Yo'l",h:"ط+ر+ي+ق"},{ar:"طَبِيب",oq:"Ṭabiib",tr:"Doktor",h:"ط+ب+ي+ب"},{ar:"ظَهَرَ",oq:"Ẓahara",tr:"Ko'rindi",h:"ظ+ه+ر"},{ar:"حَظٌّ",oq:"Ħaẓẓ",tr:"Baxt",h:"ح+ظ"}],
   oqish:[{ar:"طَ طِ طُ طْ",iz:"To (qalin t)"},{ar:"ظَ ظِ ظُ ظْ",iz:"Zo (tilni chiqarib qalin)"},{ar:"طَرِيقٌ طَوِيلٌ",iz:"Uzun yo'l"},{ar:"طَبِيبٌ مَاهِرٌ",iz:"Mohir doktor"},{ar:"ظَهَرَ الْحَقُّ",iz:"Haq namoyon bo'ldi"}],
   yozish:[{t:"ط va ظ farqini yozing",m:"ط(nuqtasiz)—ظ(nuqta ustida)"},{t:"'Ṭariiq' yozing",m:"طَرِيقٌ"},{t:"'Ẓahara' yozing",m:"ظَهَرَ"}],
   uyvazifa:["ط va ظ ni 5 martadan yozing","ط va ظ ikkalasi ham Itboq harfi ekanini tushuntiring","'Ṭabiib','Ẓahara','Ħaẓẓ' yod oling"],
   test:[
     {s:"ط harfining maxraji qaysi?",v:["Shafatayn","Vasat Lison","Tarafi Lison (til uchi—tish, qalin)","Halq"],t:2},
     {s:"ظ qanday talaffuz qilinadi?",v:["Tilni chiqarib jarangsiz ingichka","Tilni chiqarib jarangli qalin (Itboq)","Tomoqdan siqib","Til o'rta qismidan"],t:1},
     {s:"ط ning kuchli/zaif sifati?",v:["Raxv","Tavassut","Shadid","Lin"],t:2},
     {s:"ظ ning kuchli/zaif sifati?",v:["Shadid","Tavassut","Raxv","Qalqala"],t:2},
     {s:"ظ va ط ning farqi (shakl)?",v:["ط nuqtasiz, ظ nuqtali (ustida)","ط nuqtali, ظ nuqtasiz","Ikkisi ham nuqtasiz","Ikkisi ham nuqtali"],t:0},
     {s:"طَرِيق so'zining ma'nosi?",v:["Sport","Yo'l","Doktor","Urdi"],t:1},
     {s:"طَبِيب so'zining ma'nosi?",v:["Yo'l","Yer","Doktor","Ota"],t:2},
     {s:"ظَهَرَ so'zining ma'nosi?",v:["Ketdi","Ko'rindi","Keldi","Yotdi"],t:1},
     {s:"حَظٌّ so'zining ma'nosi?",v:["Ilm","Ish","Ulug'","Baxt"],t:3},
     {s:"ط va ظ ikkalasi ham qaysi umumiy sifatga ega?",v:["Safir","Itboq","G'unna","Qalqala"],t:1}
   ]},

  {id:9,harflar:["ع","غ"],nomlar:["Ayn","G'ayn"],mavzu:"Ayn va G'ayn",
   maxraj:[{h:"ع",mx:"Vasat Halq",iz:"Tomoqning o'rta qismidan siqib, jarangli."},{h:"غ",mx:"Aqsal Halq (jarangli)",iz:"Tomoqning pastki qismidan jarangli — o'zbek g' ga o'xshash."}],
   sifatlar:[{h:"ع",sf:["Tavassut","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"غ",sf:["Raxv","Jahr","Isti'lo","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ع",m:"ع",b:"عـ",o:"ـعـ",x:"ـع",iz:"Maxsus shakl — 4 holat"},{h:"غ",m:"غ",b:"غـ",o:"ـغـ",x:"ـغ",iz:"Uch nuqta (ع ga o'xshash)"}],
   harakatlar:[{h:"ع",f:"عَ",k:"عِ",d:"عُ",s:"عْ",of:"ʿa",ok:"ʿi",od:"ʿu",os:"ʿ"},{h:"غ",f:"غَ",k:"غِ",d:"غُ",s:"غْ",of:"ğa",ok:"ği",od:"ğu",os:"ğ"}],
   sozlar:[{ar:"عِلْم",oq:"ʿIlm",tr:"Ilm",h:"ع+ل+م"},{ar:"عَمَل",oq:"ʿAmal",tr:"Ish",h:"ع+م+ل"},{ar:"عَظِيم",oq:"ʿAẓiim",tr:"Ulug'",h:"ع+ظ+ي+م"},{ar:"غَيْب",oq:"Ğayb",tr:"G'oyib",h:"غ+ي+ب"},{ar:"غُرْفَة",oq:"Ğurfa",tr:"Xona",h:"غ+ر+ف"}],
   oqish:[{ar:"عَ عِ عُ عْ",iz:"Ayn (tomoqdan siqib)"},{ar:"غَ غِ غُ غْ",iz:"G'ayn (jarangli chuqur)"},{ar:"عِلْمٌ عَظِيمٌ",iz:"Buyuk ilm"},{ar:"عَمَلٌ كَامِلٌ",iz:"Mukammal ish"},{ar:"غَيْبٌ عَظِيمٌ",iz:"Ulug' g'ayb"}],
   yozish:[{t:"ع va غ farqini yozing",m:"ع(nuqtasiz)—غ(uch nuqta)"},{t:"ع ning 4 xil shaklini yozing",m:"عـ ـعـ ـع ع"},{t:"'Ğayb' yozing",m:"غَيْبٌ"}],
   uyvazifa:["ع va غ ni 5 martadan yozing","ع ni tomoqdan 20 marta ayting","'ʿIlm','ʿAmal','Ğayb' yod oling"],
   test:[
     {s:"ع harfining maxraji qaysi?",v:["Adnal Halq","Vasat Halq","Aqsal Halq","Jawf"],t:1},
     {s:"غ harfining maxraji qaysi?",v:["Adnal Halq","Vasat Halq","Aqsal Halq (jarangli)","Shafatayn"],t:2},
     {s:"ع ning kuchli/zaif sifati?",v:["Shadid","Raxv","Tavassut","Lin"],t:2},
     {s:"غ va ع yozuvdagi farqi?",v:["ع nuqtasiz, غ uch nuqta ustida","ع nuqtali, غ nuqtasiz","Ikkisi ham nuqtasiz","Maxraj bir xil"],t:0},
     {s:"غ ning ko'tarilish sifati?",v:["Istifol","Isti'lo","Infitoh","Itboq"],t:1},
     {s:"عِلْم so'zining ma'nosi?",v:["Ish","Ilm","Baxt","Ulug'"],t:1},
     {s:"عَمَل so'zining ma'nosi?",v:["Ilm","Baxt","Ish","Ko'rindi"],t:2},
     {s:"عَظِيم so'zining ma'nosi?",v:["Kichik","Eski","Ulug'","Yangi"],t:2},
     {s:"غَيْب so'zining ma'nosi?",v:["Fikr","Xona","G'oyib","Sevinch"],t:2},
     {s:"غُرْفَة so'zining ma'nosi?",v:["G'oyib","Xona","Sevinch","Yetdi"],t:1}
   ]},

  {id:10,harflar:["ف","ق"],nomlar:["Fa","Qof"],mavzu:"Fa va Qof",
   maxraj:[{h:"ف",mx:"Shafatayn (pastki lab—yuqori tish)",iz:"Pastki lab yuqori tishga tegadi, nafas erkin o'tadi."},{h:"ق",mx:"Aqsal Lison (til ildizi—eng orqa)",iz:"Tilning eng orqa qismi — o'zbek q dan chuqurroq."}],
   sifatlar:[{h:"ف",sf:["Raxv","Hams","Istifol","Infitoh","Izloq"]},{h:"ق",sf:["Shadid","Jahr","Isti'lo","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ف",m:"ف",b:"فـ",o:"ـفـ",x:"ـف",iz:"Bir nuqta ustida"},{h:"ق",m:"ق",b:"قـ",o:"ـقـ",x:"ـق",iz:"Ikki nuqta ustida"}],
   harakatlar:[{h:"ف",f:"فَ",k:"فِ",d:"فُ",s:"فْ",of:"fa",ok:"fi",od:"fu",os:"f"},{h:"ق",f:"قَ",k:"قِ",d:"قُ",s:"قْ",of:"qa",ok:"qi",od:"qu",os:"q"}],
   sozlar:[{ar:"فِكْر",oq:"Fikr",tr:"Fikr",h:"ف+ك+ر"},{ar:"فَرَح",oq:"Faraħ",tr:"Sevinch",h:"ف+ر+ح"},{ar:"قَلَم",oq:"Qalam",tr:"Qalam",h:"ق+ل+م"},{ar:"قَمَر",oq:"Qamar",tr:"Oy",h:"ق+م+ر"}],
   oqish:[{ar:"فَ فِ فُ فْ",iz:"Fa (lab-tish)"},{ar:"قَ قِ قُ قْ",iz:"Qof (chuqur q)"},{ar:"فِكْرٌ جَيِّدٌ",iz:"Yaxshi fikr"},{ar:"قَلَمٌ وَكِتَابٌ",iz:"Qalam va kitob"},{ar:"قَمَرٌ جَمِيلٌ",iz:"Go'zal oy"}],
   yozish:[{t:"ف va ق farqini yozing",m:"ف(1 nuqta)—ق(2 nuqta)"},{t:"'Fikr' yozing",m:"فِكْرٌ"},{t:"'Qalam' yozing",m:"قَلَمٌ"}],
   uyvazifa:["ف va ق ni 5 martadan yozing","فِرَّ مِنْ لُبّ yod oling (Izloq)","'Fikr','Faraħ','Qamar' yod oling"],
   test:[
     {s:"ف harfining maxraji qaysi?",v:["Lab-lab (shafatayn)","Pastki lab — yuqori tish","Vasat Halq","Tarafi Lison"],t:1},
     {s:"ق harfining maxraji qaysi?",v:["Vasat Lison","Aqsal Lison (til ildizi)","Tarafi Lison","Jawf"],t:1},
     {s:"ف ning maxsus sifati (oson talaffuz)?",v:["G'unna","Tafashi","Izloq","Safir"],t:2},
     {s:"ق ning Qalqala sifati bor — bu nima?",v:["Til titraydi","Harf sukun holida portlash bilan talaffuz qilinadi","Havo burundan chiqadi","Til cho'zilib chiqadi"],t:1},
     {s:"Isti'lo yodlash iborasi?",v:["فِرَّ مِنْ لُبّ","خُصَّ ضَغْطٍ قِظْ","لِنْ عُمَرْ","فَحَثَّهُ شَكَسَ"],t:1},
     {s:"فِكْر so'zining ma'nosi?",v:["Fikr","Xona","Sevinch","G'oyib"],t:0},
     {s:"فَرَح so'zining ma'nosi?",v:["Fikr","G'oyib","Xona","Sevinch"],t:3},
     {s:"قَلَم so'zining ma'nosi?",v:["Kitob","Oy","Qalam","Katta"],t:2},
     {s:"قَمَر so'zining ma'nosi?",v:["Quyosh","Oy","Yulduz","Osmon"],t:1},
     {s:"ق ning jarangli/jarangsiz sifati?",v:["Hams","Jahr","Safir","G'unna"],t:1}
   ]},

  {id:11,harflar:["ك","ل"],nomlar:["Kof","Lom"],mavzu:"Kof va Lam",
   maxraj:[{h:"ك",mx:"Vasat Lison (til o'rta-orqa)",iz:"Tilning o'rta-orqa qismi — q dan oldinroq."},{h:"ل",mx:"Tarafi Lison (til uchi yon—milk)",iz:"Til uchi yuqori milkka, havo yon tomoni orqali — Inhiraf."}],
   sifatlar:[{h:"ك",sf:["Shadid","Hams","Istifol","Infitoh","Ishmoq"]},{h:"ل",sf:["Tavassut","Jahr","Istifol","Infitoh","Inhiraf","Izloq"]}],
   shakllar:[{h:"ك",m:"ك",b:"كـ",o:"ـكـ",x:"ـك",iz:"Nuqtasiz, diagonal"},{h:"ل",m:"ل",b:"لـ",o:"ـلـ",x:"ـل",iz:"Uzun tik chiziq"}],
   harakatlar:[{h:"ك",f:"كَ",k:"كِ",d:"كُ",s:"كْ",of:"ka",ok:"ki",od:"ku",os:"k"},{h:"ل",f:"لَ",k:"لِ",d:"لُ",s:"لْ",of:"la",ok:"li",od:"lu",os:"l"}],
   sozlar:[{ar:"كِتَاب",oq:"Kitaab",tr:"Kitob",h:"ك+ت+ا+ب"},{ar:"كَبِير",oq:"Kabiir",tr:"Katta",h:"ك+ب+ي+ر"},{ar:"أَكَلَ",oq:"Akala",tr:"Yedi",h:"أ+ك+ل"},{ar:"لَيْل",oq:"Layl",tr:"Kecha",h:"ل+ي+ل"},{ar:"لَمَسَ",oq:"Lamasa",tr:"Tegdi",h:"ل+م+س"}],
   oqish:[{ar:"كَ كِ كُ كْ",iz:"Kof"},{ar:"لَ لِ لُ لْ",iz:"Lom 4 harakati"},{ar:"كِتَابٌ كَبِيرٌ",iz:"Katta kitob"},{ar:"أَكَلَ الرَّجُلُ",iz:"Erkak yedi"},{ar:"لَيْلٌ طَوِيلٌ",iz:"Uzun kecha"}],
   yozish:[{t:"ك va ل farqini yozing",m:"ك(diagonal)—ل(tik chiziq)"},{t:"'Kitaab' yozing",m:"كِتَابٌ"},{t:"Inhiraf sifatini tushuntir",m:"Havo yon tomoni orqali"}],
   uyvazifa:["ك va ل ni 5 martadan yozing","Inhiraf sifatini ko'rsating","'Kabiir','Akala','Layl' yod oling"],
   test:[
     {s:"ك harfining maxraji qaysi?",v:["Aqsal Lison","Vasat Lison (til o'rta-orqa)","Tarafi Lison","Halq"],t:1},
     {s:"ل harfining maxraji qaysi?",v:["Shafatayn","Vasat Lison","Tarafi Lison (til uchi—milk)","Halq"],t:2},
     {s:"ك ning jarangli/jarangsiz sifati?",v:["Jahr","Hams","Tafashi","Takrir"],t:1},
     {s:"Inhiraf sifati nimani anglatadi?",v:["Havo burundan chiqadi","Til yon tomoni uzayadi","Havo og'izdan yon tomoni orqali chiqadi","Til titraydi"],t:2},
     {s:"ك va ق ning maxraj farqi?",v:["ك va ق bir xil joyda","ق eng orqada, ك undan oldinroq","ك eng orqada, ق oldinroq","Ikkalasi halqda"],t:1},
     {s:"كِتَاب so'zining ma'nosi?",v:["Qalam","Oy","Katta","Kitob"],t:3},
     {s:"كَبِير so'zining ma'nosi?",v:["Kichik","Katta","Yangi","Eski"],t:1},
     {s:"أَكَلَ so'zining ma'nosi?",v:["Ichdi","Yedi","Ketdi","Keldi"],t:1},
     {s:"لَيْل so'zining ma'nosi?",v:["Kun","Kecha","Suv","So'z"],t:1},
     {s:"Inhiraf sifati qaysi harflarda bor?",v:["ز س","ل ر","ن م","و ي"],t:1}
   ]},

  {id:12,harflar:["م","ن"],nomlar:["Mim","Nun"],mavzu:"Mim va Nun",
   maxraj:[{h:"م",mx:"Shafatayn (lab-lab)",iz:"Ikki lab yopiladi, nafas burundan — G'unna."},{h:"ن",mx:"Tarafi Lison (til uchi—milk)",iz:"Jarangli. Sukunda G'unna sifati."}],
   sifatlar:[{h:"م",sf:["Shadid","Jahr","Istifol","Infitoh","G'unna","Izloq"]},{h:"ن",sf:["Tavassut","Jahr","Istifol","Infitoh","G'unna","Izloq"]}],
   shakllar:[{h:"م",m:"م",b:"مـ",o:"ـمـ",x:"ـم",iz:"Halqali shakl"},{h:"ن",m:"ن",b:"نـ",o:"ـنـ",x:"ـن",iz:"Bir nuqta ostida"}],
   harakatlar:[{h:"م",f:"مَ",k:"مِ",d:"مُ",s:"مْ",of:"ma",ok:"mi",od:"mu",os:"m"},{h:"ن",f:"نَ",k:"نِ",d:"نُ",s:"نْ",of:"na",ok:"ni",od:"nu",os:"n"}],
   sozlar:[{ar:"مَاء",oq:"Maau",tr:"Suv",h:"م+ا+ء"},{ar:"مُعَلِّم",oq:"Muʿallim",tr:"O'qituvchi",h:"م+ع+ل+م"},{ar:"كَلَام",oq:"Kalaam",tr:"So'z",h:"ك+ل+ا+م"},{ar:"نُور",oq:"Nuur",tr:"Nur",h:"ن+و+ر"},{ar:"نَهَر",oq:"Nahar",tr:"Daryo",h:"ن+ه+ر"}],
   oqish:[{ar:"مَ مِ مُ مْ",iz:"Mim 4 harakati"},{ar:"نَ نِ نُ نْ",iz:"Nun 4 harakati"},{ar:"مُعَلِّمٌ كَرِيمٌ",iz:"Saxovatli o'qituvchi"},{ar:"نُورٌ وَظَلَامٌ",iz:"Nur va zulmat"},{ar:"مَاءٌ وَنَهَرٌ",iz:"Suv va daryo"}],
   yozish:[{t:"م va ن G'unnasini taqqoslang",m:"Ikkisi ham burundan"},{t:"'Kalaam' yozing",m:"كَلَامٌ"},{t:"'Nuur' yozing",m:"نُورٌ"}],
   uyvazifa:["م va ن ni 5 martadan yozing","G'unna sifatini ko'rsating","'Maau','Muʿallim','Nahar' yod oling"],
   test:[
     {s:"م ning maxraji qaysi?",v:["Tarafi Lison","Vasat Halq","Shafatayn (lab-lab)","Jawf"],t:2},
     {s:"ن harfining maxraji qaysi?",v:["Shafatayn","Vasat Halq","Tarafi Lison (til uchi—milk)","Jawf"],t:2},
     {s:"م ning G'unna sifati qachon yaqqol ko'rinadi?",v:["Har doim","Fatha holida","Shadda va sukun (tanvin) holida","Kasra holida"],t:2},
     {s:"ن ning G'unna sifati qachon namoyon bo'ladi?",v:["Faqat fathada","Sukun va shadda holida (va tanvinda)","Faqat kasrada","Har doim emas"],t:1},
     {s:"G'unna sifatiga ega harflar?",v:["ل ر","ز س","ن م","و ي"],t:2},
     {s:"مَاء so'zining ma'nosi?",v:["Kecha","Suv","So'z","O'qituvchi"],t:1},
     {s:"مُعَلِّم so'zining ma'nosi?",v:["O'quvchi","Doktor","O'qituvchi","Muhandis"],t:2},
     {s:"كَلَام so'zining ma'nosi?",v:["Kecha","Suv","So'z (nutq)","O'qituvchi"],t:2},
     {s:"نُور so'zining ma'nosi?",v:["Zulmat","Nur","Daryo","Sovg'a"],t:1},
     {s:"نَهَر so'zining ma'nosi?",v:["Nur","Sovg'a","Daryo","Bu yerda"],t:2}
   ]},

  {id:13,harflar:["ه","و","ي"],nomlar:["Ha","Vov","Ya"],mavzu:"Ha, Wow va Ya",
   maxraj:[{h:"ه",mx:"Adnal Halq",iz:"Tomoqning og'izga eng yaqin qismidan yengil nafas — jarangsiz h."},{h:"و",mx:"Shafatayn + Jawf (mad)",iz:"Lab: ikki lab yumaloqlanadi. Mad: cho'ziq Ū."},{h:"ي",mx:"Vasat Lison + Jawf (mad)",iz:"Til o'rtasi. Mad: cho'ziq Ī."}],
   sifatlar:[{h:"ه",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]},{h:"و",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Lin (sukunda)"]},{h:"ي",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Lin (sukunda)"]}],
   shakllar:[{h:"ه",m:"ه",b:"هـ",o:"ـهـ",x:"ـه",iz:"Maxsus shakl o'rtada"},{h:"و",m:"و",b:"و",o:"ـو",x:"ـو",iz:"Faqat o'ngga"},{h:"ي",m:"ي",b:"يـ",o:"ـيـ",x:"ـي",iz:"Ikki nuqta ostida"}],
   harakatlar:[{h:"ه",f:"هَ",k:"هِ",d:"هُ",s:"هْ",of:"ha",ok:"hi",od:"hu",os:"h"},{h:"و",f:"وَ",k:"وِ",d:"وُ",s:"وْ",of:"wa",ok:"wi",od:"wu",os:"w/Ū"},{h:"ي",f:"يَ",k:"يِ",d:"يُ",s:"يْ",of:"ya",ok:"yi",od:"yu",os:"y/Ī"}],
   sozlar:[{ar:"هَدِيَّة",oq:"Hadiyya",tr:"Sovg'a",h:"ه+د+ي+ة"},{ar:"أَنَا",oq:"Anaa",tr:"Men",h:"أ+ن+ا"},{ar:"وَلَد",oq:"Walad",tr:"Bola",h:"و+ل+د"},{ar:"خَوْف",oq:"Xawf",tr:"Qo'rquv",h:"خ+و+ف"},{ar:"يَوْم",oq:"Yawm",tr:"Kun",h:"ي+و+م"},{ar:"يَدٌ",oq:"Yad",tr:"Qo'l",h:"ي+د"}],
   oqish:[{ar:"هَ هِ هُ هْ",iz:"Ha 4 harakati"},{ar:"وَ وِ وُ وْ",iz:"Vov 4 harakati"},{ar:"يَ يِ يُ يْ",iz:"Ya 4 harakati"},{ar:"هُنَا وَهُنَاكَ",iz:"Bu yerda va u yerda"},{ar:"يَوْمٌ جَمِيلٌ",iz:"Go'zal kun"}],
   yozish:[{t:"ه, و, ي shakllarini yozing",m:"هـ ـهـ ـه ه / و / يـ ـيـ ـي ي"},{t:"Lin sifatini tushuntir",m:"خَوْف—بَيْت (sukunda)"},{t:"'Hunaa' va 'Yawm' yozing",m:"هُنَا—يَوْمٌ"}],
   uyvazifa:["ه, و, ي ni 5 martadan yozing","Lin va Mad sifatlarini tushuntiring","'Hadiyya','Walad','Yad' yod oling"],
   test:[
     {s:"ه harfining maxraji qaysi?",v:["Vasat Halq","Adnal Halq","Aqsal Halq","Jawf"],t:1},
     {s:"Lin sifati qachon hosil bo'ladi?",v:["ل ر har doim","و ي sukun holida oldingi harfda fatha bo'lsa","ن م shadda holida","ز س fathada"],t:1},
     {s:"Mad Tabiiy (و bilan) qachon hosil bo'ladi?",v:["و dan oldin kasra bo'lsa","و dan oldin damma bo'lsa","و dan oldin fatha bo'lsa","و har doim mad"],t:1},
     {s:"Mad Tabiiy (ي bilan) qachon hosil bo'ladi?",v:["ي dan oldin fatha bo'lsa","ي dan oldin damma bo'lsa","ي dan oldin kasra bo'lsa","ي har doim mad"],t:2},
     {s:"ه va ح ning asosiy farqi?",v:["Maxraj bir xil","ه Adnal (yengil), ح Vasat (chuqur)","Ikkisi ham jarangli","Sifat bir xil"],t:1},
     {s:"هُنَا so'zining ma'nosi?",v:["U yerda","Men","Bu yerda","Biz"],t:2},
     {s:"أَنَا so'zining ma'nosi?",v:["Sen","U","Biz","Men"],t:3},
     {s:"وَلَد so'zining ma'nosi?",v:["Qiz","Kun","Qo'l","Bola"],t:3},
     {s:"يَوْم so'zining ma'nosi?",v:["Kecha","Oy","Kun","Yil"],t:2},
     {s:"يَدٌ so'zining ma'nosi?",v:["Oyoq","Bosh","Qo'l","Ko'z"],t:2}
   ]},
];
