import type { AmalBob } from "./types";

export const AMALIY: AmalBob[] = [
  {id:1,harflar:["أ","ب"],nomlar:["Hamza","Ba"],
   maxraj:[{h:"أ",mx:"Adnal Halq",iz:"Tomoqning eng yuqori qismi. Havo to'liq to'xtatiladi — glottal stop."},{h:"ب",mx:"Shafatayn (lab-lab)",iz:"Ikki lab bir-biriga yopiladi, portlatib chiqariladi."}],
   sifatlar:[{h:"أ",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"ب",sf:["Shadid","Jahr","Istifol","Infitoh","Izloq"]}],
   shakllar:[{h:"أ",m:"أ",b:"أ",o:"ـأ",x:"ـأ",iz:"Alif faqat oldingi harfga ulanadi"},{h:"ب",m:"ب",b:"بـ",o:"ـبـ",x:"ـب",iz:"Ba to'rt holatda bog'lanadi"}],
   harakatlar:[{h:"ب",f:"بَ",k:"بِ",d:"بُ",s:"بْ",of:"ba",ok:"bi",od:"bu",os:"b"},{h:"أ",f:"أَ",k:"أِ",d:"أُ",s:"أْ",of:"a",ok:"i",od:"u",os:"hamza"}],
   sozlar:[{ar:"أَب",oq:"Ab",tr:"Ota",h:"أ+ب"},{ar:"بَاب",oq:"Baab",tr:"Eshik",h:"ب+ا+ب"},{ar:"أَبُو",oq:"Abuu",tr:"Otasi",h:"أ+ب+و"},{ar:"بَر",oq:"Bar",tr:"Quruqlik",h:"ب+ر"},{ar:"أَكْبَر",oq:"Akbar",tr:"Kattaroq",h:"أ+ك+ب+ر"}],
   oqish:[{ar:"بَ بِ بُ بْ",iz:"Ba ning 4 harakati"},{ar:"أَبٌ",iz:"Ab-un — ota"},{ar:"بَابٌ",iz:"Baab — eshik"},{ar:"أَبٌ كَبِيرٌ",iz:"Katta ota"},{ar:"بَرِيءٌ",iz:"Beg'ubor"}],
   yozish:[{t:"Ba harfining 4 xil shaklini yozing",m:"بـ ـبـ ـب ب"},{t:"'Baab' so'zini harakat bilan yozing",m:"بَابٌ"},{t:"Alif+Ba birikmasini yozing",m:"أَب"}],
   uyvazifa:["أ va ب harflarini 5 martadan yozing","Ba ning 4 harakatini aytib bering","'Baab' va 'Ab' ni 10 marta o'qing"],
   test:[{s:"ب harfining maxraji?",v:["Halq","Lison","Shafatayn","Jawf"],t:2},{s:"أ harfining sifati?",v:["Raxv","Shadid","G'unna","Lin"],t:1},{s:"بَ qanday o'qiladi?",v:["bi","bu","ba","b"],t:2},{s:"بَابٌ ma'nosi?",v:["Ota","Eshik","Kitob","Bola"],t:1},{s:"ب o'rtasidagi shakli?",v:["بـ","ـبـ","ـب","ب"],t:1}]},
  {id:2,harflar:["ت","ث"],nomlar:["Ta","Sa"],
   maxraj:[{h:"ت",mx:"Tarafi Lison (til uchi—tish)",iz:"Til uchining yuqori tish orqasiga teginishi."},{h:"ث",mx:"Tarafi Lison (tish oraliq)",iz:"Til uchi ikki tish orasiga chiqariladi — 'think' dagi 'th'."}],
   sifatlar:[{h:"ت",sf:["Shadid","Hams","Istifol","Infitoh","Izloq"]},{h:"ث",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ت",m:"ت",b:"تـ",o:"ـتـ",x:"ـت",iz:"Ikki nuqta ustida"},{h:"ث",m:"ث",b:"ثـ",o:"ـثـ",x:"ـث",iz:"Uch nuqta ustida"}],
   harakatlar:[{h:"ت",f:"تَ",k:"تِ",d:"تُ",s:"تْ",of:"ta",ok:"ti",od:"tu",os:"t"},{h:"ث",f:"ثَ",k:"ثِ",d:"ثُ",s:"ثْ",of:"θa",ok:"θi",od:"θu",os:"θ"}],
   sozlar:[{ar:"تَمْر",oq:"Tamr",tr:"Xurmo",h:"ت+م+ر"},{ar:"ثَوْب",oq:"θawb",tr:"Kiyim",h:"ث+و+ب"},{ar:"بَيْت",oq:"Bayt",tr:"Uy",h:"ب+ي+ت"},{ar:"ثَلَاثَة",oq:"θalaθa",tr:"Uch",h:"ث+ل+ا+ث"},{ar:"تَابَ",oq:"Taaba",tr:"Tavba qildi",h:"ت+ا+ب"}],
   oqish:[{ar:"تَ تِ تُ تْ",iz:"Ta ning 4 harakati"},{ar:"ثَ ثِ ثُ ثْ",iz:"Sa (tilni chiqarib)"},{ar:"بَيْتٌ",iz:"Uy"},{ar:"ثَلَاثَةٌ",iz:"Uch"},{ar:"تَابَ وَأَنَابَ",iz:"Tavba qildi va qaytdi"}],
   yozish:[{t:"ت va ث farqini yozing (nuqtalar)",m:"ت(2) — ث(3)"},{t:"'Tamr' yozing",m:"تَمْرٌ"},{t:"'θawb' yozing",m:"ثَوْبٌ"}],
   uyvazifa:["ت va ث ni 5 martadan yozing","ث ni tilni chiqarib 20 marta ayting","'Bayt','Tamr','θawb' yod oling"],
   test:[{s:"ث qanday talaffuz?",v:["Oddiy s","Til chiqarib jarangsiz","Qalin s","Tomoqdan"],t:1},{s:"ت maxraji?",v:["Lab","Tomoq","Til uchi—tish","Burun"],t:2},{s:"بَيْتٌ ma'nosi?",v:["Kitob","Eshik","Uy","Bola"],t:2},{s:"ث sifati?",v:["Jahr","Shadid","Hams","G'unna"],t:2},{s:"ثَلَاثَة nima?",v:["Ikki","Uch","To'rt","Besh"],t:1}]},
  {id:3,harflar:["ج","ح"],nomlar:["Jim","Ha"],
   maxraj:[{h:"ج",mx:"Vasat Lison",iz:"Tilning o'rta qismi tanglay tomon ko'tariladi."},{h:"ح",mx:"Vasat Halq",iz:"Tomoqning o'rta qismidan chuqur nafas — jarangsiz."}],
   sifatlar:[{h:"ج",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"ح",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ج",m:"ج",b:"جـ",o:"ـجـ",x:"ـج",iz:"Bir nuqta pastida"},{h:"ح",m:"ح",b:"حـ",o:"ـحـ",x:"ـح",iz:"Nuqtasiz"}],
   harakatlar:[{h:"ج",f:"جَ",k:"جِ",d:"جُ",s:"جْ",of:"ja",ok:"ji",od:"ju",os:"j"},{h:"ح",f:"حَ",k:"حِ",d:"حُ",s:"حْ",of:"ħa",ok:"ħi",od:"ħu",os:"ħ"}],
   sozlar:[{ar:"جَمَل",oq:"Jamal",tr:"Tuya",h:"ج+م+ل"},{ar:"حَجَر",oq:"Ħajar",tr:"Tosh",h:"ح+ج+ر"},{ar:"جَاءَ",oq:"Jaa'a",tr:"Keldi",h:"ج+ا+ء"},{ar:"حُبٌّ",oq:"Ħubb",tr:"Sevgi",h:"ح+ب"},{ar:"أَجَل",oq:"Ajal",tr:"Ha",h:"أ+ج+ل"}],
   oqish:[{ar:"جَ جِ جُ جْ",iz:"Jim 4 harakati"},{ar:"حَ حِ حُ حْ",iz:"Ha (tomoqdan)"},{ar:"جَمَلٌ كَبِيرٌ",iz:"Katta tuya"},{ar:"حُبُّ الأَبِ",iz:"Ota sevgisi"},{ar:"جَاءَ الرَّجُلُ",iz:"Erkak keldi"}],
   yozish:[{t:"ج va ح farqini yozing",m:"ج (nuqtali) — ح (nuqtasiz)"},{t:"'Jamal' yozing",m:"جَمَلٌ"},{t:"'Ħubb' yozing",m:"حُبٌّ"}],
   uyvazifa:["ج va ح ni 5 martadan yozing","ح ni tomoqdan 20 marta ayting","'Jamal','Ħajar' yod oling"],
   test:[{s:"ح maxraji?",v:["Jawf","Adnal Halq","Vasat Halq","Aqsal"],t:2},{s:"ج sifati?",v:["Hams","Jahr","G'unna","Lin"],t:1},{s:"حُبٌّ ma'nosi?",v:["Tosh","Tuya","Sevgi","Keldi"],t:2},{s:"ج va ح farqi?",v:["Shakl","Nuqta","Maxraj","Hammasi"],t:3},{s:"جَمَلٌ ma'nosi?",v:["Tosh","Tuya","Sevgi","Eshik"],t:1}]},
  {id:4,harflar:["خ","د"],nomlar:["Xo","Dal"],
   maxraj:[{h:"خ",mx:"Aqsal Halq",iz:"Tomoqning pastki qismidan jarangsiz — o'zbek 'x' chuqurroq."},{h:"د",mx:"Tarafi Lison (til uchi—tish)",iz:"Portlovchi jarangli tovush."}],
   sifatlar:[{h:"خ",sf:["Raxv","Hams","Isti'lo","Infitoh","Ishmoq"]},{h:"د",sf:["Shadid","Jahr","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"خ",m:"خ",b:"خـ",o:"ـخـ",x:"ـخ",iz:"Uch nuqta (ح ga o'xshash)"},{h:"د",m:"د",b:"د",o:"ـد",x:"ـد",iz:"Faqat o'ng tomonga"}],
   harakatlar:[{h:"خ",f:"خَ",k:"خِ",d:"خُ",s:"خْ",of:"xa",ok:"xi",od:"xu",os:"x"},{h:"د",f:"دَ",k:"دِ",d:"دُ",s:"دْ",of:"da",ok:"di",od:"du",os:"d"}],
   sozlar:[{ar:"خُبْز",oq:"Xubz",tr:"Non",h:"خ+ب+ز"},{ar:"دَرْس",oq:"Dars",tr:"Dars",h:"د+ر+س"},{ar:"خَيْر",oq:"Xayr",tr:"Yaxshilik",h:"خ+ي+ر"},{ar:"دَار",oq:"Daar",tr:"Uy",h:"د+ا+ر"},{ar:"أَخٌ",oq:"Ax",tr:"Aka",h:"أ+خ"}],
   oqish:[{ar:"خَ خِ خُ خْ",iz:"Xo 4 harakati"},{ar:"دَ دِ دُ دْ",iz:"Dal 4 harakati"},{ar:"خُبْزٌ وَدَرْسٌ",iz:"Non va dars"},{ar:"دَارُ الأَخِ",iz:"Akaning uyi"},{ar:"خَيْرٌ كَثِيرٌ",iz:"Ko'p yaxshilik"}],
   yozish:[{t:"خ ni 4 xil shaklda yozing",m:"خـ ـخـ ـخ خ"},{t:"'Xubz' va 'Dars' yozing",m:"خُبْزٌ — دَرْسٌ"},{t:"د faqat o'ngga: دَار",m:"دَارٌ"}],
   uyvazifa:["خ va د ni 5 martadan yozing","خ ni ح dan farqlang (nuqta)","'Xayr','Dars','Xubz' yod oling"],
   test:[{s:"خ maxraji?",v:["Adnal","Vasat","Aqsal Halq","Jawf"],t:2},{s:"د faqat qaysi tomonga?",v:["Ikki","O'ng","Ulanmaydi","Chap"],t:1},{s:"خُبْز ma'nosi?",v:["Dars","Non","Aka","Uy"],t:1},{s:"خ sifati?",v:["Jahr","Shadid","Hams","G'unna"],t:2},{s:"دَرْس ma'nosi?",v:["Uy","Non","Dars","Xayr"],t:2}]},
  {id:5,harflar:["ذ","ر"],nomlar:["Zal","Ra"],
   maxraj:[{h:"ذ",mx:"Tarafi Lison (tish oraliq, jarangli)",iz:"Til uchi tishlar orasiga — 'this' dagi 'dh'."},{h:"ر",mx:"Tarafi Lison (til uchi—milk)",iz:"Til uchi yuqori milkka tegib, titrab chiqadi — Takrir."}],
   sifatlar:[{h:"ذ",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq"]},{h:"ر",sf:["Tavassut","Jahr","Istifol/Isti'lo","Infitoh","Takrir","Inhiraf","Izloq"]}],
   shakllar:[{h:"ذ",m:"ذ",b:"ذ",o:"ـذ",x:"ـذ",iz:"Faqat o'ngga — bir nuqta"},{h:"ر",m:"ر",b:"ر",o:"ـر",x:"ـر",iz:"Faqat o'ngga — nuqtasiz"}],
   harakatlar:[{h:"ذ",f:"ذَ",k:"ذِ",d:"ذُ",s:"ذْ",of:"ða",ok:"ði",od:"ðu",os:"ð"},{h:"ر",f:"رَ",k:"رِ",d:"رُ",s:"رْ",of:"ra",ok:"ri",od:"ru",os:"r"}],
   sozlar:[{ar:"ذَهَبَ",oq:"Zahaba",tr:"Ketdi",h:"ذ+ه+ب"},{ar:"رَجُل",oq:"Rajul",tr:"Erkak",h:"ر+ج+ل"},{ar:"هَذَا",oq:"Haazaa",tr:"Bu",h:"ه+ذ+ا"},{ar:"دَرَسَ",oq:"Darasa",tr:"O'qidi",h:"د+ر+س"},{ar:"ذِكْر",oq:"Zikr",tr:"Zikr",h:"ذ+ك+ر"}],
   oqish:[{ar:"ذَ ذِ ذُ ذْ",iz:"Zal (tilni chiqarib jarangli)"},{ar:"رَ رِ رُ رْ",iz:"Ra (titrab)"},{ar:"ذَهَبَ الرَّجُلُ",iz:"Erkak ketdi"},{ar:"هَذَا كِتَابٌ",iz:"Bu kitob"},{ar:"دَرَسَ الْوَلَدُ",iz:"Bola o'qidi"}],
   yozish:[{t:"ذ va ز farqini yozing",m:"ذ(til chiqarib)—ز(oddiy)"},{t:"'Zaahaba' yozing",m:"ذَهَبَ"},{t:"Ra — Takrir sifatini tushuntir",m:"ر titradi"}],
   uyvazifa:["ذ va ر ni yozing","ذ va ز farqini ayting","'Rajul','Haazaa','Zikr' yod oling"],
   test:[{s:"ذ qanday talaffuz?",v:["Til chiqarib jarangsiz","Til chiqarib jarangli","Oddiy z","Tomoqdan"],t:1},{s:"ر maxsus sifati?",v:["Safir","Takrir","Tafashi","G'unna"],t:1},{s:"هَذَا ma'nosi?",v:["U","Bu","Men","Siz"],t:1},{s:"ذ va ز farqi?",v:["Maxraj","ذ til chiqarib","Sifat","Hammasi"],t:1},{s:"ذَهَبَ ma'nosi?",v:["Keldi","Ketdi","O'tirdi","Yozdi"],t:1}]},
  {id:6,harflar:["ز","س"],nomlar:["Zayn","Sin"],
   maxraj:[{h:"ز",mx:"Tarafi Lison (tish izi, jarangli)",iz:"Jarangli z, Safir sifati."},{h:"س",mx:"Tarafi Lison (tish izi, jarangsiz)",iz:"Jarangsiz s, Safir sifati."}],
   sifatlar:[{h:"ز",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Safir"]},{h:"س",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq","Safir"]}],
   shakllar:[{h:"ز",m:"ز",b:"ز",o:"ـز",x:"ـز",iz:"Faqat o'ngga — bir nuqta"},{h:"س",m:"س",b:"سـ",o:"ـسـ",x:"ـس",iz:"To'rt tomonga — nuqtasiz"}],
   harakatlar:[{h:"ز",f:"زَ",k:"زِ",d:"زُ",s:"زْ",of:"za",ok:"zi",od:"zu",os:"z"},{h:"س",f:"سَ",k:"سِ",d:"سُ",s:"سْ",of:"sa",ok:"si",od:"su",os:"s"}],
   sozlar:[{ar:"زَيْد",oq:"Zayd",tr:"(Ism)",h:"ز+ي+د"},{ar:"سَمَاء",oq:"Samaau",tr:"Osmon",h:"س+م+ا+ء"},{ar:"بَازَار",oq:"Baazaar",tr:"Bozor",h:"ب+ا+ز+ا+ر"},{ar:"دَرَسَ",oq:"Darasa",tr:"O'qidi",h:"د+ر+س"},{ar:"زَرَعَ",oq:"Zaraa",tr:"Ekdi",h:"ز+ر+ع"}],
   oqish:[{ar:"زَ زِ زُ زْ",iz:"Zayn 4 harakati"},{ar:"سَ سِ سُ سْ",iz:"Sin 4 harakati"},{ar:"سَمَاءٌ صَافِيَةٌ",iz:"Tiniq osmon"},{ar:"زَرَعَ الأَبُ",iz:"Ota ekdi"},{ar:"سَمِعَ صَبَرَ زَيْدٌ",iz:"Safir yodlash iborasi"}],
   yozish:[{t:"ز va س farqini yozing",m:"ز(nuqtali)—س(nuqtasiz)"},{t:"Safir: ز س ص",m:"Hushtak ovozi"},{t:"'Samaau' yozing",m:"سَمَاءٌ"}],
   uyvazifa:["Safir sifatini ko'rsating","ز،س،ص ni taqqoslang","'Zayd','Samaau','Darasa' yod oling"],
   test:[{s:"Safir harflari?",v:["ل ر","ز س ص","ن م","و ي"],t:1},{s:"ز va س farqi?",v:["Maxraj","ز jarangli, س jarangsiz","Sifat","Shakl"],t:1},{s:"سَمَاء ma'nosi?",v:["Osmon","Bozor","Ism","Ekdi"],t:0},{s:"ز dan tashqari sifat?",v:["Hams","Jahr","G'unna","Lin"],t:1},{s:"دَرَسَ ma'nosi?",v:["Ketdi","Keldi","O'qidi","Yedi"],t:2}]},
  {id:7,harflar:["ش","ص"],nomlar:["Shin","Sod"],
   maxraj:[{h:"ش",mx:"Vasat Lison",iz:"Havo keng yoyiladi — Tafashi sifati."},{h:"ص",mx:"Tarafi Lison (qalin)",iz:"Sin kabi joyda, lekin til orqasi ko'tarilgan — qalin s."}],
   sifatlar:[{h:"ش",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq","Tafashi"]},{h:"ص",sf:["Raxv","Hams","Isti'lo","Itboq","Ishmoq","Safir"]}],
   shakllar:[{h:"ش",m:"ش",b:"شـ",o:"ـشـ",x:"ـش",iz:"Uch nuqta (س ga o'xshash)"},{h:"ص",m:"ص",b:"صـ",o:"ـصـ",x:"ـص",iz:"Nuqtasiz, yumaloq"}],
   harakatlar:[{h:"ش",f:"شَ",k:"شِ",d:"شُ",s:"شْ",of:"sha",ok:"shi",od:"shu",os:"sh"},{h:"ص",f:"صَ",k:"صِ",d:"صُ",s:"صْ",of:"ṣa",ok:"ṣi",od:"ṣu",os:"ṣ"}],
   sozlar:[{ar:"شَمْس",oq:"Shams",tr:"Quyosh",h:"ش+م+س"},{ar:"صَبَرَ",oq:"Ṣabara",tr:"Sabr qildi",h:"ص+ب+ر"},{ar:"شَجَر",oq:"Shajar",tr:"Daraxt",h:"ش+ج+ر"},{ar:"صَدِيق",oq:"Ṣadiiq",tr:"Do'st",h:"ص+د+ي+ق"},{ar:"أَشْجَار",oq:"Ashjaar",tr:"Daraxtlar",h:"أ+ش+ج+ا+ر"}],
   oqish:[{ar:"شَ شِ شُ شْ",iz:"Shin 4 harakati"},{ar:"صَ صِ صُ صْ",iz:"Sod (qalin s!)"},{ar:"شَمْسٌ مُشْرِقَةٌ",iz:"Yorqin quyosh"},{ar:"صَبْرٌ جَمِيلٌ",iz:"Go'zal sabr"},{ar:"سَمِعَ صَبَرَ زَيْدٌ",iz:"Safir iborasi"}],
   yozish:[{t:"س va ش farqini yozing",m:"س(nuqtasiz)—ش(3 nuqta)"},{t:"س va ص farqini tushuntir",m:"س ingichka—ص qalin"},{t:"'Shams' va 'Ṣadiiq' yozing",m:"شَمْسٌ—صَدِيقٌ"}],
   uyvazifa:["Tafashi sifatini ko'rsating","'Shams','Ṣabara','Shajar' yod oling","س va ص farqini amalda ko'rsating"],
   test:[{s:"Tafashi qaysi harfda?",v:["س","ز","ش","ص"],t:2},{s:"ص sifatlari soni?",v:["3","4","5","6"],t:3},{s:"شَمْس ma'nosi?",v:["Oy","Quyosh","Yulduz","Osmon"],t:1},{s:"ص va س farqi?",v:["Maxraj","ص qalin (Isti'lo)","Shakl","Sifat"],t:1},{s:"صَدِيق ma'nosi?",v:["Dushman","Do'st","Ota","Aka"],t:1}]},
  {id:8,harflar:["ض","ط"],nomlar:["Dod","To"],
   maxraj:[{h:"ض",mx:"Hafat Lison (til yon tomoni)",iz:"Tilning yon tomoni milkka — Istitoyla sifati."},{h:"ط",mx:"Tarafi Lison (til uchi—tish, qalin)",iz:"Qalin t — til orqasi ko'tarilgan."}],
   sifatlar:[{h:"ض",sf:["Raxv","Jahr","Isti'lo","Itboq","Ishmoq","Istitoyla"]},{h:"ط",sf:["Shadid","Jahr","Isti'lo","Itboq","Ishmoq"]}],
   shakllar:[{h:"ض",m:"ض",b:"ضـ",o:"ـضـ",x:"ـض",iz:"Nuqtali (ص ga o'xshash)"},{h:"ط",m:"ط",b:"طـ",o:"ـطـ",x:"ـط",iz:"Nuqtasiz, halqali"}],
   harakatlar:[{h:"ض",f:"ضَ",k:"ضِ",d:"ضُ",s:"ضْ",of:"ḍa",ok:"ḍi",od:"ḍu",os:"ḍ"},{h:"ط",f:"طَ",k:"طِ",d:"طُ",s:"طْ",of:"ṭa",ok:"ṭi",od:"ṭu",os:"ṭ"}],
   sozlar:[{ar:"رَمَضَان",oq:"Ramaḍaan",tr:"Ramazon",h:"ر+م+ض+ا+ن"},{ar:"طَرِيق",oq:"Ṭariiq",tr:"Yo'l",h:"ط+ر+ي+ق"},{ar:"ضَرَبَ",oq:"Ḍaraba",tr:"Urdi",h:"ض+ر+ب"},{ar:"طَبِيب",oq:"Ṭabiib",tr:"Doktor",h:"ط+ب+ي+ب"},{ar:"أَرْض",oq:"Arḍ",tr:"Yer",h:"أ+ر+ض"}],
   oqish:[{ar:"ضَ ضِ ضُ ضْ",iz:"Dod 4 harakati"},{ar:"طَ طِ طُ طْ",iz:"To (qalin t)"},{ar:"طَرِيقٌ طَوِيلٌ",iz:"Uzun yo'l"},{ar:"أَرْضٌ وَسَمَاءٌ",iz:"Yer va osmon"},{ar:"طَبِيبٌ مَاهِرٌ",iz:"Mohir doktor"}],
   yozish:[{t:"ض va ص farqini yozing",m:"ص(nuqtasiz)—ض(nuqtali)"},{t:"Istitoyla sifatini tushuntir",m:"Til yon tomoni uzayib chiqadi"},{t:"'Ramaḍaan' va 'Ṭariiq' yozing",m:"رَمَضَانٌ—طَرِيقٌ"}],
   uyvazifa:["Itboq sifatini ko'rsating","'Ramaḍaan','Ṭabiib','Arḍ' yod oling","Istitoyla sifatini namoyish qiling"],
   test:[{s:"Istitoyla qaysi harfda?",v:["ط","ص","ض","ظ"],t:2},{s:"Itboq harflari?",v:["ز س ص","ص ض ط ظ","ب ر ف ل","ن م"],t:1},{s:"أَرْض ma'nosi?",v:["Osmon","Yo'l","Yer","Doktor"],t:2},{s:"ط sifati?",v:["Raxv","Shadid","G'unna","Safir"],t:1},{s:"رَمَضَان nima?",v:["Kunlar","Oylar","Oy nomi","Yil"],t:2}]},
  {id:9,harflar:["ظ","ع"],nomlar:["Zo","Ayn"],
   maxraj:[{h:"ظ",mx:"Tarafi Lison (tish oraliq, qalin, jarangli)",iz:"Tilni chiqarib, til orqasi ko'tarilgan — qalin jarangli."},{h:"ع",mx:"Vasat Halq",iz:"Tomoqning o'rta qismidan siqib, jarangli."}],
   sifatlar:[{h:"ظ",sf:["Raxv","Jahr","Isti'lo","Itboq","Ishmoq"]},{h:"ع",sf:["Tavassut","Jahr","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ظ",m:"ظ",b:"ظـ",o:"ـظـ",x:"ـظ",iz:"Nuqta ustida (ط ga o'xshash)"},{h:"ع",m:"ع",b:"عـ",o:"ـعـ",x:"ـع",iz:"Maxsus shakl — 4 holat"}],
   harakatlar:[{h:"ظ",f:"ظَ",k:"ظِ",d:"ظُ",s:"ظْ",of:"ẓa",ok:"ẓi",od:"ẓu",os:"ẓ"},{h:"ع",f:"عَ",k:"عِ",d:"عُ",s:"عْ",of:"ʿa",ok:"ʿi",od:"ʿu",os:"ʿ"}],
   sozlar:[{ar:"ظَهَرَ",oq:"Ẓahara",tr:"Ko'rindi",h:"ظ+ه+ر"},{ar:"عِلْم",oq:"ʿIlm",tr:"Ilm",h:"ع+ل+م"},{ar:"عَظِيم",oq:"ʿAẓiim",tr:"Ulug'",h:"ع+ظ+ي+م"},{ar:"عَمَل",oq:"ʿAmal",tr:"Ish",h:"ع+م+ل"},{ar:"حَظٌّ",oq:"Ħaẓẓ",tr:"Baxt",h:"ح+ظ"}],
   oqish:[{ar:"ظَ ظِ ظُ ظْ",iz:"Zo (tilni chiqarib qalin)"},{ar:"عَ عِ عُ عْ",iz:"Ayn (tomoqdan siqib)"},{ar:"عِلْمٌ عَظِيمٌ",iz:"Buyuk ilm"},{ar:"ظَهَرَ الْحَقُّ",iz:"Haq namoyon bo'ldi"},{ar:"عَمَلٌ صَالِحٌ",iz:"Yaxshi ish"}],
   yozish:[{t:"ظ va ذ farqini yozing",m:"ذ ingichka—ظ qalin (Itboq)"},{t:"ع ning 4 xil shaklini yozing",m:"عـ ـعـ ـع ع"},{t:"'ʿIlm' va 'ʿAẓiim' yozing",m:"عِلْمٌ—عَظِيمٌ"}],
   uyvazifa:["ظ va ذ farqini tushuntiring","ع ni tomoqdan 20 marta ayting","'ʿIlm','ʿAẓiim','ʿAmal' yod oling"],
   test:[{s:"ع maxraji?",v:["Adnal","Vasat Halq","Aqsal","Jawf"],t:1},{s:"ظ sifati (ذ dan farqi)?",v:["Hams","Raxv","Itboq (qalin)","Jahr"],t:2},{s:"عِلْم ma'nosi?",v:["Ish","Ilm","Baxt","Ulug'"],t:1},{s:"عَظِيم ma'nosi?",v:["Kichik","Ulug'","Eski","Yangi"],t:1},{s:"ظ va ط farqi?",v:["Maxraj","ط Shadid, ظ Raxv","Shakl","Sifat"],t:1}]},
  {id:10,harflar:["غ","ف"],nomlar:["G'ayn","Fa"],
   maxraj:[{h:"غ",mx:"Aqsal Halq (jarangli)",iz:"Tomoqning pastki qismidan jarangli — o'zbek g' ga o'xshash."},{h:"ف",mx:"Shafatayn (pastki lab—yuqori tish)",iz:"Pastki lab yuqori tishga tegadi, nafas erkin o'tadi."}],
   sifatlar:[{h:"غ",sf:["Raxv","Jahr","Isti'lo","Infitoh","Ishmoq"]},{h:"ف",sf:["Raxv","Hams","Istifol","Infitoh","Izloq"]}],
   shakllar:[{h:"غ",m:"غ",b:"غـ",o:"ـغـ",x:"ـغ",iz:"Uch nuqta (ع ga o'xshash)"},{h:"ف",m:"ف",b:"فـ",o:"ـفـ",x:"ـف",iz:"Bir nuqta ustida"}],
   harakatlar:[{h:"غ",f:"غَ",k:"غِ",d:"غُ",s:"غْ",of:"ğa",ok:"ği",od:"ğu",os:"ğ"},{h:"ف",f:"فَ",k:"فِ",d:"فُ",s:"فْ",of:"fa",ok:"fi",od:"fu",os:"f"}],
   sozlar:[{ar:"غَيْب",oq:"Ğayb",tr:"G'oyib",h:"غ+ي+ب"},{ar:"فِكْر",oq:"Fikr",tr:"Fikr",h:"ف+ك+ر"},{ar:"غُرْفَة",oq:"Ğurfa",tr:"Xona",h:"غ+ر+ف"},{ar:"فَرَح",oq:"Faraħ",tr:"Sevinch",h:"ف+ر+ح"},{ar:"بَلَغَ",oq:"Balaği",tr:"Yetdi",h:"ب+ل+غ"}],
   oqish:[{ar:"غَ غِ غُ غْ",iz:"G'ayn (jarangli chuqur)"},{ar:"فَ فِ فُ فْ",iz:"Fa (lab-tish)"},{ar:"فِكْرٌ جَيِّدٌ",iz:"Yaxshi fikr"},{ar:"غَيْبٌ عَظِيمٌ",iz:"Ulug' g'ayb"},{ar:"غُرْفَةٌ كَبِيرَةٌ",iz:"Katta xona"}],
   yozish:[{t:"غ va خ farqini yozing",m:"غ(Jahr)—خ(Hams)"},{t:"'Fikr' va 'Ğayb' yozing",m:"فِكْرٌ—غَيْبٌ"},{t:"غ ni ع dan farqlang",m:"ع(Vasat)—غ(Aqsal)"}],
   uyvazifa:["غ va خ farqini ko'rsating","فِرَّ مِنْ لُبّ yod oling (Izloq)","'Ğayb','Fikr','Faraħ' yod oling"],
   test:[{s:"غ va خ farqi?",v:["Maxraj","غ Jahr, خ Hams","Shakl","Sifat soni"],t:1},{s:"ف maxraji?",v:["Lab-lab","Pastki lab—yuqori tish","Tomoq","Burun"],t:1},{s:"غَيْب ma'nosi?",v:["Fikr","Xona","G'oyib","Sevinch"],t:2},{s:"Izloq harflari?",v:["ز س ص","ص ض ط ظ","ب ر ف ل م ن","ن م"],t:2},{s:"فِكْر ma'nosi?",v:["Fikr","Xona","Sevinch","Uy"],t:0}]},
  {id:11,harflar:["ق","ك"],nomlar:["Qof","Kof"],
   maxraj:[{h:"ق",mx:"Aqsal Lison (til ildizi—eng orqa)",iz:"Tilning eng orqa qismi — o'zbek q dan chuqurroq."},{h:"ك",mx:"Vasat Lison (til o'rta-orqa)",iz:"Tilning o'rta-orqa qismi — q dan oldinroq."}],
   sifatlar:[{h:"ق",sf:["Shadid","Jahr","Isti'lo","Infitoh","Ishmoq"]},{h:"ك",sf:["Shadid","Hams","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ق",m:"ق",b:"قـ",o:"ـقـ",x:"ـق",iz:"Ikki nuqta ustida"},{h:"ك",m:"ك",b:"كـ",o:"ـكـ",x:"ـك",iz:"Nuqtasiz, diagonal"}],
   harakatlar:[{h:"ق",f:"قَ",k:"قِ",d:"قُ",s:"قْ",of:"qa",ok:"qi",od:"qu",os:"q"},{h:"ك",f:"كَ",k:"كِ",d:"كُ",s:"كْ",of:"ka",ok:"ki",od:"ku",os:"k"}],
   sozlar:[{ar:"قَلَم",oq:"Qalam",tr:"Qalam",h:"ق+ل+م"},{ar:"كِتَاب",oq:"Kitaab",tr:"Kitob",h:"ك+ت+ا+ب"},{ar:"قَمَر",oq:"Qamar",tr:"Oy",h:"ق+م+ر"},{ar:"كَبِير",oq:"Kabiir",tr:"Katta",h:"ك+ب+ي+ر"},{ar:"أَكَلَ",oq:"Akala",tr:"Yedi",h:"أ+ك+ل"}],
   oqish:[{ar:"قَ قِ قُ قْ",iz:"Qof (chuqur q)"},{ar:"كَ كِ كُ كْ",iz:"Kof"},{ar:"كِتَابٌ كَبِيرٌ",iz:"Katta kitob"},{ar:"قَلَمٌ وَكِتَابٌ",iz:"Qalam va kitob"},{ar:"أَكَلَ الرَّجُلُ",iz:"Erkak yedi"}],
   yozish:[{t:"ق va ك farqini yozing",m:"ق chuqurroq—ك oldinroq"},{t:"'Qalam' va 'Kitaab' yozing",m:"قَلَمٌ—كِتَابٌ"},{t:"خُصَّ ضَغْطٍ قِظْ yozing",m:"خ ص ض ط ظ غ ق — Isti'lo"}],
   uyvazifa:["خُصَّ ضَغْطٍ قِظْ yod oling","ق va ك farqini tushuntiring","'Qalam','Kitaab','Qamar' yod oling"],
   test:[{s:"ق maxraji?",v:["Vasat Lison","Aqsal Lison","Tarafi Lison","Jawf"],t:1},{s:"Isti'lo yodlash iborasi?",v:["فِرَّ مِنْ لُبّ","خُصَّ ضَغْطٍ قِظْ","لِنْ عُمَرْ","فَحَثَّهُ"],t:1},{s:"كِتَاب ma'nosi?",v:["Qalam","Oy","Kitob","Katta"],t:2},{s:"ق va ك farqi?",v:["ق Hams, ك Jahr","ق chuqur, ك oldin","Shakl","Nuqta"],t:1},{s:"قَمَر ma'nosi?",v:["Quyosh","Oy","Yulduz","Osmon"],t:1}]},
  {id:12,harflar:["ل","م"],nomlar:["Lom","Mim"],
   maxraj:[{h:"ل",mx:"Tarafi Lison (til uchi yon—milk)",iz:"Til uchi yuqori milkka, havo yon tomoni orqali — Inhiraf."},{h:"م",mx:"Shafatayn (lab-lab)",iz:"Ikki lab yopiladi, nafas burundan — G'unna."}],
   sifatlar:[{h:"ل",sf:["Tavassut","Jahr","Istifol","Infitoh","Inhiraf","Izloq"]},{h:"م",sf:["Shadid","Jahr","Istifol","Infitoh","G'unna","Izloq"]}],
   shakllar:[{h:"ل",m:"ل",b:"لـ",o:"ـلـ",x:"ـل",iz:"Uzun tik chiziq"},{h:"م",m:"م",b:"مـ",o:"ـمـ",x:"ـم",iz:"Halqali shakl"}],
   harakatlar:[{h:"ل",f:"لَ",k:"لِ",d:"لُ",s:"لْ",of:"la",ok:"li",od:"lu",os:"l"},{h:"م",f:"مَ",k:"مِ",d:"مُ",s:"مْ",of:"ma",ok:"mi",od:"mu",os:"m"}],
   sozlar:[{ar:"لَيْل",oq:"Layl",tr:"Kecha",h:"ل+ي+ل"},{ar:"مَاء",oq:"Maau",tr:"Suv",h:"م+ا+ء"},{ar:"كَلَام",oq:"Kalaam",tr:"So'z",h:"ك+ل+ا+م"},{ar:"مُعَلِّم",oq:"Muʿallim",tr:"O'qituvchi",h:"م+ع+ل+م"},{ar:"لَمَسَ",oq:"Lamasa",tr:"Tegdi",h:"ل+م+س"}],
   oqish:[{ar:"لَ لِ لُ لْ",iz:"Lom 4 harakati"},{ar:"مَ مِ مُ مْ",iz:"Mim 4 harakati"},{ar:"لَيْلٌ وَنَهَارٌ",iz:"Kecha va kunduz"},{ar:"مُعَلِّمٌ كَرِيمٌ",iz:"Saxovatli o'qituvchi"},{ar:"لِنْ عُمَرْ",iz:"Tavassut yodlash: ل ن ع م ر"}],
   yozish:[{t:"Inhiraf sifatini tushuntir",m:"Havo yon tomoni orqali"},{t:"'Kalaam' va 'Muʿallim' yozing",m:"كَلَامٌ—مُعَلِّمٌ"},{t:"لِنْ عُمَرْ yozing (Tavassut)",m:"ل ن ع م ر"}],
   uyvazifa:["لِنْ عُمَرْ yod oling (Tavassut)","Inhiraf sifatini ko'rsating","'Layl','Maau','Muʿallim' yod oling"],
   test:[{s:"Inhiraf qaysi harflarda?",v:["ز س","ل ر","ن م","و ي"],t:1},{s:"Tavassut yodlash iborasi?",v:["فِرَّ مِنْ لُبّ","لِنْ عُمَرْ","خُصَّ ضَغْطٍ","فَحَثَّهُ"],t:1},{s:"مُعَلِّم ma'nosi?",v:["O'quvchi","O'qituvchi","Doktor","Muhandis"],t:1},{s:"م G'unna qachon?",v:["Har doim","Shadda va tanvinda","Fathada","Sukunda"],t:1},{s:"لَيْل ma'nosi?",v:["Kun","Kecha","Oy","Quyosh"],t:1}]},
  {id:13,harflar:["ن","ه"],nomlar:["Nun","Ha"],
   maxraj:[{h:"ن",mx:"Tarafi Lison (til uchi—milk)",iz:"Jarangli. Sukunda G'unna sifati."},{h:"ه",mx:"Adnal Halq",iz:"Tomoqning og'izga eng yaqin qismidan yengil nafas — jarangsiz h."}],
   sifatlar:[{h:"ن",sf:["Tavassut","Jahr","Istifol","Infitoh","G'unna","Izloq"]},{h:"ه",sf:["Raxv","Hams","Istifol","Infitoh","Ishmoq"]}],
   shakllar:[{h:"ن",m:"ن",b:"نـ",o:"ـنـ",x:"ـن",iz:"Bir nuqta ostida"},{h:"ه",m:"ه",b:"هـ",o:"ـهـ",x:"ـه",iz:"Maxsus shakl o'rtada"}],
   harakatlar:[{h:"ن",f:"نَ",k:"نِ",d:"نُ",s:"نْ",of:"na",ok:"ni",od:"nu",os:"n"},{h:"ه",f:"هَ",k:"هِ",d:"هُ",s:"هْ",of:"ha",ok:"hi",od:"hu",os:"h"}],
   sozlar:[{ar:"نُور",oq:"Nuur",tr:"Nur",h:"ن+و+ر"},{ar:"هَدِيَّة",oq:"Hadiyya",tr:"Sovg'a",h:"ه+د+ي+ة"},{ar:"نَهَر",oq:"Nahar",tr:"Daryo",h:"ن+ه+ر"},{ar:"هُنَا",oq:"Hunaa",tr:"Bu yerda",h:"ه+ن+ا"},{ar:"أَنَا",oq:"Anaa",tr:"Men",h:"أ+ن+ا"}],
   oqish:[{ar:"نَ نِ نُ نْ",iz:"Nun 4 harakati"},{ar:"هَ هِ هُ هْ",iz:"Ha 4 harakati"},{ar:"نُورٌ وَظَلَامٌ",iz:"Nur va zulmat"},{ar:"هُنَا وَهُنَاكَ",iz:"Bu yerda va u yerda"},{ar:"أَنَا هُنَا",iz:"Men bu yerdaman"}],
   yozish:[{t:"ن va م G'unnasini taqqoslang",m:"Ikkisi ham burundan"},{t:"'Nuur' va 'Hunaa' yozing",m:"نُورٌ—هُنَا"},{t:"ه va ح farqini yozing",m:"ه(Adnal,yengil)—ح(Vasat,chuqur)"}],
   uyvazifa:["G'unna sifatini ko'rsating","ه va ح farqini ayting","'Nuur','Nahar','Anaa' yod oling"],
   test:[{s:"ه maxraji?",v:["Vasat","Adnal Halq","Aqsal","Jawf"],t:1},{s:"G'unna harflari?",v:["ل ر","ز س","ن م","و ي"],t:2},{s:"نُور ma'nosi?",v:["Zulmat","Nur","Daryo","Sovg'a"],t:1},{s:"أَنَا ma'nosi?",v:["Sen","U","Men","Biz"],t:2},{s:"Tavassut harflari?",v:["ص ض ط ظ","ل ن ع م ر","ب ر ف","ن م"],t:1}]},
  {id:14,harflar:["و","ي"],nomlar:["Vov","Ya"],
   maxraj:[{h:"و",mx:"Shafatayn + Jawf (mad)",iz:"Lab: ikki lab yumaloqlanadi. Mad: cho'ziq Ū."},{h:"ي",mx:"Vasat Lison + Jawf (mad)",iz:"Til o'rtasi. Mad: cho'ziq Ī."}],
   sifatlar:[{h:"و",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Lin (sukunda)"]},{h:"ي",sf:["Raxv","Jahr","Istifol","Infitoh","Ishmoq","Lin (sukunda)"]}],
   shakllar:[{h:"و",m:"و",b:"و",o:"ـو",x:"ـو",iz:"Faqat o'ngga"},{h:"ي",m:"ي",b:"يـ",o:"ـيـ",x:"ـي",iz:"Ikki nuqta ostida"}],
   harakatlar:[{h:"و",f:"وَ",k:"وِ",d:"وُ",s:"وْ",of:"wa",ok:"wi",od:"wu",os:"w/Ū"},{h:"ي",f:"يَ",k:"يِ",d:"يُ",s:"يْ",of:"ya",ok:"yi",od:"yu",os:"y/Ī"}],
   sozlar:[{ar:"وَلَد",oq:"Walad",tr:"Bola",h:"و+ل+د"},{ar:"يَوْم",oq:"Yawm",tr:"Kun",h:"ي+و+م"},{ar:"بَيْت",oq:"Bayt",tr:"Uy",h:"ب+ي+ت"},{ar:"خَوْف",oq:"Xawf",tr:"Qo'rquv",h:"خ+و+ف"},{ar:"يَدٌ",oq:"Yad",tr:"Qo'l",h:"ي+د"}],
   oqish:[{ar:"وَ وِ وُ وْ",iz:"Vov 4 harakati"},{ar:"يَ يِ يُ يْ",iz:"Ya 4 harakati"},{ar:"خَوْفٌ وَبَيْتٌ",iz:"Lin sifati"},{ar:"يَوْمٌ جَمِيلٌ",iz:"Go'zal kun"},{ar:"وَلَدٌ وَبِنْتٌ",iz:"O'g'il va qiz"}],
   yozish:[{t:"Lin sifatini tushuntir",m:"خَوْف—بَيْت (sukunda)"},{t:"Mad: و=Ū, ي=Ī",m:"نُور(و uzun)—دِين(ي uzun)"},{t:"'Walad' va 'Yawm' yozing",m:"وَلَدٌ—يَوْمٌ"}],
   uyvazifa:["Lin va Mad sifatlarini tushuntiring","'Walad','Yawm','Bayt','Yad' yod oling","خَوْف va بَيْت da Lin sifatini ko'rsating"],
   test:[{s:"Lin sifati (qachon)?",v:["ل ر—har doim","و ي—sukunda","ن م—shadda","ز س—fathada"],t:1},{s:"بَيْت da ي holati?",v:["Mad","Lin (sukun)","Oddiy","G'unna"],t:1},{s:"وَلَد ma'nosi?",v:["Qiz","Bola","Daryo","Kun"],t:1},{s:"Mad da و qanday o'qiladi?",v:["wa","wi","Ū (uzun u)","wu"],t:2},{s:"يَوْم ma'nosi?",v:["Kecha","Oy","Kun","Yil"],t:2}]},
];
