export interface MockSavol {
  id: number;
  matn: string;
  arabcha?: string; // arabcha matn bo'lsa
  variantlar: string[];
  togri: number; // 0-based index
  izoh?: string; // nima uchun bu javob to'g'ri
}

export interface MockTest {
  id: number;
  nomi: string;
  daraja: "A0" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  tur: "alifbo" | "lug'at" | "grammatika" | "talaffuz" | "umumiy";
  davomiylik: number; // daqiqalarda
  savollar: MockSavol[];
  rang: string;
  icon: string;
}

export const MOCK_TESTLAR: MockTest[] = [
  {
    id: 1,
    nomi: "A0 — Alifbo testi",
    daraja: "A0",
    tur: "alifbo",
    davomiylik: 10,
    rang: "#0891B2",
    icon: "✏️",
    savollar: [
      {
        id: 1,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ب",
        variantlar: ["ba", "ta", "sa", "pa"],
        togri: 0,
        izoh: "ب — Ba, arabchaning ikkinchi harfi",
      },
      {
        id: 2,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ت",
        variantlar: ["ba", "ta", "jim", "xo"],
        togri: 1,
        izoh: "ت — Ta, arabchaning uchinchi harfi",
      },
      {
        id: 3,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ج",
        variantlar: ["ha", "xo", "jim", "ta"],
        togri: 2,
        izoh: "ج — Jim, arabchaning beshinchi harfi",
      },
      {
        id: 4,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ر",
        variantlar: ["ro", "zayn", "sin", "shin"],
        togri: 0,
        izoh: "ر — Ro, arabchaning o'n birinchi harfi",
      },
      {
        id: 5,
        matn: "'Alif' harfining arabcha yozilishi qaysi?",
        arabcha: undefined,
        variantlar: ["ع", "أ", "ا", "إ"],
        togri: 2,
        izoh: "ا — Alif, arabchaning birinchi harfi (hamzasiz shakli)",
      },
      {
        id: 6,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌َ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Sukun"],
        togri: 2,
        izoh: "Fatha — undosh ustiga yoziladi, 'a' ovozini beradi",
      },
      {
        id: 7,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌ِ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Tanvin"],
        togri: 0,
        izoh: "Kasra — undosh ostiga yoziladi, 'i' ovozini beradi",
      },
      {
        id: 8,
        matn: "Arabcha alifboda nechta harf bor?",
        arabcha: undefined,
        variantlar: ["26", "28", "30", "24"],
        togri: 1,
        izoh: "Arab alifbosida 28 ta harf mavjud",
      },
      {
        id: 9,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ع",
        variantlar: ["ayn", "g'ayn", "fa", "qof"],
        togri: 0,
        izoh: "ع — Ayn, arabchaning o'n sakkizinchi harfi",
      },
      {
        id: 10,
        matn: "Arabcha qaysi yo'nalishda o'qiladi?",
        arabcha: undefined,
        variantlar: ["Chapdan o'ngga", "O'ngdan chapga", "Yuqoridan pastga", "Pastdan yuqoriga"],
        togri: 1,
        izoh: "Arabcha o'ngdan chapga yoziladi va o'qiladi",
      },
    ],
  },
  {
    id: 2,
    nomi: "A1 — Lug'at testi",
    daraja: "A1",
    tur: "lug'at",
    davomiylik: 15,
    rang: "#2563EB",
    icon: "📝",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "بَيْت",
        variantlar: ["Maktab", "Uy", "Mashina", "Kitob"],
        togri: 1,
        izoh: "بَيْت (bayt) — uy",
      },
      {
        id: 2,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مُدَرِّس",
        variantlar: ["O'quvchi", "Kitob", "O'qituvchi", "Qalam"],
        togri: 2,
        izoh: "مُدَرِّس (mudarris) — o'qituvchi",
      },
      {
        id: 3,
        matn: "'Kitob' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["قَلَم", "كِتَاب", "مَدْرَسَة", "سَيَّارَة"],
        togri: 1,
        izoh: "كِتَاب (kitaab) — kitob",
      },
      {
        id: 4,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "سَيَّارَة",
        variantlar: ["Samolyot", "Mashina", "Velosiped", "Qayiq"],
        togri: 1,
        izoh: "سَيَّارَة (sayyaara) — mashina",
      },
      {
        id: 5,
        matn: "'Maktab' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["بَيْت", "مَدْرَسَة", "مَكْتَب", "مَسْجِد"],
        togri: 1,
        izoh: "مَدْرَسَة (madrasa) — maktab",
      },
      {
        id: 6,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مَاء",
        variantlar: ["Non", "Suv", "Choy", "Sharbat"],
        togri: 1,
        izoh: "مَاء (maa') — suv",
      },
      {
        id: 7,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "يَوْم",
        variantlar: ["Hafta", "Oy", "Kun", "Yil"],
        togri: 2,
        izoh: "يَوْم (yawm) — kun",
      },
      {
        id: 8,
        matn: "'Ota' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["أُم", "أَخ", "أَب", "اِبْن"],
        togri: 2,
        izoh: "أَب (ab) — ota",
      },
      {
        id: 9,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "طَالِب",
        variantlar: ["O'qituvchi", "Direktor", "O'quvchi", "Shifokor"],
        togri: 2,
        izoh: "طَالِب (toolib) — o'quvchi",
      },
      {
        id: 10,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "شَمْس",
        variantlar: ["Oy (samoviy jism)", "Yulduz", "Quyosh", "Bulut"],
        togri: 2,
        izoh: "شَمْس (shams) — quyosh",
      },
    ],
  },
  {
    id: 3,
    nomi: "A1 — Grammatika testi",
    daraja: "A1",
    tur: "grammatika",
    davomiylik: 15,
    rang: "#059669",
    icon: "📐",
    savollar: [
      {
        id: 1,
        matn: "'U (erkak)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنَا", "أَنْتَ", "هُوَ", "هِيَ"],
        togri: 2,
        izoh: "هُوَ (huwa) — u (erkak)",
      },
      {
        id: 2,
        matn: "'Biz' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنْتُمْ", "نَحْنُ", "هُمْ", "أَنْتَ"],
        togri: 1,
        izoh: "نَحْنُ (nahnu) — biz",
      },
      {
        id: 3,
        matn: "Quyidagi so'z qaysi jinsda?",
        arabcha: "مُعَلِّمَة",
        variantlar: ["Muzakkar (erkak jins)", "Muannash (ayol jins)", "Ikkalasi ham", "Hech biri"],
        togri: 1,
        izoh: "مُعَلِّمَة — muallima (ayol o'qituvchi), -a (ta-marbuta) ayol jinsini bildiradi",
      },
      {
        id: 4,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "هَذَا",
        variantlar: ["U (uzoqdagi erkak)", "Bu (yaqindagi erkak)", "Bu (yaqindagi ayol)", "Ular"],
        togri: 1,
        izoh: "هَذَا (haza) — bu (yaqindagi erkak jins uchun)",
      },
      {
        id: 5,
        matn: "Qaysi so'z muzakkar (erkak jins)?",
        arabcha: undefined,
        variantlar: ["مُعَلِّمَة", "طَالِبَة", "مُدِير", "مُدِيرَة"],
        togri: 2,
        izoh: "مُدِير (mudiir) — direktor (erkak), boshqalarida -a qo'shimchasi bor",
      },
      {
        id: 6,
        matn: "'U (ayol)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُوَ", "أَنَا", "هِيَ", "أَنْتِ"],
        togri: 2,
        izoh: "هِيَ (hiya) — u (ayol)",
      },
      {
        id: 7,
        matn: "'Ular (erkaklar)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُنَّ", "أَنْتُنَّ", "هُمْ", "نَحْنُ"],
        togri: 2,
        izoh: "هُمْ (hum) — ular (erkaklar yoki aralash guruh)",
      },
      {
        id: 8,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "تِلْكَ",
        variantlar: ["Bu (yaqin, erkak)", "Bu (yaqin, ayol)", "U (uzoq, ayol)", "U (uzoq, erkak)"],
        togri: 2,
        izoh: "تِلْكَ (tilka) — u (uzoqdagi ayol jins uchun)",
      },
      {
        id: 9,
        matn: "Quyidagi so'z ko'plikda qanday bo'ladi?",
        arabcha: "كِتَاب",
        variantlar: ["كِتَابَات", "كُتُب", "كِتَابَان", "كِتَابَيْن"],
        togri: 1,
        izoh: "كُتُب (kutub) — kitoblar (ko'plik shakli)",
      },
      {
        id: 10,
        matn: "'Men o'quvchiman' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["أَنَا مُدَرِّس", "أَنَا طَالِب", "هُوَ طَالِب", "أَنْتَ طَالِب"],
        togri: 1,
        izoh: "أَنَا طَالِب (anaa toolib) — Men o'quvchiman",
      },
    ],
  },
  {
    id: 4,
    nomi: "A2 — Umumiy test",
    daraja: "A2",
    tur: "umumiy",
    davomiylik: 20,
    rang: "#CA8A04",
    icon: "🎯",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi fe'l o'tgan zamonda qanday o'qiladi?",
        arabcha: "ذَهَبَ",
        variantlar: ["zahaba (u bordi)", "yazhabu (u boradi)", "zahab (boring)", "layzhabu (u bormaydi)"],
        togri: 0,
        izoh: "ذَهَبَ (zahaba) — u bordi (erkak, o'tgan zamon)",
      },
      {
        id: 2,
        matn: "Quyidagi gapning tarjimasi nima?",
        arabcha: "أَنَا أَذْهَبُ إِلَى المَدْرَسَة",
        variantlar: ["Men maktabga bordim", "Men maktabga boraman", "U maktabga boradi", "Biz maktabga boramiz"],
        togri: 1,
        izoh: "أَذْهَبُ — hozirgi/kelasi zamon, birinchi shaxs (men boraman)",
      },
      {
        id: 3,
        matn: "Quyidagi savol so'zi nima degan ma'noni anglatadi?",
        arabcha: "مَتَى؟",
        variantlar: ["Qayerda?", "Nima?", "Qachon?", "Qanday?"],
        togri: 2,
        izoh: "مَتَى (mataa) — qachon?",
      },
      {
        id: 4,
        matn: "Quyidagi jumla to'g'ri tarjima qilinganmi?",
        arabcha: "البَيْتُ كَبِير",
        variantlar: ["Kichik uy", "Katta uy", "Yangi uy", "Eski uy"],
        togri: 1,
        izoh: "كَبِير (kabiir) — katta; البَيْتُ كَبِير — uy katta",
      },
      {
        id: 5,
        matn: "Arabchada 'Nima?' savol so'zi qaysi?",
        arabcha: undefined,
        variantlar: ["مَنْ", "أَيْنَ", "مَاذَا", "كَيْفَ"],
        togri: 2,
        izoh: "مَاذَا (maaza) — nima?, biror narsa haqida so'rash uchun",
      },
    ],
  },
];
