export interface MockSavol {
  id: number;
  matn: string;
  arabcha?: string; // arabcha matn bo'lsa
  variantlar: string[];
  togri: number; // 0-based index
  izoh?: string; // nima uchun bu javob to'g'ri
}

export interface MockTest {
  id: number;
  nomi: string;
  daraja: "A0" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  tur: "alifbo" | "lug'at" | "grammatika" | "talaffuz" | "umumiy";
  davomiylik: number; // daqiqalarda
  savollar: MockSavol[];
  rang: string;
  icon: string;
}

export const MOCK_TESTLAR: MockTest[] = [
  {
    id: 1,
    nomi: "A0 — Alifbo testi",
    daraja: "A0",
    tur: "alifbo",
    davomiylik: 10,
    rang: "#0891B2",
    icon: "✏️",
    savollar: [
      {
        id: 1,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ب",
        variantlar: ["ba", "ta", "sa", "pa"],
        togri: 0,
        izoh: "ب — Ba, arabchaning ikkinchi harfi",
      },
      {
        id: 2,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ت",
        variantlar: ["ba", "ta", "jim", "xo"],
        togri: 1,
        izoh: "ت — Ta, arabchaning uchinchi harfi",
      },
      {
        id: 3,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ج",
        variantlar: ["ha", "xo", "jim", "ta"],
        togri: 2,
        izoh: "ج — Jim, arabchaning beshinchi harfi",
      },
      {
        id: 4,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ر",
        variantlar: ["ro", "zayn", "sin", "shin"],
        togri: 0,
        izoh: "ر — Ro, arabchaning o'n birinchi harfi",
      },
      {
        id: 5,
        matn: "'Alif' harfining arabcha yozilishi qaysi?",
        arabcha: undefined,
        variantlar: ["ع", "أ", "ا", "إ"],
        togri: 2,
        izoh: "ا — Alif, arabchaning birinchi harfi (hamzasiz shakli)",
      },
      {
        id: 6,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌َ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Sukun"],
        togri: 2,
        izoh: "Fatha — undosh ustiga yoziladi, 'a' ovozini beradi",
      },
      {
        id: 7,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌ِ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Tanvin"],
        togri: 0,
        izoh: "Kasra — undosh ostiga yoziladi, 'i' ovozini beradi",
      },
      {
        id: 8,
        matn: "Arabcha alifboda nechta harf bor?",
        arabcha: undefined,
        variantlar: ["26", "28", "30", "24"],
        togri: 1,
        izoh: "Arab alifbosida 28 ta harf mavjud",
      },
      {
        id: 9,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ع",
        variantlar: ["ayn", "g'ayn", "fa", "qof"],
        togri: 0,
        izoh: "ع — Ayn, arabchaning o'n sakkizinchi harfi",
      },
      {
        id: 10,
        matn: "Arabcha qaysi yo'nalishda o'qiladi?",
        arabcha: undefined,
        variantlar: ["Chapdan o'ngga", "O'ngdan chapga", "Yuqoridan pastga", "Pastdan yuqoriga"],
        togri: 1,
        izoh: "Arabcha o'ngdan chapga yoziladi va o'qiladi",
      },
    ],
  },
  {
    id: 2,
    nomi: "A1 — Lug'at testi",
    daraja: "A1",
    tur: "lug'at",
    davomiylik: 15,
    rang: "#2563EB",
    icon: "📝",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "بَيْت",
        variantlar: ["Maktab", "Uy", "Mashina", "Kitob"],
        togri: 1,
        izoh: "بَيْت (bayt) — uy",
      },
      {
        id: 2,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مُدَرِّس",
        variantlar: ["O'quvchi", "Kitob", "O'qituvchi", "Qalam"],
        togri: 2,
        izoh: "مُدَرِّس (mudarris) — o'qituvchi",
      },
      {
        id: 3,
        matn: "'Kitob' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["قَلَم", "كِتَاب", "مَدْرَسَة", "سَيَّارَة"],
        togri: 1,
        izoh: "كِتَاب (kitaab) — kitob",
      },
      {
        id: 4,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "سَيَّارَة",
        variantlar: ["Samolyot", "Mashina", "Velosiped", "Qayiq"],
        togri: 1,
        izoh: "سَيَّارَة (sayyaara) — mashina",
      },
      {
        id: 5,
        matn: "'Maktab' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["بَيْت", "مَدْرَسَة", "مَكْتَب", "مَسْجِد"],
        togri: 1,
        izoh: "مَدْرَسَة (madrasa) — maktab",
      },
      {
        id: 6,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مَاء",
        variantlar: ["Non", "Suv", "Choy", "Sharbat"],
        togri: 1,
        izoh: "مَاء (maa') — suv",
      },
      {
        id: 7,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "يَوْم",
        variantlar: ["Hafta", "Oy", "Kun", "Yil"],
        togri: 2,
        izoh: "يَوْم (yawm) — kun",
      },
      {
        id: 8,
        matn: "'Ota' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["أُم", "أَخ", "أَب", "اِبْن"],
        togri: 2,
        izoh: "أَب (ab) — ota",
      },
      {
        id: 9,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "طَالِب",
        variantlar: ["O'qituvchi", "Direktor", "O'quvchi", "Shifokor"],
        togri: 2,
        izoh: "طَالِب (toolib) — o'quvchi",
      },
      {
        id: 10,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "شَمْس",
        variantlar: ["Oy (samoviy jism)", "Yulduz", "Quyosh", "Bulut"],
        togri: 2,
        izoh: "شَمْس (shams) — quyosh",
      },
    ],
  },
  {
    id: 3,
    nomi: "A1 — Grammatika testi",
    daraja: "A1",
    tur: "grammatika",
    davomiylik: 15,
    rang: "#059669",
    icon: "📐",
    savollar: [
      {
        id: 1,
        matn: "'U (erkak)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنَا", "أَنْتَ", "هُوَ", "هِيَ"],
        togri: 2,
        izoh: "هُوَ (huwa) — u (erkak)",
      },
      {
        id: 2,
        matn: "'Biz' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنْتُمْ", "نَحْنُ", "هُمْ", "أَنْتَ"],
        togri: 1,
        izoh: "نَحْنُ (nahnu) — biz",
      },
      {
        id: 3,
        matn: "Quyidagi so'z qaysi jinsda?",
        arabcha: "مُعَلِّمَة",
        variantlar: ["Muzakkar (erkak jins)", "Muannash (ayol jins)", "Ikkalasi ham", "Hech biri"],
        togri: 1,
        izoh: "مُعَلِّمَة — muallima (ayol o'qituvchi), -a (ta-marbuta) ayol jinsini bildiradi",
      },
      {
        id: 4,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "هَذَا",
        variantlar: ["U (uzoqdagi erkak)", "Bu (yaqindagi erkak)", "Bu (yaqindagi ayol)", "Ular"],
        togri: 1,
        izoh: "هَذَا (haza) — bu (yaqindagi erkak jins uchun)",
      },
      {
        id: 5,
        matn: "Qaysi so'z muzakkar (erkak jins)?",
        arabcha: undefined,
        variantlar: ["مُعَلِّمَة", "طَالِبَة", "مُدِير", "مُدِيرَة"],
        togri: 2,
        izoh: "مُدِير (mudiir) — direktor (erkak), boshqalarida -a qo'shimchasi bor",
      },
      {
        id: 6,
        matn: "'U (ayol)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُوَ", "أَنَا", "هِيَ", "أَنْتِ"],
        togri: 2,
        izoh: "هِيَ (hiya) — u (ayol)",
      },
      {
        id: 7,
        matn: "'Ular (erkaklar)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُنَّ", "أَنْتُنَّ", "هُمْ", "نَحْنُ"],
        togri: 2,
        izoh: "هُمْ (hum) — ular (erkaklar yoki aralash guruh)",
      },
      {
        id: 8,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "تِلْكَ",
        variantlar: ["Bu (yaqin, erkak)", "Bu (yaqin, ayol)", "U (uzoq, ayol)", "U (uzoq, erkak)"],
        togri: 2,
        izoh: "تِلْكَ (tilka) — u (uzoqdagi ayol jins uchun)",
      },
      {
        id: 9,
        matn: "Quyidagi so'z ko'plikda qanday bo'ladi?",
        arabcha: "كِتَاب",
        variantlar: ["كِتَابَات", "كُتُب", "كِتَابَان", "كِتَابَيْن"],
        togri: 1,
        izoh: "كُتُب (kutub) — kitoblar (ko'plik shakli)",
      },
      {
        id: 10,
        matn: "'Men o'quvchiman' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["أَنَا مُدَرِّس", "أَنَا طَالِب", "هُوَ طَالِب", "أَنْتَ طَالِب"],
        togri: 1,
        izoh: "أَنَا طَالِب (anaa toolib) — Men o'quvchiman",
      },
    ],
  },
  {
    id: 4,
    nomi: "A2 — Umumiy test",
    daraja: "A2",
    tur: "umumiy",
    davomiylik: 20,
    rang: "#CA8A04",
    icon: "🎯",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi fe'l o'tgan zamonda qanday o'qiladi?",
        arabcha: "ذَهَبَ",
        variantlar: ["zahaba (u bordi)", "yazhabu (u boradi)", "zahab (boring)", "layzhabu (u bormaydi)"],
        togri: 0,
        izoh: "ذَهَبَ (zahaba) — u bordi (erkak, o'tgan zamon)",
      },
      {
        id: 2,
        matn: "Quyidagi gapning tarjimasi nima?",
        arabcha: "أَنَا أَذْهَبُ إِلَى المَدْرَسَة",
        variantlar: ["Men maktabga bordim", "Men maktabga boraman", "U maktabga boradi", "Biz maktabga boramiz"],
        togri: 1,
        izoh: "أَذْهَبُ — hozirgi/kelasi zamon, birinchi shaxs (men boraman)",
      },
      {
        id: 3,
        matn: "Quyidagi savol so'zi nima degan ma'noni anglatadi?",
        arabcha: "مَتَى؟",
        variantlar: ["Qayerda?", "Nima?", "Qachon?", "Qanday?"],
        togri: 2,
        izoh: "مَتَى (mataa) — qachon?",
      },
      {
        id: 4,
        matn: "Quyidagi jumla to'g'ri tarjima qilinganmi?",
        arabcha: "البَيْتُ كَبِير",
        variantlar: ["Kichik uy", "Katta uy", "Yangi uy", "Eski uy"],
        togri: 1,
        izoh: "كَبِير (kabiir) — katta; البَيْتُ كَبِير — uy katta",
      },
      {
        id: 5,
        matn: "Arabchada 'Nima?' savol so'zi qaysi?",
        arabcha: undefined,
        variantlar: ["مَنْ", "أَيْنَ", "مَاذَا", "كَيْفَ"],
        togri: 2,
        izoh: "مَاذَا (maaza) — nima?, biror narsa haqida so'rash uchun",
      },
    ],
  },

  // ─── A2 Grammatika ──────────────────────────────────────────────────────────
  {
    id: 5,
    nomi: "A2 — Grammatika testi",
    daraja: "A2",
    tur: "grammatika",
    davomiylik: 20,
    rang: "#7C3AED",
    icon: "📐",
    savollar: [
      {
        id: 1,
        matn: "كَتَبَتْ so'zi qaysi shaxs va jinsda?",
        arabcha: "كَتَبَتْ",
        variantlar: ["1-shaxs erkak", "3-shaxs erkak", "3-shaxs ayol", "2-shaxs ayol"],
        togri: 2,
        izoh: "كَتَبَتْ — katabat: 3-shaxs yagona ayol, o'tgan zamon ('u yozdi' — ayol)",
      },
      {
        id: 2,
        matn: "'Biz yozdik' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["كَتَبُوا", "كَتَبْتُ", "كَتَبْنَا", "كَتَبَتْ"],
        togri: 2,
        izoh: "كَتَبْنَا (katabna) — biz yozdik (1-shaxs ko'plik)",
      },
      {
        id: 3,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "الْكِتَابُ عَلَى الطَّاوِلَةِ",
        variantlar: ["Kitob sumkada", "Kitob stol ostida", "Kitob stolning ustida", "Kitob yerdagi stol"],
        togri: 2,
        izoh: "عَلَى — ustida/ustiga; الطَّاوِلَة — stol",
      },
      {
        id: 4,
        matn: "'Maktabdan' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["إِلَى الْمَدْرَسَةِ", "فِي الْمَدْرَسَةِ", "مِنَ الْمَدْرَسَةِ", "عَلَى الْمَدْرَسَةِ"],
        togri: 2,
        izoh: "مِنْ — dan/manba bildiradi: مِنَ الْمَدْرَسَةِ = maktabdan",
      },
      {
        id: 5,
        matn: "Sifat otdan qayerda turadi?",
        arabcha: undefined,
        variantlar: ["Oldida", "Keyin", "Gapning boshida", "Gapning oxirida"],
        togri: 1,
        izoh: "Arabchada sifat (na't) doimo otdan KEYIN keladi: بَيْتٌ كَبِيرٌ = katta uy",
      },
      {
        id: 6,
        matn: "Quyidagi birikma to'g'rimi?",
        arabcha: "سَيَّارَةٌ كَبِيرَةٌ",
        variantlar: ["Ha, to'g'ri", "Yo'q, كَبِيرٌ bo'lishi kerak", "Yo'q, سَيَّارَة boshqa bo'lishi kerak", "Yo'q, tartib noto'g'ri"],
        togri: 0,
        izoh: "سَيَّارَة muannash → sifat ham muannash: كَبِيرَةٌ — to'g'ri",
      },
      {
        id: 7,
        matn: "الطَّالِبُ الْجَدِيدُ gapini tarjima qiling.",
        arabcha: "الطَّالِبُ الْجَدِيدُ",
        variantlar: ["Yangi o'quvchi (ma'lum)", "O'quvchi yangi", "Yangi o'quvchi (noma'lum)", "O'quvchilar yangi"],
        togri: 0,
        izoh: "الـ + الـ = aniq birikmali sifat: yangi o'quvchi (ma'lum, belgilangan)",
      },
      {
        id: 8,
        matn: "O'tgan zamon fe'lida 2-shaxs yagona erkak qo'shimchasi qaysi?",
        arabcha: undefined,
        variantlar: ["تُ", "تَ", "تِ", "نَا"],
        togri: 1,
        izoh: "كَتَبْتَ (katabta) — sen yozding (erkak): قo'shimcha = تَ",
      },
      {
        id: 9,
        matn: "'Uyda' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["عَلَى الْبَيْتِ", "مِنَ الْبَيْتِ", "فِي الْبَيْتِ", "إِلَى الْبَيْتِ"],
        togri: 2,
        izoh: "فِي — da/ichida: فِي الْبَيْتِ = uyda",
      },
      {
        id: 10,
        matn: "Quyidagi so'z aniqmi yoki noaniqmi?",
        arabcha: "الْقَلَمُ",
        variantlar: ["Noaniq (tanvin bor)", "Aniq (الـ bor)", "Ko'plik", "Fe'l"],
        togri: 1,
        izoh: "الـ artikli so'zni aniq qiladi: الْقَلَمُ = qalam (ma'lum, aniq)",
      },
    ],
  },

  // ─── A2 Lug'at ──────────────────────────────────────────────────────────────
  {
    id: 6,
    nomi: "A2 — Lug'at testi",
    daraja: "A2",
    tur: "lug'at",
    davomiylik: 20,
    rang: "#059669",
    icon: "📖",
    savollar: [
      {
        id: 1,
        matn: "So'zning tarjimasini toping.",
        arabcha: "ذَهَبَ",
        variantlar: ["Keldi", "Bordi", "Ko'rdi", "Yozdi"],
        togri: 1,
        izoh: "ذَهَبَ (zahaba) — bordi (o'tgan zamon, 3-shaxs erkak)",
      },
      {
        id: 2,
        matn: "So'zning tarjimasini toping.",
        arabcha: "طَاوِلَة",
        variantlar: ["Kursi", "Stol", "Deraza", "Eshik"],
        togri: 1,
        izoh: "طَاوِلَة (taawila) — stol",
      },
      {
        id: 3,
        matn: "'Tez' so'zi arabchada qanday?",
        arabcha: undefined,
        variantlar: ["كَبِير", "صَغِير", "سَرِيع", "جَدِيد"],
        togri: 2,
        izoh: "سَرِيع (sari') — tez",
      },
      {
        id: 4,
        matn: "So'zning tarjimasini toping.",
        arabcha: "أَكَلَ",
        variantlar: ["Ichdi", "Yedi", "O'qidi", "Yozdi"],
        togri: 1,
        izoh: "أَكَلَ (akala) — yedi (o'tgan zamon)",
      },
      {
        id: 5,
        matn: "So'zning tarjimasini toping.",
        arabcha: "نَافِذَة",
        variantlar: ["Eshik", "Stol", "Deraza", "Devor"],
        togri: 2,
        izoh: "نَافِذَة (naafiza) — deraza",
      },
      {
        id: 6,
        matn: "'Yangi' so'zi arabchada qanday (muannash shakl)?",
        arabcha: undefined,
        variantlar: ["جَدِيد", "جَدِيدَة", "قَدِيم", "قَدِيمَة"],
        togri: 1,
        izoh: "جَدِيدَة (jadiida) — yangi (muannash), جَدِيد — erkak shakl",
      },
      {
        id: 7,
        matn: "So'zning tarjimasini toping.",
        arabcha: "شَرِبَ",
        variantlar: ["Yedi", "Yozdi", "Ichdi", "Bordi"],
        togri: 2,
        izoh: "شَرِبَ (shariba) — ichdi (o'tgan zamon)",
      },
      {
        id: 8,
        matn: "So'zning tarjimasini toping.",
        arabcha: "كُرْسِي",
        variantlar: ["Stol", "Kursi", "Kitob", "Qalam"],
        togri: 1,
        izoh: "كُرْسِي (kursiy) — kursi",
      },
      {
        id: 9,
        matn: "'Baland/uzun' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["قَصِير", "طَوِيل", "كَبِير", "صَغِير"],
        togri: 1,
        izoh: "طَوِيل (tawiil) — uzun/baland, قَصِير esa qisqa/past",
      },
      {
        id: 10,
        matn: "So'zning tarjimasini toping.",
        arabcha: "غُرْفَة",
        variantlar: ["Hovli", "Xona/uy xonasi", "Maktab", "Do'kon"],
        togri: 1,
        izoh: "غُرْفَة (ghurfa) — xona (uy ichidagi xona)",
      },
    ],
  },

  // ─── B1 Grammatika ──────────────────────────────────────────────────────────
  {
    id: 7,
    nomi: "B1 — Grammatika testi",
    daraja: "B1",
    tur: "grammatika",
    davomiylik: 25,
    rang: "#2563EB",
    icon: "🧠",
    savollar: [
      {
        id: 1,
        matn: "Hozirgi/kelasi zamon fe'li qanday yasaladi?",
        arabcha: "يَكْتُبُ",
        variantlar: ["O'tgan zamon, 3-shaxs erkak", "Hozirgi zamon, 3-shaxs erkak", "Buyruq mayli", "Inkor"],
        togri: 1,
        izoh: "يَكْتُبُ (yaktubu) — u yozadi/yozmoqda: hozirgi/kelasi zamon, 3-shaxs erkak",
      },
      {
        id: 2,
        matn: "Hozirgi zamonda 1-shaxs shakli qaysi?",
        arabcha: "يَكْتُبُ → ?",
        variantlar: ["نَكْتُبُ", "أَكْتُبُ", "تَكْتُبُ", "يَكْتُبَانِ"],
        togri: 1,
        izoh: "أَكْتُبُ (aktubu) — men yozaman: 1-shaxs yagona, hozirgi zamon (أ- prefiksi)",
      },
      {
        id: 3,
        matn: "Quyidagi inkor gapni tarjima qiling.",
        arabcha: "لَا أَفْهَمُ",
        variantlar: ["Men tushundim", "Men tushunaman", "Men tushunmayapman", "U tushunmaydi"],
        togri: 2,
        izoh: "لَا + fe'l = inkor: لَا أَفْهَمُ = men tushunmayapman/tushunmayman",
      },
      {
        id: 4,
        matn: "Masdar (infinitiv) qaysi?",
        arabcha: undefined,
        variantlar: ["كَتَبَ", "يَكْتُبُ", "كِتَابَة", "كَاتِب"],
        togri: 2,
        izoh: "كِتَابَة (kitaaba) — yozish (masdar/infinitiv), كَتَبَ = yozdi, يَكْتُبُ = yozadi",
      },
      {
        id: 5,
        matn: "Shart gapida qaysi bog'lovchi ishlatiladi?",
        arabcha: undefined,
        variantlar: ["وَ (va)", "أَوْ (yoki)", "إِذَا (agar)", "لَكِنْ (lekin)"],
        togri: 2,
        izoh: "إِذَا (iza) — agar: shart gaplarida ishlatiladi. إِذَا دَرَسْتَ نَجَحْتَ = agar o'qisang, muvaffaq bo'lasan",
      },
      {
        id: 6,
        matn: "Quyidagi jumla to'g'ri tarjima qilinganmi?",
        arabcha: "كَانَ الطَّقْسُ بَارِدًا",
        variantlar: ["Havo sovuq", "Havo sovuq edi", "Havo issiq edi", "Havo issiq bo'ladi"],
        togri: 1,
        izoh: "كَانَ — o'tgan zamonda 'bo'lmoq/edi': كَانَ ... بَارِدًا = sovuq edi",
      },
      {
        id: 7,
        matn: "Hol (zarf) qaysi javobda to'g'ri?",
        arabcha: undefined,
        variantlar: ["بَيْتٌ كَبِيرٌ", "كَتَبَ بِسُرْعَةٍ", "هُوَ طَالِبٌ", "الْكِتَابُ جَدِيدٌ"],
        togri: 1,
        izoh: "كَتَبَ بِسُرْعَةٍ (kataba bisur'atin) — u tez yozdi: بِسُرْعَةٍ holdir (qanday yozdi?)",
      },
      {
        id: 8,
        matn: "'Agar yog'in yog'sa, uyda qolaman' gapidagi shart qo'shimchasi qaysi?",
        arabcha: "إِذَا أَمْطَرَتْ، بَقِيتُ فِي الْبَيْتِ",
        variantlar: ["بَقِيتُ", "أَمْطَرَتْ", "إِذَا", "فِي الْبَيْتِ"],
        togri: 2,
        izoh: "إِذَا — 'agar' ma'nosida shart bog'lovchisi",
      },
      {
        id: 9,
        matn: "Juft son (ikkilik) qo'shimchasi qaysi?",
        arabcha: undefined,
        variantlar: ["ون-", "ات-", "ان-", "ين-"],
        togri: 2,
        izoh: "كِتَابَانِ (kitabani) — ikki kitob: -ان qo'shimchasi yagonani ikkiga aylantiradi",
      },
      {
        id: 10,
        matn: "Faol ism (ism fa'il) qaysi?",
        arabcha: undefined,
        variantlar: ["مَكْتُوب (yozilgan)", "كِتَابَة (yozish)", "كَاتِب (yozuvchi)", "كَتَبَ (yozdi)"],
        togri: 2,
        izoh: "كَاتِب (katib) — yozuvchi: faol ism (ism fa'il) — ish bajaruvchi shaxs",
      },
    ],
  },

  // ─── B1 Umumiy ──────────────────────────────────────────────────────────────
  {
    id: 8,
    nomi: "B1 — Umumiy test",
    daraja: "B1",
    tur: "umumiy",
    davomiylik: 25,
    rang: "#DC2626",
    icon: "🏆",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "أُحِبُّ تَعَلُّمَ اللُّغَةِ الْعَرَبِيَّةِ",
        variantlar: [
          "U arabcha o'rganishni yaxshi ko'radi",
          "Men arabcha o'rganishni yaxshi ko'raman",
          "Biz arabcha o'rganamiz",
          "Sen arabcha bilasan",
        ],
        togri: 1,
        izoh: "أُحِبُّ — men yaxshi ko'raman (1-shaxs); تَعَلُّم — o'rganish (masdar)",
      },
      {
        id: 2,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مَطَار",
        variantlar: ["Temir yo'l", "Kemaxona", "Aeroport", "Avtobus bekat"],
        togri: 2,
        izoh: "مَطَار (mataar) — aeroport",
      },
      {
        id: 3,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "لَمْ أَذْهَبْ إِلَى الْعَمَلِ الْيَوْمَ",
        variantlar: [
          "Men bugun ishga boraman",
          "Men bugun ishga bormadim",
          "U bugun ishga bormadi",
          "Men kecha ishga bormadim",
        ],
        togri: 1,
        izoh: "لَمْ + mudori' majzum = o'tgan zamonda inkor: لَمْ أَذْهَبْ = men bormadim; الْيَوْمَ = bugun",
      },
      {
        id: 4,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مُهَنْدِس",
        variantlar: ["Shifokor", "Muhandis/muallim", "Muhandis/injener", "Savdogar"],
        togri: 2,
        izoh: "مُهَنْدِس (muhandis) — muhandis, injener",
      },
      {
        id: 5,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "كُنْتُ أَعِيشُ فِي الْقَاهِرَةِ",
        variantlar: [
          "Men Qohirada yashayman",
          "Men Qohirada yashar edim",
          "U Qohirada yashadi",
          "Biz Qohirada yashaymiz",
        ],
        togri: 1,
        izoh: "كُنْتُ أَعِيشُ — men yashar edim (davomli o'tgan zamon): كَانَ + hozirgi fe'l",
      },
      {
        id: 6,
        matn: "So'zning tarjimasini toping.",
        arabcha: "اِجْتِمَاع",
        variantlar: ["Dam olish", "Uchrashuv/yig'ilish", "Imtihon", "Safar"],
        togri: 1,
        izoh: "اِجْتِمَاع (ijtima') — yig'ilish, uchrashuv",
      },
      {
        id: 7,
        matn: "Quyidagi gapni to'ldiring.",
        arabcha: "سَأَذْهَبُ إِلَى السُّوقِ ___ أَشْتَرِيَ خُضَارًا",
        variantlar: ["لِأَنَّ", "وَلَكِنْ", "لِ (uchun)", "إِذَا"],
        togri: 2,
        izoh: "لِ + fe'l = uchun/maqsadida: سَأَذْهَبُ لِأَشْتَرِيَ = boraman, sabzavot sotib olish uchun",
      },
      {
        id: 8,
        matn: "So'zning tarjimasini toping.",
        arabcha: "صَعْب",
        variantlar: ["Oson", "Qiziq", "Qiyin", "Chiroyli"],
        togri: 2,
        izoh: "صَعْب (sa'b) — qiyin, murakkab. Aksi: سَهْل (sahl) = oson",
      },
      {
        id: 9,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "أَتَكَلَّمُ الْعَرَبِيَّةَ قَلِيلًا",
        variantlar: [
          "Men arabchani yaxshi bilaman",
          "Men arabchani ozgina gapiraman",
          "U arabchani o'rganadi",
          "Men arabchani o'rganmoqchiman",
        ],
        togri: 1,
        izoh: "أَتَكَلَّمُ = men gapiraman; قَلِيلًا = ozgina, sal",
      },
      {
        id: 10,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مُتَعَب",
        variantlar: ["Xursand", "Charchagan", "Kasal", "Ochigan"],
        togri: 1,
        izoh: "مُتَعَب (muta'ab) — charchagan, holdan toygan",
      },
    ],
  },
  {
    id: 9,
    nomi: "B2 — Grammatika testi",
    daraja: "B2",
    tur: "grammatika",
    davomiylik: 20,
    rang: "#CA8A04",
    icon: "⚡",
    savollar: [
      {
        id: 1,
        matn: "كَانَ fe'li qanday gap tuzilmasini talab qiladi?",
        variantlar: ["Mubtada + khabar (ikkalasi marf')", "Ism + xabar (ism mansub, xabar marf')", "Faqat fe'l + subyekt", "Hech qanday o'zgarish"],
        togri: 1,
        izoh: "كَانَ ismi mansub, xabari marf' bo'ladi: كَانَ الطَّالِبُ مُجْتَهِدًا",
      },
      {
        id: 2,
        matn: "كَانَ ning inkor shakli qaysi?",
        arabcha: "كَانَ الطَّقْسُ جَمِيلًا",
        variantlar: ["لَمْ يَكُنِ الطَّقْسُ جَمِيلًا", "لَا يَكُونُ الطَّقْسُ جَمِيلًا", "مَا كَانَ الطَّقْسُ جَمِيلًا", "كَانَ الطَّقْسُ لَيْسَ جَمِيلًا"],
        togri: 0,
        izoh: "لَمْ + مضارع مجزوم: لَمْ يَكُنْ — o'tgan zamon inkori",
      },
      {
        id: 3,
        matn: "Quyidagi naqis fe'llardan qaysi biri 'bo'lib qoldi / aylandi' ma'nosini beradi?",
        variantlar: ["ظَلَّ", "أَصْبَحَ", "صَارَ", "لَيْسَ"],
        togri: 2,
        izoh: "صَارَ = aylandi, bo'lib qoldi (holatning o'zgarishi)",
      },
      {
        id: 4,
        matn: "إِنْ shart yuklamas qaysi holda ishlatiladi?",
        variantlar: ["Noreal (bajarib bo'lmaydigan) shart", "Real (mumkin) shart", "O'tgan voqea", "Buyruq ifodalash"],
        togri: 1,
        izoh: "إِنْ — real, mumkin shart uchun; لَوْ — noreal shart uchun",
      },
      {
        id: 5,
        matn: "لَوْ دَرَسْتَ لَنَجَحْتَ gapining ma'nosi nima?",
        variantlar: ["Agar o'qisang, o'tasan", "O'qiganingda o'tarding (lekin o'qimading)", "O'qi, keyin o'tasan", "O'qish shart emas"],
        togri: 1,
        izoh: "لَوْ — noreal shart: شart bajarilmagan, shuning uchun natija ham yuz bermagan",
      },
      {
        id: 6,
        matn: "Fe'l tizimlari (mazid) da vazn II (فَعَّلَ) qanday ma'no qo'shadi?",
        variantlar: ["O'zaro harakat", "Ettirish/intensivlik", "O'zlik", "Passiv"],
        togri: 1,
        izoh: "Vazn II (فَعَّلَ): ettirish yoki intensivlik — دَرَّسَ = o'qitdi (دَرَسَ dan)",
      },
      {
        id: 7,
        matn: "أَصْبَحَ الطِّفْلُ طَوِيلًا gapidagi naqis fe'lning roli nima?",
        variantlar: ["Harakatni bildiradi", "Subyektni o'tgan vaqt holatida ifodalaydi", "Holatning o'zgarishini bildiradi (erta tongda)", "Inkor bildiradi"],
        togri: 2,
        izoh: "أَصْبَحَ = ertalab bo'ldi / aylandi — holatning erta tongga o'tish belgisi",
      },
      {
        id: 8,
        matn: "Vazn V (تَفَعَّلَ) Vazn II (فَعَّلَ) dan qanday yasaladi va qanday ma'no beradi?",
        variantlar: ["تَـ qo'shiladi, passiv ma'no", "تَـ qo'shiladi, o'zlik ma'nosi (o'z-o'zi)", "أَـ qo'shiladi, ettirish", "لا qo'shiladi, inkor"],
        togri: 1,
        izoh: "تَفَعَّلَ = Vazn II ga تَـ qo'shiladi, o'zlik: عَلَّمَ → تَعَلَّمَ (o'qitdi → o'rgandi)",
      },
      {
        id: 9,
        matn: "ظَلَّ الْهَوَاءُ بَارِدًا gapidagi naqis fe'l qaysi?",
        variantlar: ["الْهَوَاءُ", "ظَلَّ", "بَارِدًا", "Hech biri"],
        togri: 1,
        izoh: "ظَلَّ = davom etdi, qolaverdi — naqis fe'l",
      },
      {
        id: 10,
        matn: "إِنْ تَعْمَلْ بِجِدٍّ تَنْجَحْ gapida fe'llar qaysi holatda?",
        variantlar: ["Ikkalasi marf'", "Ikkalasi mansub", "Ikkalasi majzum", "Biri marf', biri mansub"],
        togri: 2,
        izoh: "Shart (إِنْ) kelganda fe'l majzum bo'ladi: تَعْمَلْ va تَنْجَحْ ikkalasi majzum",
      },
    ],
  },
  {
    id: 10,
    nomi: "B2 — Lug'at va umumiy",
    daraja: "B2",
    tur: "umumiy",
    davomiylik: 20,
    rang: "#DC2626",
    icon: "🏆",
    savollar: [
      {
        id: 1,
        matn: "So'zni tarjima qiling.",
        arabcha: "الاِحْتِمَال",
        variantlar: ["Ehtimollik", "Muammo", "Muvaffaqiyat", "Natija"],
        togri: 0,
        izoh: "الاِحْتِمَال (al-ihtimal) — ehtimollik, mumkinlik",
      },
      {
        id: 2,
        matn: "So'zni tarjima qiling.",
        arabcha: "يَتَطَوَّرُ",
        variantlar: ["Tugatadi", "Rivojlanadi", "O'zgaradi", "Qolaveradi"],
        togri: 1,
        izoh: "يَتَطَوَّرُ (yatatawwaru) — rivojlanadi, takomillashadi (Vazn V)",
      },
      {
        id: 3,
        matn: "Gapni tarjima qiling.",
        arabcha: "صَارَ الطَّالِبُ مُعَلِّمًا",
        variantlar: ["Talaba o'qituvchi edi", "Talaba o'qituvchi bo'ldi", "Talaba o'qituvchimi?", "Talaba o'qituvchi emas"],
        togri: 1,
        izoh: "صَارَ = bo'ldi/aylandi — holatning o'zgarishi",
      },
      {
        id: 4,
        matn: "So'zning antonimini toping.",
        arabcha: "النَّجَاح",
        variantlar: ["التَّقَدُّم", "الْفَشَل", "الْعَمَل", "الْجُهْد"],
        togri: 1,
        izoh: "النَّجَاح (muvaffaqiyat) ↔ الْفَشَل (muvaffaqiyatsizlik)",
      },
      {
        id: 5,
        matn: "Bo'sh joyni to'ldiring: _____ اجْتَهَدْتَ، نَجَحْتَ",
        variantlar: ["لَوْ", "إِذَا", "إِنْ", "حِينَ"],
        togri: 2,
        izoh: "إِنْ تَجْتَهِدْ تَنْجَحْ — real shart uchun إِنْ + majzum",
      },
      {
        id: 6,
        matn: "So'zni tarjima qiling.",
        arabcha: "مُتَطَوِّر",
        variantlar: ["Eski", "Rivojlangan", "Katta", "Murakkab"],
        togri: 1,
        izoh: "مُتَطَوِّر (mutatatawwir) — rivojlangan, zamonaviy (Vazn V ism fa'il)",
      },
      {
        id: 7,
        matn: "Gapni tarjima qiling.",
        arabcha: "لَمْ يَكُنِ الطَّقْسُ بَارِدًا أَمْسِ",
        variantlar: ["Bugun havo sovuq emas", "Kecha havo sovuq emas edi", "Havo hech qachon sovuq bo'lmaydi", "Kecha havo sovuq bo'ladi"],
        togri: 1,
        izoh: "لَمْ يَكُنْ — o'tgan zamon inkori; أَمْسِ = kecha",
      },
      {
        id: 8,
        matn: "So'zni tarjima qiling.",
        arabcha: "التَّعَاوُن",
        variantlar: ["Musobaqa", "Hamkorlik", "Bahs", "Muvaffaqiyat"],
        togri: 1,
        izoh: "التَّعَاوُن (at-ta'awun) — hamkorlik, birgalikda ishlash (Vazn VI masdar)",
      },
      {
        id: 9,
        matn: "Qaysi jumla to'g'ri tuzilgan?",
        variantlar: [
          "كَانَ الْجَوُّ جَمِيلٌ",
          "كَانَ الْجَوُّ جَمِيلًا",
          "كَانَ الْجَوَّ جَمِيلًا",
          "كَانَتِ الْجَوُّ جَمِيلًا",
        ],
        togri: 1,
        izoh: "كَانَ + ism marf' + xabar mansub: كَانَ الْجَوُّ جَمِيلًا",
      },
      {
        id: 10,
        matn: "So'zni tarjima qiling.",
        arabcha: "اسْتَفَادَ",
        variantlar: ["Foyda berdi", "Foyda oldi/foydalandi", "Qaytdi", "Ketdi"],
        togri: 1,
        izoh: "اسْتَفَادَ (istafada) — foyda oldi, unumli foydalandi (Vazn X)",
      },
    ],
  },
  {
    id: 11,
    nomi: "C1 — Grammatika testi",
    daraja: "C1",
    tur: "grammatika",
    davomiylik: 25,
    rang: "#0E7490",
    icon: "🔄",
    savollar: [
      {
        id: 1,
        matn: "كَتَبَ ning o'tgan zamon passiv shakli qaysi?",
        variantlar: ["كَتِبَ", "كُتِبَ", "كُتِّبَ", "أُكْتِبَ"],
        togri: 1,
        izoh: "O'tgan zamon passivi: birinchi harf damma, ikkinchi kasra → كُتِبَ",
      },
      {
        id: 2,
        matn: "يُكْتَبُ so'zi qaysi zamonning passivi?",
        variantlar: ["O'tgan zamon", "Hozirgi/kelasi zamon", "Buyruq mayli", "Inkor"],
        togri: 1,
        izoh: "يُفْعَلُ shakli — hozirgi/kelasi zamon passivi",
      },
      {
        id: 3,
        matn: "فُتِحَتِ الشَّبَابِيكُ gapida نَائِبُ الْفَاعِل qaysi?",
        variantlar: ["فُتِحَتِ", "الشَّبَابِيكُ", "Birinchi so'z", "Ikkinchi so'z va uchinchi so'z"],
        togri: 1,
        izoh: "الشَّبَابِيكُ — passiv gapda noyib fa'il, marf' holatda",
      },
      {
        id: 4,
        matn: "الطَّالِبُ الَّذِي نَجَحَ فَرِحَ gapida الَّذِي ning vazifasi nima?",
        variantlar: ["Inkor yuklamasi", "Nisbiy olmosh (aniqlovchi)", "Shart yuklamasi", "Ta'kid vositasi"],
        togri: 1,
        izoh: "الَّذِي — muzakkar birlik nisbiy olmoshi, الطَّالِبُ ni aniqlovchi jumla bilan bog'laydi",
      },
      {
        id: 5,
        matn: "الَّتِي olmoshi qaysi ot uchun ishlatiladi?",
        variantlar: ["Muzakkar birlik", "Muannash birlik", "Muzakkar ko'plik", "Muannash ko'plik"],
        togri: 1,
        izoh: "الَّتِي — muannash birlik nisbiy olmoshi",
      },
      {
        id: 6,
        matn: "جَلَسَ الطَّالِبُ وَهُوَ يَقْرَأُ gapida وَهُوَ يَقْرَأُ qanday jumla?",
        variantlar: ["Asosiy jumla", "Hal jumlasi", "Nisbiy jumla", "Shart jumlasi"],
        togri: 1,
        izoh: "وَهُوَ يَقْرَأُ — hal jumlasi: asosiy harakat paytidagi holatni bildiradi",
      },
      {
        id: 7,
        matn: "مَا أَجْمَلَ الطَّبِيعَةَ gapida qanday balaghat san'ati?",
        variantlar: ["Passiv nisbat", "Nisbiy jumla", "Taajjub I vazni", "Mubalacha"],
        togri: 2,
        izoh: "مَا أَفْعَلَ + maf'ul — taajjub I vazni: 'qanchalik go'zal!'",
      },
      {
        id: 8,
        matn: "صَبُور so'zi qaysi mubalacha og'iri va ma'nosi nima?",
        variantlar: ["فَعَّال — ko'p qiladigan", "فَعُول — kuchli xususiyat", "فَعِيل — sifat", "مِفْعَال — tabiiy"],
        togri: 1,
        izoh: "صَبُور — فَعُول og'iri: 'juda sabr qiluvchi' (sabr ko'p bo'lgan kishi)",
      },
      {
        id: 9,
        matn: "أَجْمِلْ بِالْمَدِينَةِ gapining ma'nosi nima?",
        variantlar: ["Shaharni go'zallash", "Shahar go'zal", "Shahar qanchalik go'zal!", "Go'zal shahar"],
        togri: 2,
        izoh: "أَفْعِلْ بِـ — taajjub II vazni: 'qanchalik go'zal!'",
      },
      {
        id: 10,
        matn: "يُدَرَّسُ الْعِلْمُ فِي الْجَامِعَةِ gapida qaysi vazn passivi?",
        variantlar: ["Vazn I", "Vazn II", "Vazn IV", "Vazn X"],
        togri: 1,
        izoh: "يُدَرَّسُ — Vazn II (دَرَّسَ) ning hozirgi zamon passivi",
      },
    ],
  },
  {
    id: 12,
    nomi: "C1 — Umumiy test",
    daraja: "C1",
    tur: "umumiy",
    davomiylik: 25,
    rang: "#7C3AED",
    icon: "🔍",
    savollar: [
      {
        id: 1,
        matn: "Gapni tarjima qiling.",
        arabcha: "كُتِبَ التَّقْرِيرُ أَمْسِ",
        variantlar: ["Hisobot kecha yoziladi", "Hisobot kecha yozildi", "Hisobotni kecha yozing", "Hisobot yozilmadi"],
        togri: 1,
        izoh: "كُتِبَ — o'tgan zamon passivi; أَمْسِ = kecha",
      },
      {
        id: 2,
        matn: "So'zni tarjima qiling.",
        arabcha: "يُسْتَخْدَمُ",
        variantlar: ["Ishlatadi", "Ishlatiladi", "Ishlatdi", "Ishlatildi"],
        togri: 1,
        izoh: "يُسْتَخْدَمُ — Vazn X hozirgi zamon passivi: 'ishlatiladi'",
      },
      {
        id: 3,
        matn: "Qaysi jumla to'g'ri?",
        variantlar: [
          "رَأَيْتُ الطَّالِبَ الَّتِي نَجَحَ",
          "رَأَيْتُ الطَّالِبَ الَّذِي نَجَحَ",
          "رَأَيْتُ الطَّالِبَ مَنْ نَجَحَ",
          "رَأَيْتُ الطَّالِبَ الَّذِينَ نَجَحَ",
        ],
        togri: 1,
        izoh: "الطَّالِب muzakkar birlik → الَّذِي nisbiy olmoshi ishlatiladi",
      },
      {
        id: 4,
        matn: "مَنْ يَجْتَهِدْ يَنْجَحْ gapining ma'nosi nima?",
        variantlar: ["Tirishqoq kim?", "Tirishib ishlagan kishi o'tadi", "Tirishib ishlading, o'tding", "Tirishib ishla!"],
        togri: 1,
        izoh: "مَنْ = kim (nisbiy); Tirishib ishlaydigan kishi muvaffaqiyatga erishadi",
      },
      {
        id: 5,
        matn: "So'zni tarjima qiling.",
        arabcha: "مُجْتَهِد",
        variantlar: ["Dangasa", "G'ayratli/tirishqoq", "Aqlli", "Tez"],
        togri: 1,
        izoh: "مُجْتَهِد (mujtahid) — tirishqoq, g'ayratli (Vazn VIII ism fa'il)",
      },
      {
        id: 6,
        matn: "مَا أَسْرَعَ الْقِطَارَ gapida taajjub nimaga oid?",
        variantlar: ["Poyezdning uzunligi", "Poyezdning tezligi", "Poyezdning rangi", "Poyezdning narxi"],
        togri: 1,
        izoh: "أَسْرَعَ ← سَرِيع (tez) — tezlik haqida taajjub",
      },
      {
        id: 7,
        matn: "Hal jumlasini aniqlang.",
        variantlar: [
          "جَاءَ الطَّالِبُ",
          "الطَّالِبُ مُجْتَهِدٌ",
          "جَاءَ الطَّالِبُ وَهُوَ يَبْتَسِمُ",
          "الطَّالِبُ الَّذِي جَاءَ",
        ],
        togri: 2,
        izoh: "وَهُوَ يَبْتَسِمُ — hal jumlasi: kelish paytidagi holat",
      },
      {
        id: 8,
        matn: "So'zni tarjima qiling.",
        arabcha: "مَشْهُور",
        variantlar: ["Noma'lum", "Mashhur", "Eski", "Yangi"],
        togri: 1,
        izoh: "مَشْهُور (mashhur) — taniqli, mashhur (شَهَرَ dan ism maf'ul)",
      },
      {
        id: 9,
        matn: "Gapni tarjima qiling.",
        arabcha: "يُبْنَى الْجِسْرُ الْجَدِيدُ الآنَ",
        variantlar: ["Yangi ko'prik qurildi", "Yangi ko'prik hozir qurilmoqda", "Yangi ko'prikni qurang", "Yangi ko'prik quriladi ertaga"],
        togri: 1,
        izoh: "يُبْنَى — hozirgi passiv; الآنَ = hozir",
      },
      {
        id: 10,
        matn: "كَذَّاب so'zi qaysi mubalacha og'iri?",
        variantlar: ["فَعُول", "فَعِيل", "فَعَّال", "مِفْعَال"],
        togri: 2,
        izoh: "كَذَّاب — فَعَّال og'iri: ko'p yolg'on gapiradigan (كَذَبَ dan)",
      },
    ],
  },
  {
    id: 13,
    nomi: "C2 — Balaghat va grammatika",
    daraja: "C2",
    tur: "grammatika",
    davomiylik: 30,
    rang: "#CA8A04",
    icon: "✍️",
    savollar: [
      {
        id: 1,
        matn: "الْعِلْمُ كَالنُّورِ gapidagi balaghat san'ati nima?",
        variantlar: ["Isti'ora", "Tashabuh", "Kinoya", "Ta'kid"],
        togri: 1,
        izoh: "Mushabbah (الْعِلْم) + adatu t-tashabuh (كَـ) + mushabbah bihi (النُّور) — tashabuh",
      },
      {
        id: 2,
        matn: "رَأَيْتُ أَسَدًا يَخْطُبُ gapida qanday balaghat ishlatilgan?",
        variantlar: ["Tashabuh", "Isti'ora", "Kinoya", "Mubalacha"],
        togri: 1,
        izoh: "Isti'ora — o'xshatish vositasisiz: sher o'rnida jasur kishi nazarda tutilgan",
      },
      {
        id: 3,
        matn: "هُوَ طَوِيلُ الْيَدِ iborasining majoziy ma'nosi nima?",
        variantlar: ["Qo'li uzun (jismoniy)", "Saxiy yoki o'g'ri (kinoya)", "Kuchli", "Ishchan"],
        togri: 1,
        izoh: "طَوِيلُ الْيَدِ — kinoya: qo'lning uzunligi → saxiylik yoki o'g'rilik",
      },
      {
        id: 4,
        matn: "إِنَّ الْعَمَلَ مُفِيدٌ gapida إِنَّ ning vazifasi nima?",
        variantlar: ["Savol berish", "Inkor qilish", "Ta'kid (kuchaytirish)", "O'xshatish"],
        togri: 2,
        izoh: "إِنَّ — ta'kid vositasi: ism mansub, xabar marf' bo'ladi",
      },
      {
        id: 5,
        matn: "لَقَدْ أَثْبَتَ الطُّلَّابُ كَفَاءَتَهُمْ gapida ta'kid vositasi qaysi?",
        variantlar: ["أَثْبَتَ", "الطُّلَّابُ", "لَقَدْ", "كَفَاءَتَهُمْ"],
        togri: 2,
        izoh: "لَقَدْ = لَـ + قَدْ — ikki ta'kid birlashgan: 'haqiqatan, albatta'",
      },
      {
        id: 6,
        matn: "I'tirod jumlasi qaysi gapda to'g'ri ishlatilgan?",
        variantlar: [
          "مُحَمَّدٌ — وَهُوَ مُعَلِّمٌ — نَجَحَ",
          "مُحَمَّدٌ نَجَحَ وَهُوَ مُعَلِّمٌ",
          "مُحَمَّدٌ مُعَلِّمٌ نَجَحَ",
          "نَجَحَ مُحَمَّدٌ الْمُعَلِّمُ",
        ],
        togri: 0,
        izoh: "I'tirod jumlasi tire (-) bilan asosiy gap ichiga kiritiladi",
      },
      {
        id: 7,
        matn: "قَدْ o'tgan zamon fe'li oldidan kelganda qanday ma'no beradi?",
        variantlar: ["Inkor", "Kelasi zamon", "Tasdiqlash/ta'kid", "Hayrat"],
        togri: 2,
        izoh: "قَدْ + o'tgan zamon = tasdiqlash: قَدْ فَهِمْتُ = tushundim (albatta)",
      },
      {
        id: 8,
        matn: "Tashabuh tarkibini belgilang.",
        arabcha: "كَأَنَّ النُّجُومَ دُرَرٌ",
        variantlar: [
          "Mushabbah: النُّجُوم, Adatu t-tashabuh: كَأَنَّ, Mushabbah bihi: دُرَر",
          "Mushabbah: دُرَر, Adatu t-tashabuh: كَأَنَّ, Mushabbah bihi: النُّجُوم",
          "Mushabbah: كَأَنَّ, Mushabbah bihi: النُّجُوم",
          "Faqat mushabbah va mushabbah bihi",
        ],
        togri: 0,
        izoh: "Yulduzlar (النُّجُوم) — o'xshatiladigan; كَأَنَّ — vosita; marvaridlar (دُرَر) — o'xshash",
      },
      {
        id: 9,
        matn: "Kinoya va isti'orani farqlovchi asosiy xususiyat nima?",
        variantlar: [
          "Kinoyada o'xshatish vositasi bor, isti'orada yo'q",
          "Kinoyada bilvosita ma'no, isti'orada narsa o'rniga boshqa narsa ishlatiladi",
          "Ikkalasi bir xil",
          "Isti'orada haqiqiy ma'no, kinoyada ko'chma",
        ],
        togri: 1,
        izoh: "Kinoya — belgi orqali bilvosita; Isti'ora — narsa o'rniga o'xshash narsa (vositasiz)",
      },
      {
        id: 10,
        matn: "إِنَّكَ لَمُجْتَهِدٌ gapida nechta ta'kid vositasi bor?",
        variantlar: ["Bitta (إِنَّ)", "Ikkita (إِنَّ va لَـ)", "Uchta", "Hech biri"],
        togri: 1,
        izoh: "إِنَّ va لَـ — ikki ta'kid vositasi birgalikda ishlatilgan",
      },
    ],
  },
  {
    id: 14,
    nomi: "C2 — Matn va professional",
    daraja: "C2",
    tur: "umumiy",
    davomiylik: 30,
    rang: "#059669",
    icon: "📜",
    savollar: [
      {
        id: 1,
        matn: "Akademik arabcha matnning tuzilmasini to'g'ri tartibda belgilang.",
        variantlar: [
          "Xotima — tanasi — kirish",
          "Kirish (muqaddima) — asosiy qism — xotima",
          "Asosiy qism — kirish — xotima",
          "Xotima — kirish — asosiy qism",
        ],
        togri: 1,
        izoh: "Muqaddima → Sulbu l-mawdu' → Khatima — standart akademik tuzilma",
      },
      {
        id: 2,
        matn: "وَبِالتَّالِي bog'lovchisi qanday ma'no beradi?",
        variantlar: ["Birinchidan", "Garchi... bo'lsa ham", "Binobarin/shuning uchun", "Bundan tashqari"],
        togri: 2,
        izoh: "وَبِالتَّالِي — natija/xulosa bildiradi: 'binobarin, shuning uchun'",
      },
      {
        id: 3,
        matn: "So'zni tarjima qiling.",
        arabcha: "يُلَاحَظُ أَنَّ",
        variantlar: ["E'lon qilinadi ki", "Kuzatiladi ki", "So'raladi ki", "Tavsiya etiladi ki"],
        togri: 1,
        izoh: "يُلَاحَظُ — 'kuzatiladi' (passiv), ilmiy matnda ob'ektiv ton uchun",
      },
      {
        id: 4,
        matn: "عَلَى الرَّغْمِ مِنْ iborasi qanday bog'lovchi?",
        variantlar: ["Natija bildiradi", "Qarama-qarshilik bildiradi", "Tartib bildiradi", "Qo'shimcha ma'lumot"],
        togri: 1,
        izoh: "عَلَى الرَّغْمِ مِنْ — 'garchi... bo'lsa ham' — qarama-qarshilik/ziddiyat",
      },
      {
        id: 5,
        matn: "Ilmiy arabcha matnda passiv nisbat ko'p ishlatilishining sababi nima?",
        variantlar: ["Oson yozish uchun", "Ob'ektiv, shaxssiz ton berish uchun", "Qisqalik uchun", "Taajjub ifodalash uchun"],
        togri: 1,
        izoh: "Ilmiy uslubda ob'ektiv ton uchun passiv afzal: يُلَاحَظُ, يُعَرَّفُ kabi",
      },
      {
        id: 6,
        matn: "فِي ضَوْءِ مَا سَبَقَ iborasi qaysi qismni kiritadi?",
        variantlar: ["Kirish qismini", "Xulosa qismini", "Yangi mavzuni", "Savol qismini"],
        togri: 1,
        izoh: "فِي ضَوْءِ مَا سَبَقَ — 'yuqorida aytilganlar asosida' — xulosa kirish iborasi",
      },
      {
        id: 7,
        matn: "So'zni tarjima qiling.",
        arabcha: "الْمَرَاجِع",
        variantlar: ["Kirish qism", "Asosiy g'oyalar", "Manbalar/adabiyotlar ro'yxati", "Xulosa"],
        togri: 2,
        izoh: "الْمَرَاجِع (al-maraji') — manbalar, foydalanilgan adabiyotlar ro'yxati",
      },
      {
        id: 8,
        matn: "فَضْلًا عَنْ ذَلِكَ iborasi qanday ma'no beradi?",
        variantlar: ["Shuning uchun", "Bundan tashqari/qo'shimcha", "Xulosa qilib", "Birinchidan"],
        togri: 1,
        izoh: "فَضْلًا عَنْ ذَلِكَ — 'bundan tashqari' — qo'shimcha ma'lumot kiritadi",
      },
      {
        id: 9,
        matn: "Gapni tarjima qiling.",
        arabcha: "تُشِيرُ الدِّرَاسَاتُ إِلَى أَنَّ الْقِرَاءَةَ تُطَوِّرُ الْعَقْلَ",
        variantlar: [
          "Tadqiqotlar o'qishni rivojlantiradi",
          "Tadqiqotlar ko'rsatadi ki, o'qish aqlni rivojlantiradi",
          "O'qish aqlni rivojlantiradi, tadqiqotlar aytadi",
          "Tadqiqotlar va o'qish aqlni rivojlantiradi",
        ],
        togri: 1,
        izoh: "تُشِيرُ إِلَى أَنَّ = 'ko'rsatadi ki' — ilmiy ibora",
      },
      {
        id: 10,
        matn: "أَوَّلًا, ثَانِيًا, ثَالِثًا bog'lovchilari qanday ma'no beradi?",
        variantlar: ["Qarama-qarshilik", "Natija", "Tartib (birinchidan, ikkinchidan...)", "Qo'shimcha"],
        togri: 2,
        izoh: "أَوَّلًا/ثَانِيًا/ثَالِثًا — tartib bildiradi: birinchidan, ikkinchidan, uchinchidan",
      },
    ],
  },
  // ─── Attanal fonetika uslubi ─────────────────────────────────────────────────
  {
    id: 9,
    nomi: "Attanal — Fonetika testi",
    daraja: "A2",
    tur: "talaffuz",
    davomiylik: 15,
    rang: "#DC2626",
    icon: "🎙️",
    savollar: [
      {
        id: 1,
        matn: "«ص» harfining sifati qaysi?",
        variantlar: ["Jahriy va qattiq", "Mahmuziy va yumshoq", "Mahmuziy, yumshoq, qalin", "Jahriy va yumshoq"],
        togri: 2,
        izoh: "ص — Mahmuziy (hams), yumshoq (raxwa), qalin (isti'lo) — fonetika terminlari",
      },
      {
        id: 2,
        matn: "«ب» harfi qaysi sifatga ega?",
        variantlar: ["Hams va raxwa", "Jahr va shidda", "Jahr va raxwa", "Hams va shidda"],
        togri: 1,
        izoh: "ب — jahriy (jahr) va qattiq (shidda) harfidir",
      },
      {
        id: 3,
        matn: "Shamsiy harflar nima?",
        arabcha: "اَلشَّمْسِيَّة",
        variantlar: [
          "Al bilan kelganda lam aniq o'qiladigan harflar",
          "Al bilan kelganda lam idg'om bo'ladigan harflar",
          "Faqat labdan chiqadigan harflar",
          "Doim qattiq o'qiladigan harflar",
        ],
        togri: 1,
        izoh: "Shamsiy — ش,س,ص... kabi harflar: al kelganda ل ular ichiga singadi: الشَّمس",
      },
      {
        id: 4,
        matn: "Qamariy harflar nima?",
        arabcha: "اَلْقَمَرِيَّة",
        variantlar: [
          "Al bilan kelganda lam idg'om bo'ladigan harflar",
          "Al bilan kelganda lam aniq o'qiladigan harflar",
          "Faqat tildan chiqadigan harflar",
          "Doim yumshoq o'qiladigan harflar",
        ],
        togri: 1,
        izoh: "Qamariy — ب,ك,ق... kabi harflar: al kelganda ل aniq o'qiladi: الْكِتَاب",
      },
      {
        id: 5,
        matn: "«مَدّ طَبِيعِي» (tabiiy madd) necha harakat davom etadi?",
        variantlar: ["1 harakat", "2 harakat", "4 harakat", "6 harakat"],
        togri: 1,
        izoh: "Madd tabiiy — 2 harakat davom etadi (to'siq yoki hamza bo'lmasa)",
      },
      {
        id: 6,
        matn: "Ikhfa' nima?",
        arabcha: "الإِخْفَاء",
        variantlar: [
          "Nun sakinni aniq o'qish",
          "Nun sakinni mim'ga aylantirish",
          "Nun sakinni keyingi harfga singdirish",
          "Nun sakinni yashirib, o'rta holat bilan o'qish",
        ],
        togri: 3,
        izoh: "Ikhfa' — nun sakin + 15 ta ikhfa' harfidan biri: yashirilgan holda o'qiladi",
      },
      {
        id: 7,
        matn: "«غُنَّة» (gunna) nima?",
        variantlar: [
          "Og'iz bo'shlig'i tovushi",
          "Tomoqdan chiqadigan tovush",
          "Burundan chiqadigan tovush",
          "Labdan chiqadigan tovush",
        ],
        togri: 2,
        izoh: "Gunna — burundan chiqadigan tovush, mim va nun'da bo'ladi",
      },
      {
        id: 8,
        matn: "Qaysi harf o'zida gunna sifatini doim saqlaydi?",
        variantlar: ["ب", "ن", "و", "ي"],
        togri: 1,
        izoh: "ن (nun) harfi har doim gunna sifatiga ega",
      },
      {
        id: 9,
        matn: "«الإِدْغَام» (idg'om) bo'limida harf qanday o'qiladi?",
        variantlar: [
          "Ikkita harf aniq, alohida o'qiladi",
          "Birinchi harf ikkinchisiga singib ketadi",
          "Ikkinchi harf birinchisiga singib ketadi",
          "Ikkala harf ham o'chirilib ketadi",
        ],
        togri: 1,
        izoh: "Idg'om — birinchi harf (nun sakin/tanvin) keyingi harfga singadi, tashdid bilan o'qiladi",
      },
      {
        id: 10,
        matn: "Quyidagi harflardan qaysi biri «حُرُوف الاسْتِعْلَاء» (qalin harflar) guruhiga kiradi?",
        variantlar: ["ب", "خ", "ن", "م"],
        togri: 1,
        izoh: "خ — Isti'lo harflari: خ,ص,ض,ط,ظ,غ,ق — til ko'tarilib o'qiladi (qalin tovush)",
      },
    ],
  },
  // ─── CEFR Reading Comprehension ──────────────────────────────────────────────
  {
    id: 10,
    nomi: "CEFR B1 — Matn tushunish",
    daraja: "B1",
    tur: "umumiy",
    davomiylik: 20,
    rang: "#CA8A04",
    icon: "📖",
    savollar: [
      {
        id: 1,
        matn: "Matnni o'qing va savolga javob bering:\nذَهَبَ أَحْمَدُ إِلَى الْمَكْتَبَةِ لِيَقْرَأَ كِتَابًا. وَجَدَ كِتَابًا مُفِيدًا عَنِ التَّارِيخِ فَأَخَذَهُ وَجَلَسَ يَقْرَأُ.\n\nAhmad qayerga bordi?",
        variantlar: ["Maktabga", "Bozorga", "Kutubxonaga", "Kasalxonaga"],
        togri: 2,
        izoh: "الْمَكْتَبَة — kutubxona (al-maktaba)",
      },
      {
        id: 2,
        matn: "Xuddi shu matn. Ahmad nima qildi?",
        arabcha: "أَخَذَهُ وَجَلَسَ يَقْرَأُ",
        variantlar: [
          "Kitobni sotib oldi",
          "Kitobni olib o'qishga o'tirdi",
          "Kitobni qaytarib qo'ydi",
          "Kitobni do'stiga berdi",
        ],
        togri: 1,
        izoh: "أَخَذَهُ = uni oldi | جَلَسَ يَقْرَأُ = o'qib o'tirdi",
      },
      {
        id: 3,
        matn: "Bo'sh joyni to'ldiring: أَنَا ___ مِنَ الأُزْبَكِسْتَان",
        variantlar: ["ذَهَبَ", "قَادِم", "كَتَبَ", "يَجْلِس"],
        togri: 1,
        izoh: "قَادِم — kelyapman / kelganman (hall ism sifati) — Men O'zbekistondan kelganman",
      },
      {
        id: 4,
        matn: "Qaysi gap to'g'ri tarjima qilingan?\nالطُّلَّابُ يَدْرُسُونَ فِي الْجَامِعَةِ",
        variantlar: [
          "Talabalar maktabda o'qiydi",
          "Talabalar universitetda o'qiydi",
          "O'quvchilar kutubxonada o'qiydi",
          "Muallimlar universitetda ishlamoqda",
        ],
        togri: 1,
        izoh: "طُلَّاب = talabalar | جَامِعَة = universitet | يَدْرُسُونَ = o'qiydilar",
      },
      {
        id: 5,
        matn: "«لَيْسَ» so'zi nimani bildiradi?",
        variantlar: ["Bor, mavjud", "Yo'q, emas", "Katta, buyuk", "Ketdi, yo'q bo'ldi"],
        togri: 1,
        izoh: "لَيْسَ — inkor fe'li: 'emas', 'yo'q' (ism jumlasini inkor qiladi)",
      },
      {
        id: 6,
        matn: "Bo'sh joyni to'ldiring:\nالْكِتَابُ عَلَى ___ الْمَكْتَب",
        variantlar: ["فِي", "مِنْ", "فَوْقَ", "إِلَى"],
        togri: 2,
        izoh: "عَلَى = ustida / فَوْقَ = tepasida — ikkalasi ham to'g'ri, lekin عَلَى ko'proq ishlatiladi",
      },
      {
        id: 7,
        matn: "Qaysi so'z «talaba» ma'nosida?",
        variantlar: ["مُدَرِّس", "طَالِب", "طَبِيب", "مُهَنْدِس"],
        togri: 1,
        izoh: "طَالِب — talaba | مُدَرِّس — muallim | طَبِيب — shifokor | مُهَنْدِس — muhandis",
      },
      {
        id: 8,
        matn: "Matnni o'qing:\nتَعَلَّمَ مُحَمَّدٌ اللُّغَةَ الْعَرَبِيَّةَ لِمُدَّةِ سَنَتَيْنِ فَأَصْبَحَ يَتَكَلَّمُ بِطَلَاقَة.\n\nMuhammad arabchani necha yil o'rgandi?",
        variantlar: ["1 yil", "2 yil", "3 yil", "5 yil"],
        togri: 1,
        izoh: "سَنَتَيْنِ — ikki yil (musonno shakli)",
      },
      {
        id: 9,
        matn: "«فَأَصْبَحَ» iborasi qanday ma'no beradi?",
        arabcha: "فَأَصْبَحَ يَتَكَلَّمُ بِطَلَاقَة",
        variantlar: [
          "Keyin uxlab qoldi",
          "Natijada ravon gapira boshladi",
          "Ertalab uyg'ondi",
          "Lekin gapira olmadi",
        ],
        togri: 1,
        izoh: "فَأَصْبَحَ = natijada bo'ldi | يَتَكَلَّمُ بِطَلَاقَة = ravon gapiradi",
      },
      {
        id: 10,
        matn: "Quyidagi jumlada xato topilgan o'rinni aniqlang:\nالطَّالِبَةُ ذَهَبَ إِلَى الْمَدْرَسَة",
        variantlar: [
          "الطَّالِبَةُ so'zi xato",
          "ذَهَبَ xato (ذَهَبَتْ bo'lishi kerak)",
          "إِلَى to'g'ri emas",
          "الْمَدْرَسَة xato",
        ],
        togri: 1,
        izoh: "الطَّالِبَةُ — ayol o'quvchi: uning fe'li ذَهَبَتْ bo'lishi kerak",
      },
    ],
  },
];
