export interface MockSavol {
  id: number;
  matn: string;
  arabcha?: string; // arabcha matn bo'lsa
  variantlar: string[];
  togri: number; // 0-based index
  izoh?: string; // nima uchun bu javob to'g'ri
}

export interface MockTest {
  id: number;
  nomi: string;
  daraja: "A0" | "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  tur: "alifbo" | "lug'at" | "grammatika" | "talaffuz" | "umumiy";
  davomiylik: number; // daqiqalarda
  savollar: MockSavol[];
  rang: string;
  icon: string;
}

export const MOCK_TESTLAR: MockTest[] = [
  {
    id: 1,
    nomi: "A0 — Alifbo testi",
    daraja: "A0",
    tur: "alifbo",
    davomiylik: 10,
    rang: "#0891B2",
    icon: "✏️",
    savollar: [
      {
        id: 1,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ب",
        variantlar: ["ba", "ta", "sa", "pa"],
        togri: 0,
        izoh: "ب — Ba, arabchaning ikkinchi harfi",
      },
      {
        id: 2,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ت",
        variantlar: ["ba", "ta", "jim", "xo"],
        togri: 1,
        izoh: "ت — Ta, arabchaning uchinchi harfi",
      },
      {
        id: 3,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ج",
        variantlar: ["ha", "xo", "jim", "ta"],
        togri: 2,
        izoh: "ج — Jim, arabchaning beshinchi harfi",
      },
      {
        id: 4,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ر",
        variantlar: ["ro", "zayn", "sin", "shin"],
        togri: 0,
        izoh: "ر — Ro, arabchaning o'n birinchi harfi",
      },
      {
        id: 5,
        matn: "'Alif' harfining arabcha yozilishi qaysi?",
        arabcha: undefined,
        variantlar: ["ع", "أ", "ا", "إ"],
        togri: 2,
        izoh: "ا — Alif, arabchaning birinchi harfi (hamzasiz shakli)",
      },
      {
        id: 6,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌َ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Sukun"],
        togri: 2,
        izoh: "Fatha — undosh ustiga yoziladi, 'a' ovozini beradi",
      },
      {
        id: 7,
        matn: "Bu qaysi harakat belgisi?",
        arabcha: "◌ِ",
        variantlar: ["Kasra", "Zamma", "Fatha", "Tanvin"],
        togri: 0,
        izoh: "Kasra — undosh ostiga yoziladi, 'i' ovozini beradi",
      },
      {
        id: 8,
        matn: "Arabcha alifboda nechta harf bor?",
        arabcha: undefined,
        variantlar: ["26", "28", "30", "24"],
        togri: 1,
        izoh: "Arab alifbosida 28 ta harf mavjud",
      },
      {
        id: 9,
        matn: "Bu harf qanday o'qiladi?",
        arabcha: "ع",
        variantlar: ["ayn", "g'ayn", "fa", "qof"],
        togri: 0,
        izoh: "ع — Ayn, arabchaning o'n sakkizinchi harfi",
      },
      {
        id: 10,
        matn: "Arabcha qaysi yo'nalishda o'qiladi?",
        arabcha: undefined,
        variantlar: ["Chapdan o'ngga", "O'ngdan chapga", "Yuqoridan pastga", "Pastdan yuqoriga"],
        togri: 1,
        izoh: "Arabcha o'ngdan chapga yoziladi va o'qiladi",
      },
    ],
  },
  {
    id: 2,
    nomi: "A1 — Lug'at testi",
    daraja: "A1",
    tur: "lug'at",
    davomiylik: 15,
    rang: "#2563EB",
    icon: "📝",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "بَيْت",
        variantlar: ["Maktab", "Uy", "Mashina", "Kitob"],
        togri: 1,
        izoh: "بَيْت (bayt) — uy",
      },
      {
        id: 2,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مُدَرِّس",
        variantlar: ["O'quvchi", "Kitob", "O'qituvchi", "Qalam"],
        togri: 2,
        izoh: "مُدَرِّس (mudarris) — o'qituvchi",
      },
      {
        id: 3,
        matn: "'Kitob' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["قَلَم", "كِتَاب", "مَدْرَسَة", "سَيَّارَة"],
        togri: 1,
        izoh: "كِتَاب (kitaab) — kitob",
      },
      {
        id: 4,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "سَيَّارَة",
        variantlar: ["Samolyot", "Mashina", "Velosiped", "Qayiq"],
        togri: 1,
        izoh: "سَيَّارَة (sayyaara) — mashina",
      },
      {
        id: 5,
        matn: "'Maktab' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["بَيْت", "مَدْرَسَة", "مَكْتَب", "مَسْجِد"],
        togri: 1,
        izoh: "مَدْرَسَة (madrasa) — maktab",
      },
      {
        id: 6,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "مَاء",
        variantlar: ["Non", "Suv", "Choy", "Sharbat"],
        togri: 1,
        izoh: "مَاء (maa') — suv",
      },
      {
        id: 7,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "يَوْم",
        variantlar: ["Hafta", "Oy", "Kun", "Yil"],
        togri: 2,
        izoh: "يَوْم (yawm) — kun",
      },
      {
        id: 8,
        matn: "'Ota' so'zi arabchada qanday yoziladi?",
        arabcha: undefined,
        variantlar: ["أُم", "أَخ", "أَب", "اِبْن"],
        togri: 2,
        izoh: "أَب (ab) — ota",
      },
      {
        id: 9,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "طَالِب",
        variantlar: ["O'qituvchi", "Direktor", "O'quvchi", "Shifokor"],
        togri: 2,
        izoh: "طَالِب (toolib) — o'quvchi",
      },
      {
        id: 10,
        matn: "Quyidagi so'zning tarjimasi nima?",
        arabcha: "شَمْس",
        variantlar: ["Oy (samoviy jism)", "Yulduz", "Quyosh", "Bulut"],
        togri: 2,
        izoh: "شَمْس (shams) — quyosh",
      },
    ],
  },
  {
    id: 3,
    nomi: "A1 — Grammatika testi",
    daraja: "A1",
    tur: "grammatika",
    davomiylik: 15,
    rang: "#059669",
    icon: "📐",
    savollar: [
      {
        id: 1,
        matn: "'U (erkak)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنَا", "أَنْتَ", "هُوَ", "هِيَ"],
        togri: 2,
        izoh: "هُوَ (huwa) — u (erkak)",
      },
      {
        id: 2,
        matn: "'Biz' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["أَنْتُمْ", "نَحْنُ", "هُمْ", "أَنْتَ"],
        togri: 1,
        izoh: "نَحْنُ (nahnu) — biz",
      },
      {
        id: 3,
        matn: "Quyidagi so'z qaysi jinsda?",
        arabcha: "مُعَلِّمَة",
        variantlar: ["Muzakkar (erkak jins)", "Muannash (ayol jins)", "Ikkalasi ham", "Hech biri"],
        togri: 1,
        izoh: "مُعَلِّمَة — muallima (ayol o'qituvchi), -a (ta-marbuta) ayol jinsini bildiradi",
      },
      {
        id: 4,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "هَذَا",
        variantlar: ["U (uzoqdagi erkak)", "Bu (yaqindagi erkak)", "Bu (yaqindagi ayol)", "Ular"],
        togri: 1,
        izoh: "هَذَا (haza) — bu (yaqindagi erkak jins uchun)",
      },
      {
        id: 5,
        matn: "Qaysi so'z muzakkar (erkak jins)?",
        arabcha: undefined,
        variantlar: ["مُعَلِّمَة", "طَالِبَة", "مُدِير", "مُدِيرَة"],
        togri: 2,
        izoh: "مُدِير (mudiir) — direktor (erkak), boshqalarida -a qo'shimchasi bor",
      },
      {
        id: 6,
        matn: "'U (ayol)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُوَ", "أَنَا", "هِيَ", "أَنْتِ"],
        togri: 2,
        izoh: "هِيَ (hiya) — u (ayol)",
      },
      {
        id: 7,
        matn: "'Ular (erkaklar)' arabchada qanday aytiladi?",
        arabcha: undefined,
        variantlar: ["هُنَّ", "أَنْتُنَّ", "هُمْ", "نَحْنُ"],
        togri: 2,
        izoh: "هُمْ (hum) — ular (erkaklar yoki aralash guruh)",
      },
      {
        id: 8,
        matn: "Bu ishorali olmosh nimani bildiradi?",
        arabcha: "تِلْكَ",
        variantlar: ["Bu (yaqin, erkak)", "Bu (yaqin, ayol)", "U (uzoq, ayol)", "U (uzoq, erkak)"],
        togri: 2,
        izoh: "تِلْكَ (tilka) — u (uzoqdagi ayol jins uchun)",
      },
      {
        id: 9,
        matn: "Quyidagi so'z ko'plikda qanday bo'ladi?",
        arabcha: "كِتَاب",
        variantlar: ["كِتَابَات", "كُتُب", "كِتَابَان", "كِتَابَيْن"],
        togri: 1,
        izoh: "كُتُب (kutub) — kitoblar (ko'plik shakli)",
      },
      {
        id: 10,
        matn: "'Men o'quvchiman' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["أَنَا مُدَرِّس", "أَنَا طَالِب", "هُوَ طَالِب", "أَنْتَ طَالِب"],
        togri: 1,
        izoh: "أَنَا طَالِب (anaa toolib) — Men o'quvchiman",
      },
    ],
  },
  {
    id: 4,
    nomi: "A2 — Umumiy test",
    daraja: "A2",
    tur: "umumiy",
    davomiylik: 20,
    rang: "#CA8A04",
    icon: "🎯",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi fe'l o'tgan zamonda qanday o'qiladi?",
        arabcha: "ذَهَبَ",
        variantlar: ["zahaba (u bordi)", "yazhabu (u boradi)", "zahab (boring)", "layzhabu (u bormaydi)"],
        togri: 0,
        izoh: "ذَهَبَ (zahaba) — u bordi (erkak, o'tgan zamon)",
      },
      {
        id: 2,
        matn: "Quyidagi gapning tarjimasi nima?",
        arabcha: "أَنَا أَذْهَبُ إِلَى المَدْرَسَة",
        variantlar: ["Men maktabga bordim", "Men maktabga boraman", "U maktabga boradi", "Biz maktabga boramiz"],
        togri: 1,
        izoh: "أَذْهَبُ — hozirgi/kelasi zamon, birinchi shaxs (men boraman)",
      },
      {
        id: 3,
        matn: "Quyidagi savol so'zi nima degan ma'noni anglatadi?",
        arabcha: "مَتَى؟",
        variantlar: ["Qayerda?", "Nima?", "Qachon?", "Qanday?"],
        togri: 2,
        izoh: "مَتَى (mataa) — qachon?",
      },
      {
        id: 4,
        matn: "Quyidagi jumla to'g'ri tarjima qilinganmi?",
        arabcha: "البَيْتُ كَبِير",
        variantlar: ["Kichik uy", "Katta uy", "Yangi uy", "Eski uy"],
        togri: 1,
        izoh: "كَبِير (kabiir) — katta; البَيْتُ كَبِير — uy katta",
      },
      {
        id: 5,
        matn: "Arabchada 'Nima?' savol so'zi qaysi?",
        arabcha: undefined,
        variantlar: ["مَنْ", "أَيْنَ", "مَاذَا", "كَيْفَ"],
        togri: 2,
        izoh: "مَاذَا (maaza) — nima?, biror narsa haqida so'rash uchun",
      },
    ],
  },

  // ─── A2 Grammatika ──────────────────────────────────────────────────────────
  {
    id: 5,
    nomi: "A2 — Grammatika testi",
    daraja: "A2",
    tur: "grammatika",
    davomiylik: 20,
    rang: "#7C3AED",
    icon: "📐",
    savollar: [
      {
        id: 1,
        matn: "كَتَبَتْ so'zi qaysi shaxs va jinsda?",
        arabcha: "كَتَبَتْ",
        variantlar: ["1-shaxs erkak", "3-shaxs erkak", "3-shaxs ayol", "2-shaxs ayol"],
        togri: 2,
        izoh: "كَتَبَتْ — katabat: 3-shaxs yagona ayol, o'tgan zamon ('u yozdi' — ayol)",
      },
      {
        id: 2,
        matn: "'Biz yozdik' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["كَتَبُوا", "كَتَبْتُ", "كَتَبْنَا", "كَتَبَتْ"],
        togri: 2,
        izoh: "كَتَبْنَا (katabna) — biz yozdik (1-shaxs ko'plik)",
      },
      {
        id: 3,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "الْكِتَابُ عَلَى الطَّاوِلَةِ",
        variantlar: ["Kitob sumkada", "Kitob stol ostida", "Kitob stolning ustida", "Kitob yerdagi stol"],
        togri: 2,
        izoh: "عَلَى — ustida/ustiga; الطَّاوِلَة — stol",
      },
      {
        id: 4,
        matn: "'Maktabdan' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["إِلَى الْمَدْرَسَةِ", "فِي الْمَدْرَسَةِ", "مِنَ الْمَدْرَسَةِ", "عَلَى الْمَدْرَسَةِ"],
        togri: 2,
        izoh: "مِنْ — dan/manba bildiradi: مِنَ الْمَدْرَسَةِ = maktabdan",
      },
      {
        id: 5,
        matn: "Sifat otdan qayerda turadi?",
        arabcha: undefined,
        variantlar: ["Oldida", "Keyin", "Gapning boshida", "Gapning oxirida"],
        togri: 1,
        izoh: "Arabchada sifat (na't) doimo otdan KEYIN keladi: بَيْتٌ كَبِيرٌ = katta uy",
      },
      {
        id: 6,
        matn: "Quyidagi birikma to'g'rimi?",
        arabcha: "سَيَّارَةٌ كَبِيرَةٌ",
        variantlar: ["Ha, to'g'ri", "Yo'q, كَبِيرٌ bo'lishi kerak", "Yo'q, سَيَّارَة boshqa bo'lishi kerak", "Yo'q, tartib noto'g'ri"],
        togri: 0,
        izoh: "سَيَّارَة muannash → sifat ham muannash: كَبِيرَةٌ — to'g'ri",
      },
      {
        id: 7,
        matn: "الطَّالِبُ الْجَدِيدُ gapini tarjima qiling.",
        arabcha: "الطَّالِبُ الْجَدِيدُ",
        variantlar: ["Yangi o'quvchi (ma'lum)", "O'quvchi yangi", "Yangi o'quvchi (noma'lum)", "O'quvchilar yangi"],
        togri: 0,
        izoh: "الـ + الـ = aniq birikmali sifat: yangi o'quvchi (ma'lum, belgilangan)",
      },
      {
        id: 8,
        matn: "O'tgan zamon fe'lida 2-shaxs yagona erkak qo'shimchasi qaysi?",
        arabcha: undefined,
        variantlar: ["تُ", "تَ", "تِ", "نَا"],
        togri: 1,
        izoh: "كَتَبْتَ (katabta) — sen yozding (erkak): قo'shimcha = تَ",
      },
      {
        id: 9,
        matn: "'Uyda' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["عَلَى الْبَيْتِ", "مِنَ الْبَيْتِ", "فِي الْبَيْتِ", "إِلَى الْبَيْتِ"],
        togri: 2,
        izoh: "فِي — da/ichida: فِي الْبَيْتِ = uyda",
      },
      {
        id: 10,
        matn: "Quyidagi so'z aniqmi yoki noaniqmi?",
        arabcha: "الْقَلَمُ",
        variantlar: ["Noaniq (tanvin bor)", "Aniq (الـ bor)", "Ko'plik", "Fe'l"],
        togri: 1,
        izoh: "الـ artikli so'zni aniq qiladi: الْقَلَمُ = qalam (ma'lum, aniq)",
      },
    ],
  },

  // ─── A2 Lug'at ──────────────────────────────────────────────────────────────
  {
    id: 6,
    nomi: "A2 — Lug'at testi",
    daraja: "A2",
    tur: "lug'at",
    davomiylik: 20,
    rang: "#059669",
    icon: "📖",
    savollar: [
      {
        id: 1,
        matn: "So'zning tarjimasini toping.",
        arabcha: "ذَهَبَ",
        variantlar: ["Keldi", "Bordi", "Ko'rdi", "Yozdi"],
        togri: 1,
        izoh: "ذَهَبَ (zahaba) — bordi (o'tgan zamon, 3-shaxs erkak)",
      },
      {
        id: 2,
        matn: "So'zning tarjimasini toping.",
        arabcha: "طَاوِلَة",
        variantlar: ["Kursi", "Stol", "Deraza", "Eshik"],
        togri: 1,
        izoh: "طَاوِلَة (taawila) — stol",
      },
      {
        id: 3,
        matn: "'Tez' so'zi arabchada qanday?",
        arabcha: undefined,
        variantlar: ["كَبِير", "صَغِير", "سَرِيع", "جَدِيد"],
        togri: 2,
        izoh: "سَرِيع (sari') — tez",
      },
      {
        id: 4,
        matn: "So'zning tarjimasini toping.",
        arabcha: "أَكَلَ",
        variantlar: ["Ichdi", "Yedi", "O'qidi", "Yozdi"],
        togri: 1,
        izoh: "أَكَلَ (akala) — yedi (o'tgan zamon)",
      },
      {
        id: 5,
        matn: "So'zning tarjimasini toping.",
        arabcha: "نَافِذَة",
        variantlar: ["Eshik", "Stol", "Deraza", "Devor"],
        togri: 2,
        izoh: "نَافِذَة (naafiza) — deraza",
      },
      {
        id: 6,
        matn: "'Yangi' so'zi arabchada qanday (muannash shakl)?",
        arabcha: undefined,
        variantlar: ["جَدِيد", "جَدِيدَة", "قَدِيم", "قَدِيمَة"],
        togri: 1,
        izoh: "جَدِيدَة (jadiida) — yangi (muannash), جَدِيد — erkak shakl",
      },
      {
        id: 7,
        matn: "So'zning tarjimasini toping.",
        arabcha: "شَرِبَ",
        variantlar: ["Yedi", "Yozdi", "Ichdi", "Bordi"],
        togri: 2,
        izoh: "شَرِبَ (shariba) — ichdi (o'tgan zamon)",
      },
      {
        id: 8,
        matn: "So'zning tarjimasini toping.",
        arabcha: "كُرْسِي",
        variantlar: ["Stol", "Kursi", "Kitob", "Qalam"],
        togri: 1,
        izoh: "كُرْسِي (kursiy) — kursi",
      },
      {
        id: 9,
        matn: "'Baland/uzun' arabchada qanday?",
        arabcha: undefined,
        variantlar: ["قَصِير", "طَوِيل", "كَبِير", "صَغِير"],
        togri: 1,
        izoh: "طَوِيل (tawiil) — uzun/baland, قَصِير esa qisqa/past",
      },
      {
        id: 10,
        matn: "So'zning tarjimasini toping.",
        arabcha: "غُرْفَة",
        variantlar: ["Hovli", "Xona/uy xonasi", "Maktab", "Do'kon"],
        togri: 1,
        izoh: "غُرْفَة (ghurfa) — xona (uy ichidagi xona)",
      },
    ],
  },

  // ─── B1 Grammatika ──────────────────────────────────────────────────────────
  {
    id: 7,
    nomi: "B1 — Grammatika testi",
    daraja: "B1",
    tur: "grammatika",
    davomiylik: 25,
    rang: "#2563EB",
    icon: "🧠",
    savollar: [
      {
        id: 1,
        matn: "Hozirgi/kelasi zamon fe'li qanday yasaladi?",
        arabcha: "يَكْتُبُ",
        variantlar: ["O'tgan zamon, 3-shaxs erkak", "Hozirgi zamon, 3-shaxs erkak", "Buyruq mayli", "Inkor"],
        togri: 1,
        izoh: "يَكْتُبُ (yaktubu) — u yozadi/yozmoqda: hozirgi/kelasi zamon, 3-shaxs erkak",
      },
      {
        id: 2,
        matn: "Hozirgi zamonda 1-shaxs shakli qaysi?",
        arabcha: "يَكْتُبُ → ?",
        variantlar: ["نَكْتُبُ", "أَكْتُبُ", "تَكْتُبُ", "يَكْتُبَانِ"],
        togri: 1,
        izoh: "أَكْتُبُ (aktubu) — men yozaman: 1-shaxs yagona, hozirgi zamon (أ- prefiksi)",
      },
      {
        id: 3,
        matn: "Quyidagi inkor gapni tarjima qiling.",
        arabcha: "لَا أَفْهَمُ",
        variantlar: ["Men tushundim", "Men tushunaman", "Men tushunmayapman", "U tushunmaydi"],
        togri: 2,
        izoh: "لَا + fe'l = inkor: لَا أَفْهَمُ = men tushunmayapman/tushunmayman",
      },
      {
        id: 4,
        matn: "Masdar (infinitiv) qaysi?",
        arabcha: undefined,
        variantlar: ["كَتَبَ", "يَكْتُبُ", "كِتَابَة", "كَاتِب"],
        togri: 2,
        izoh: "كِتَابَة (kitaaba) — yozish (masdar/infinitiv), كَتَبَ = yozdi, يَكْتُبُ = yozadi",
      },
      {
        id: 5,
        matn: "Shart gapida qaysi bog'lovchi ishlatiladi?",
        arabcha: undefined,
        variantlar: ["وَ (va)", "أَوْ (yoki)", "إِذَا (agar)", "لَكِنْ (lekin)"],
        togri: 2,
        izoh: "إِذَا (iza) — agar: shart gaplarida ishlatiladi. إِذَا دَرَسْتَ نَجَحْتَ = agar o'qisang, muvaffaq bo'lasan",
      },
      {
        id: 6,
        matn: "Quyidagi jumla to'g'ri tarjima qilinganmi?",
        arabcha: "كَانَ الطَّقْسُ بَارِدًا",
        variantlar: ["Havo sovuq", "Havo sovuq edi", "Havo issiq edi", "Havo issiq bo'ladi"],
        togri: 1,
        izoh: "كَانَ — o'tgan zamonda 'bo'lmoq/edi': كَانَ ... بَارِدًا = sovuq edi",
      },
      {
        id: 7,
        matn: "Hol (zarf) qaysi javobda to'g'ri?",
        arabcha: undefined,
        variantlar: ["بَيْتٌ كَبِيرٌ", "كَتَبَ بِسُرْعَةٍ", "هُوَ طَالِبٌ", "الْكِتَابُ جَدِيدٌ"],
        togri: 1,
        izoh: "كَتَبَ بِسُرْعَةٍ (kataba bisur'atin) — u tez yozdi: بِسُرْعَةٍ holdir (qanday yozdi?)",
      },
      {
        id: 8,
        matn: "'Agar yog'in yog'sa, uyda qolaman' gapidagi shart qo'shimchasi qaysi?",
        arabcha: "إِذَا أَمْطَرَتْ، بَقِيتُ فِي الْبَيْتِ",
        variantlar: ["بَقِيتُ", "أَمْطَرَتْ", "إِذَا", "فِي الْبَيْتِ"],
        togri: 2,
        izoh: "إِذَا — 'agar' ma'nosida shart bog'lovchisi",
      },
      {
        id: 9,
        matn: "Juft son (ikkilik) qo'shimchasi qaysi?",
        arabcha: undefined,
        variantlar: ["ون-", "ات-", "ان-", "ين-"],
        togri: 2,
        izoh: "كِتَابَانِ (kitabani) — ikki kitob: -ان qo'shimchasi yagonani ikkiga aylantiradi",
      },
      {
        id: 10,
        matn: "Faol ism (ism fa'il) qaysi?",
        arabcha: undefined,
        variantlar: ["مَكْتُوب (yozilgan)", "كِتَابَة (yozish)", "كَاتِب (yozuvchi)", "كَتَبَ (yozdi)"],
        togri: 2,
        izoh: "كَاتِب (katib) — yozuvchi: faol ism (ism fa'il) — ish bajaruvchi shaxs",
      },
    ],
  },

  // ─── B1 Umumiy ──────────────────────────────────────────────────────────────
  {
    id: 8,
    nomi: "B1 — Umumiy test",
    daraja: "B1",
    tur: "umumiy",
    davomiylik: 25,
    rang: "#DC2626",
    icon: "🏆",
    savollar: [
      {
        id: 1,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "أُحِبُّ تَعَلُّمَ اللُّغَةِ الْعَرَبِيَّةِ",
        variantlar: [
          "U arabcha o'rganishni yaxshi ko'radi",
          "Men arabcha o'rganishni yaxshi ko'raman",
          "Biz arabcha o'rganamiz",
          "Sen arabcha bilasan",
        ],
        togri: 1,
        izoh: "أُحِبُّ — men yaxshi ko'raman (1-shaxs); تَعَلُّم — o'rganish (masdar)",
      },
      {
        id: 2,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مَطَار",
        variantlar: ["Temir yo'l", "Kemaxona", "Aeroport", "Avtobus bekat"],
        togri: 2,
        izoh: "مَطَار (mataar) — aeroport",
      },
      {
        id: 3,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "لَمْ أَذْهَبْ إِلَى الْعَمَلِ الْيَوْمَ",
        variantlar: [
          "Men bugun ishga boraman",
          "Men bugun ishga bormadim",
          "U bugun ishga bormadi",
          "Men kecha ishga bormadim",
        ],
        togri: 1,
        izoh: "لَمْ + mudori' majzum = o'tgan zamonda inkor: لَمْ أَذْهَبْ = men bormadim; الْيَوْمَ = bugun",
      },
      {
        id: 4,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مُهَنْدِس",
        variantlar: ["Shifokor", "Muhandis/muallim", "Muhandis/injener", "Savdogar"],
        togri: 2,
        izoh: "مُهَنْدِس (muhandis) — muhandis, injener",
      },
      {
        id: 5,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "كُنْتُ أَعِيشُ فِي الْقَاهِرَةِ",
        variantlar: [
          "Men Qohirada yashayman",
          "Men Qohirada yashar edim",
          "U Qohirada yashadi",
          "Biz Qohirada yashaymiz",
        ],
        togri: 1,
        izoh: "كُنْتُ أَعِيشُ — men yashar edim (davomli o'tgan zamon): كَانَ + hozirgi fe'l",
      },
      {
        id: 6,
        matn: "So'zning tarjimasini toping.",
        arabcha: "اِجْتِمَاع",
        variantlar: ["Dam olish", "Uchrashuv/yig'ilish", "Imtihon", "Safar"],
        togri: 1,
        izoh: "اِجْتِمَاع (ijtima') — yig'ilish, uchrashuv",
      },
      {
        id: 7,
        matn: "Quyidagi gapni to'ldiring.",
        arabcha: "سَأَذْهَبُ إِلَى السُّوقِ ___ أَشْتَرِيَ خُضَارًا",
        variantlar: ["لِأَنَّ", "وَلَكِنْ", "لِ (uchun)", "إِذَا"],
        togri: 2,
        izoh: "لِ + fe'l = uchun/maqsadida: سَأَذْهَبُ لِأَشْتَرِيَ = boraman, sabzavot sotib olish uchun",
      },
      {
        id: 8,
        matn: "So'zning tarjimasini toping.",
        arabcha: "صَعْب",
        variantlar: ["Oson", "Qiziq", "Qiyin", "Chiroyli"],
        togri: 2,
        izoh: "صَعْب (sa'b) — qiyin, murakkab. Aksi: سَهْل (sahl) = oson",
      },
      {
        id: 9,
        matn: "Quyidagi gapni tarjima qiling.",
        arabcha: "أَتَكَلَّمُ الْعَرَبِيَّةَ قَلِيلًا",
        variantlar: [
          "Men arabchani yaxshi bilaman",
          "Men arabchani ozgina gapiraman",
          "U arabchani o'rganadi",
          "Men arabchani o'rganmoqchiman",
        ],
        togri: 1,
        izoh: "أَتَكَلَّمُ = men gapiraman; قَلِيلًا = ozgina, sal",
      },
      {
        id: 10,
        matn: "So'zning tarjimasini toping.",
        arabcha: "مُتَعَب",
        variantlar: ["Xursand", "Charchagan", "Kasal", "Ochigan"],
        togri: 1,
        izoh: "مُتَعَب (muta'ab) — charchagan, holdan toygan",
      },
    ],
  },
];
