import type { NazDars } from "./types";

export const NAZARIY: NazDars[] = [
  {id:1,nomi:"Arab Yozuviga Kirish",icon:"أ",color:"green",
   mavzu:`# Arab Yozuviga Kirish\n\n## Asosiy Xususiyatlar\nArab yozuvi o'ngdan chapga yoziladi. **28 ta harf** bor. Faqat **6 ta harf** faqat o'ng tomoniga ulanadi: **ا د ذ ر ز و**\n\n---\n\n## Harflarning 4 xil Ko'rinishi\n\n| № | Harf | Mustaqil | Boshi | O'rtasi | Oxiri |\n|---|------|----------|-------|---------|-------|\n|1|Alif|ا|ا|ـا|ـا|\n|2|Ba|ب|بـ|ـبـ|ـب|\n|3|Ta|ت|تـ|ـتـ|ـت|\n|4|Jim|ج|جـ|ـجـ|ـج|\n|5|Dal|د|د|ـد|ـد|\n|6|Sin|س|سـ|ـسـ|ـس|\n|7|Ayn|ع|عـ|ـعـ|ـع|\n|8|Fa|ف|فـ|ـفـ|ـف|\n\n---\n\n## Faqat O'ng Tomonga Ulanadiganlar (6 ta)\n\n| Harf | Nomi | Misol |\n|------|------|-------|\n|ا|Alif|كِتَاب|\n|د|Dal|وَلَد|\n|ذ|Zal|هَذَا|\n|ر|Ra|دَرْس|\n|ز|Zayn|بَارِز|\n|و|Vov|يَوْم|`,
   vazifalar:[
     {id:1,savol:"Arab alifbosida nechta harf bor?",variantlar:["24","26","28","30"],togri:2},
     {id:2,savol:"Faqat o'ng tomonga ulanadiganlar nechta?",variantlar:["4","5","6","7"],togri:2},
     {id:3,savol:"Arab yozuvi qaysi tomonga yoziladi?",variantlar:["Chapdan o'ngga","O'ngdan chapga","Yuqoridan pastga","Istalgan"],togri:1},
     {id:4,savol:"Har bir harf necha xil ko'rinishda?",variantlar:["2","3","4","5"],togri:2},
     {id:5,savol:"ر harfi qaysi guruhga kiradi?",variantlar:["Ikki tomonga","Faqat o'ng tomonga","Ulanmaydi","Lab harfi"],togri:1},
   ]},
  {id:2,nomi:"28 ta Arab Harfi",icon:"ب",color:"deep",
   mavzu:`# 28 ta Arab Harfi\n\n## Asosiy Jadval\n\n| Harf | Nomi | Holati |\n|------|------|--------|\n|ث|Sa|**Tilni chiqarib**|\n|ح|Ha|**Yo'q** — chuqur nafas|\n|ذ|Zal|**Tilni chiqarib**|\n|ص|Sod|**Yo'q** — qalin s|\n|ض|Dod|**Yo'q** — qalin d|\n|ط|To|**Yo'q** — qalin t|\n|ظ|Zo|**Tilni chiqarib qalin**|\n|ع|Ayn|**Yo'q** — tomoqdan|\n\n## Tilni Chiqarib 3 Harf\n\n| Harf | Jaranglilik |\n|------|-------------|\n|ث|Jarangsiz|\n|ذ|Jarangli|\n|ظ|Jarangli, qalin|`,
   vazifalar:[
     {id:1,savol:"Tilni chiqarib etiladigan harflar nechtasi?",variantlar:["2","3","4","5"],togri:1},
     {id:2,savol:"ع (Ayn) ni to'g'ri tavsifla:",variantlar:["Oddiy 'a'","Tomoqni siqib jarangli","Lab harfi","Burun harfi"],togri:1},
     {id:3,savol:"ص va س farqi:",variantlar:["Shakli","Sod qalin, Sin ingichka","Burundan","Yo'q"],togri:1},
     {id:4,savol:"ث qaysi oiladan?",variantlar:["Lab","Tomoq","Interdental","Burun"],togri:2},
     {id:5,savol:"ذ va ز farqi:",variantlar:["Zal tilni chiqarib","Bir xil","Zayn tilni chiqarib","Yo'q"],togri:0},
   ]},
  {id:3,nomi:"4 ta Asosiy Harakat",icon:"َ",color:"lime",
   mavzu:`# To'rtta Asosiy Harakat\n\n## 1. فَتْحَة — Fatha ( َ )\n**"A" tovushi** · Harfning ustida\n\n| Arab | O'qilishi | Ma'nosi |\n|------|-----------|---------|\n|كَتَبَ|kataba|yozdi|\n|ذَهَبَ|zahaba|ketdi|\n|فَتَحَ|fataha|ochdi|\n\n## 2. كَسْرَة — Kasra ( ِ )\n**"I" tovushi** · Harfning ostida\n\n| Arab | O'qilishi | Ma'nosi |\n|------|-----------|---------|\n|كِتَاب|kitaab|kitob|\n|مِنْ|min|dan|\n|فِيل|fiil|fil|\n\n## 3. ضَمَّة — Damma ( ُ )\n**"U" tovushi** · Harfning ustida\n\n| Arab | O'qilishi | Ma'nosi |\n|------|-----------|---------|\n|نُور|nuur|nur|\n|كُتُب|kutub|kitoblar|\n\n## 4. سُكُون — Sukun ( ْ )\n**Harakat YO'Q** · Harfning ustida\n\n| Arab | O'qilishi | Ma'nosi |\n|------|-----------|---------|\n|بَيْت|bayt|uy|\n|عِلْم|ilm|bilim|`,
   vazifalar:[
     {id:1,savol:"Kasra qaerda yoziladi?",variantlar:["Ustida","Ostida","O'ngida","Chapida"],togri:1},
     {id:2,savol:"بُ qanday o'qiladi?",variantlar:["ba","bi","bu","b"],togri:2},
     {id:3,savol:"Sukun nimani bildiradi?",variantlar:["Uzun a","Harakat yo'q","Ikki marta","U ovozi"],togri:1},
     {id:4,savol:"كَتَبَ da qaysi harakatlar?",variantlar:["3 kasra","3 fatha","3 damma","3 sukun"],togri:1},
     {id:5,savol:"Damma qanday o'qiladi?",variantlar:["a","i","u","yo'q"],togri:2},
   ]},
  {id:4,nomi:"Maxraj Ilmi",icon:"م",color:"green",
   mavzu:`# Maxraj Ilmi\n\n**Maxraj** — harfning chiqish joyi.\n\n## 5 ta Maxraj\n\n### 1. Jawf (3 harf)\nا و ي — cho'zilib chiqadi\n\n### 2. Halq (6 harf)\n\n| Qavat | Harflar |\n|-------|--------|\n|Adnal (yuqori)|ء ه|\n|Vasat (o'rta)|ع ح|\n|Aqsal (quyi)|غ خ|\n\n**Hamza ء — Adnal Halqdan!**\n\n### 3. Lison (18 harf)\nTilning turli qismlari\n\n### 4. Shafatayn (4 harf)\nف ب م و\n\n### 5. Xayshum\nG'unna — ن م`,
   vazifalar:[
     {id:1,savol:"Hamza qaysi maxrajdan?",variantlar:["Aqsal Halq","Vasat Halq","Adnal Halq","Jawf"],togri:2},
     {id:2,savol:"Lison maxrajida nechta harf?",variantlar:["14","16","18","20"],togri:2},
     {id:3,savol:"غ va خ qaysi maxrajdan?",variantlar:["Adnal","Vasat","Aqsal Halq","Shafatayn"],togri:2},
     {id:4,savol:"ف qanday chiqadi?",variantlar:["Ikki lab","Pastki lab yuqori tishga","Burundan","Tomoqdan"],togri:1},
     {id:5,savol:"Mad harflari qaysi maxrajdan?",variantlar:["Halq","Jawf","Lison","Shafatayn"],togri:1},
   ]},
  {id:5,nomi:"Sifat Ilmi",icon:"ص",color:"deep",
   mavzu:`# Sifat Ilmi\n\n**17 ta** sifat: 5 juft + 7 mustaqil.\n\n## Ziddi Bor — 5 Juft\n\n| Sifat | Ziddi |\n|-------|-------|\n|Jahr|Hams|\n|Shadid|Raxv|\n|Isti'lo|Istifol|\n|Itboq|Infitoh|\n|Izloq|Ishmoq|\n\n**Hams 10:** ت ث ح خ س ش ص ف ك ه\nYodlash: **"فَحَثَّهُ شَخْصٌ سَكَتْ"**\n\n**Itboq 4:** ص ض ط ظ\n**Tavassut 5:** ل ن ع م ر — **"لِنْ عُمَرْ"**\n**Isti'lo 7:** خ ص ض ط ظ غ ق — **"خُصَّ ضَغْطٍ قِظْ"**\n\n## Ziddi Yo'q — 7 ta\n\n| Sifat | Harflar | Ta'rif |\n|-------|---------|--------|\n|Safir|ز س ص|Hushtak|\n|Lin|و ي sukunda|Yumshoq|\n|Inhiraf|ل ر|Og'ish|\n|Takrir|ر|Titrash|\n|Tafashi|ش|Yoyilish|\n|Istitoyla|ض|Uzayish|\n|G'unna|ن م|Burun|`,
   vazifalar:[
     {id:1,savol:"Hams sifatida nechta harf?",variantlar:["8","9","10","11"],togri:2},
     {id:2,savol:"Itboq sifatiga kiruvchi harflar:",variantlar:["ص ض ط ظ","ب ر ف ل","ز س ص","ن م و ي"],togri:0},
     {id:3,savol:"'فَحَثَّهُ شَخْصٌ سَكَتْ' qaysi sifat?",variantlar:["Jahr","Hams","Isti'lo","Shadid"],togri:1},
     {id:4,savol:"Tavassut harflari:",variantlar:["ص ض ط ظ","ل ن ع م ر","ب ر ف","ء ه ع ح"],togri:1},
     {id:5,savol:"Takrir faqat qaysi harfda?",variantlar:["ل","ن","ر","م"],togri:2},
   ]},
  {id:6,nomi:"Hamza Harfi",icon:"ء",color:"lime",
   mavzu:`# Hamza Harfi — ء\n\n**Glottal stop** — Adnal Halqdan.\n\n## Hamza va Alif\n\n| | Hamza | Alif |\n|-|-------|------|\n|Tur|To'xtash|Cho'ziq|\n|Maxraj|Adnal Halq|Jawf|\n|Sifat|Shadid|Mad|\n|Misol|أَكَلَ|كِتَاب|\n\n## 5 xil Ko'rinish\n\n| Shakl | Sharti | Misol |\n|-------|--------|-------|\n|أ|Boshi fatha/damma|أَحْمَد|\n|إ|Boshi kasra|إِسْلَام|\n|ؤ|O'rta damma|يُؤْمِن|\n|ئ|O'rta kasra|بِئْر|\n|ء|Oxiri|شَيْء|\n\n## Sifatlari\n- Shadid · Jahr · Istifol · Infitoh · Ishmoq`,
   vazifalar:[
     {id:1,savol:"Hamza qaysi maxrajdan?",variantlar:["Aqsal","Vasat","Adnal Halq","Jawf"],togri:2},
     {id:2,savol:"Boshida kasra bilan hamza:",variantlar:["أ","إ","ؤ","ئ"],togri:1},
     {id:3,savol:"Hamza sifati:",variantlar:["Raxv","Shadid","G'unna","Takrir"],togri:1},
     {id:4,savol:"شَيْء dagi hamza:",variantlar:["Alif ustida","Alif ostida","Mustaqil","Vov ustida"],togri:2},
     {id:5,savol:"Hamza va Alif:",variantlar:["Bir xil","Hamza to'xtash, Alif cho'ziq","Alif jarangli","Faqat yozuvda"],togri:1},
   ]},
  {id:7,nomi:"Tarixiy Olimlar",icon:"ع",color:"green",
   mavzu:`# Fonetika Olimlari\n\n## Abu al-Asvad ad-Du'aliy\n603–688 m. · **Harakat belgilari tizimi**\n\n## Nasr ibn Osim\nvaf. 708 m. · **Nuqta tizimi** (Amir ibn Nosir emas!)\n\n## Yahyo ibn Ya'mar\nNuqta tizimini hamkorlikda ishlab chiqqan\n\n## Al-Xalil ibn Ahmad\n718–791 m. · Harakatlarni takomillashtirdi, "Kitob al-Ayn"\n\n## Sibavayhi\nAl-Xalil shogirdi · "Al-Kitab"\n\n## Xronologiya\n\n| Davr | Voqea |\n|------|-------|\n|688|Abu al-Asvad: harakatlar|\n|708|Nasr ibn Osim: nuqtalar|\n|VIII|Al-Xalil: fonetika ilmi|`,
   vazifalar:[
     {id:1,savol:"Harakat tizimini kim yaratdi?",variantlar:["Nasr ibn Osim","Al-Xalil","Abu al-Asvad","Sibavayhi"],togri:2},
     {id:2,savol:"Nuqta tizimini kim joriy qildi?",variantlar:["Abu al-Asvad","Nasr ibn Osim","Al-Xalil","Sibavayhi"],togri:1},
     {id:3,savol:"Al-Xalil lug'ati qanday tartibda?",variantlar:["Alifbo","Maxrajga ko'ra","Sifatga ko'ra","Tasodifiy"],togri:1},
     {id:4,savol:"Sibavayhi kim edi?",variantlar:["Abu al-Asvad shogirdi","Al-Xalil shogirdi","Mustaqil","Nasr shogirdi"],togri:1},
     {id:5,savol:"Abu al-Asvad harakatlarni qanday belgilagan?",variantlar:["Hozirgicha","Rangli nuqtalar","Raqamlar","Belgilamagan"],togri:1},
   ]},
  {id:8,nomi:"Umumiy Takrorlash",icon:"★",color:"deep",
   mavzu:`# Umumiy Takrorlash\n\n### Arab Yozuvi\n28 harf · o'ngdan chapga · 4 xil shakl · 6 ta faqat o'ngga\n\n### 4 Harakat\n\n| Harakat | Belgi | Ovoz |\n|---------|-------|------|\n|Fatha|بَ|a|\n|Kasra|بِ|i|\n|Damma|بُ|u|\n|Sukun|بْ|yo'q|\n\n### Maxrajlar\n\n| Maxraj | Soni |\n|--------|------|\n|Jawf|3|\n|Halq|6|\n|Lison|18|\n|Shafatayn|4|\n\n### Sifatlar — 17 ta\nJahr↔Hams · Shadid↔Raxv · Isti'lo↔Istifol · Itboq↔Infitoh · Izloq↔Ishmoq\nSafir · Lin · Inhiraf · Takrir · Tafashi · Istitoyla · G'unna\n\n### Olimlar\nAbu al-Asvad (harakat) · Nasr ibn Osim (nuqta) · Al-Xalil (fonetika)`,
   vazifalar:[
     {id:1,savol:"Hamza qaysi maxrajdan?",variantlar:["Aqsal","Vasat","Adnal Halq","Jawf"],togri:2},
     {id:2,savol:"Hams nechta harf?",variantlar:["8","9","10","11"],togri:2},
     {id:3,savol:"Al-Xalil xizmati:",variantlar:["Nuqta","Harakatlarni takomillashtirdi","Lug'at","Nahv"],togri:1},
     {id:4,savol:"Itboq harflari:",variantlar:["ب ر ف ل","ص ض ط ظ","ز س ص","ن م"],togri:1},
     {id:5,savol:"Tavassut harflari:",variantlar:["ل ن ع م ر","ص ض ط ظ","ت ث ح خ","ء ه"],togri:0},
     {id:6,savol:"ث harfi qanday?",variantlar:["Oddiy s","Tilni chiqarib jarangsiz","Qalin s","Tomoqdan"],togri:1},
     {id:7,savol:"Jawf maxrajida nechta harf?",variantlar:["2","3","4","5"],togri:1},
     {id:8,savol:"Safir harflari:",variantlar:["ل ر","ز س ص","ن م","و ي"],togri:1},
     {id:9,savol:"Nasr ibn Osim — xato ism:",variantlar:["Abu al-Asvad","Yahyo","Amir ibn Nosir","Al-Xalil"],togri:2},
     {id:10,savol:"Shadid nechta harf?",variantlar:["6","7","8","9"],togri:2},
   ]},
];
